Create Chat.html
MastersAcademy/frontend-course-2020 pull request #103
Opened 2020-10-31 22:05 UTC by AzraelGoddless

2nd homework

2020-10-31 23:12 UTC, AzraelGoddless commented
первое знакомство с Литером заставило понервничать

2020-11-02 02:30 UTC, AzraelGoddless commented
![Снимок](https://user-images.githubusercontent.com/41678085/97824290-8bd79680-1ccc-11eb-8918-37cd305eeadf.JPG)

2020-11-02 17:54 UTC, TArch64 requested changes

2020-11-02 17:54 UTC, TArch64 commented on homeworks/Eduard.Kalmykov_AzraelGoddless/2-dom/Chat1.html
> +    body {
у тебе стилі дублюються тут та в css файлику

2020-11-02 17:54 UTC, TArch64 commented on homeworks/Eduard.Kalmykov_AzraelGoddless/2-dom/style.css
> +output {
у тебе на сторінці немає такого тега і стилі нічого не роблять

2020-11-02 17:54 UTC, TArch64 commented on homeworks/Eduard.Kalmykov_AzraelGoddless/2-dom/style.css
> +button {
за виключенням `body` та `html` додавай стилі тільки через класи

2020-11-02 17:54 UTC, TArch64 commented on homeworks/Eduard.Kalmykov_AzraelGoddless/2-dom/style.css
> +content {
`sidebar, content` в CSS таких тегів немає

2020-11-02 17:54 UTC, TArch64 commented on homeworks/Eduard.Kalmykov_AzraelGoddless/2-dom/script.js
> +const button = document.querySelector('button');
шукай елементи в домі через `data-` атрибути

2020-11-02 17:54 UTC, TArch64 commented on homeworks/Eduard.Kalmykov_AzraelGoddless/2-dom/script.js
> +button.onclick = function () {
використовуй `addEventListener`. Всі інші варіанти в реальних задачах не використовуються

2020-11-02 17:54 UTC, TArch64 commented on homeworks/Eduard.Kalmykov_AzraelGoddless/2-dom/script.js
> +const inputIn = document.querySelector('.input-in');
додавай до змінних куди ти кладеш елементи дому суфікс `El`

2020-11-02 17:55 UTC, TArch64 commented
немає лінки на GitHub Pages

2020-11-02 17:57 UTC, TArch64 commented
Виглядає так наче ти завантажував файли через UI ГітХаба. Не роби так. Це найгірший шлях роботи з гітом. Навчися використовувати гіт по нормальному бо це така штука з якою ти в будь-якому випадку зіткнешся і краще раніше навчитися з ним працювати, поки є час

2020-11-05 06:58 UTC, TArch64 commented
Пулл реквест все ще вимагає правок і не встиг по делайну

2020-11-05 06:58 UTC, closed without merging