3 async
MastersAcademy/frontend-course-2020 pull request #113
Opened 2020-11-05 09:16 UTC by Anton-Mosquito

https://anton-mosquito.github.io/frontend-course-2020/homeworks/anton.komarnitskyi_Anton-Mosquito/3-async/
![Снимок экрана от 2020-11-05 11-15-27](https://user-images.githubusercontent.com/69711709/98221442-4e873900-1f58-11eb-8205-81b48e74c828.png)

2020-11-05 09:29 UTC, Anton-Mosquito commented
Подскажите пожалуйста как разрешить данный конфликт.

2020-11-05 09:30 UTC, powerbot15 requested changes
Еще до проверки кода могу сказать - сортировка должна комбинироваться с поиском. То есть если юзер отсортировал по A-Z, то когда он ищет что-то, результаты поиска тоже должны быть отсортированы по A-Z. И наоборот, если юзер что-то нашел и потом выбирает сортировку, то отсортироваться должны только результаты поиска.

2020-11-05 09:52 UTC, powerbot15 commented
Это не конфликт, так работает поиск и фильтры на всех сайтах)) Просто перед показом найденных постов учитывай, что у тебя есть сортировка и если она применена, сортируй найденное. Соответственно в обратном случае при применении сортировки учитывай, что ты показал юзеру не все посты, а только найденные и сортируй только их

2020-11-05 10:01 UTC, Anton-Mosquito commented
я имел виду конфликт в файле package-lock.json. Сортировку и фильтрацию исправлю

2020-11-05 10:17 UTC, powerbot15 commented
Вернись в ветку мастер, скопируй оттуда содержимое этого файла в текущую ветку и запушь. На будущее просто следи, чтобы в коммиты не попадали файлы из корня проекта.

2020-11-05 10:17 UTC, powerbot15 commented
А, да, и желательно мастер сначала обновить из основного репозитория

2020-11-05 10:34 UTC, Anton-Mosquito commented
В package-lock.json  из мастера скопировал все содержимое и запушил. Фильтр работает в тандеме с сортировкой, вроде бы) но почему то конфликт не исчезает

2020-11-05 11:55 UTC, powerbot15 commented
Значит ты не обновил свой мастер из главного репозитория https://github.com/MastersAcademy/frontend-course-2020

2020-11-06 12:08 UTC, powerbot15 requested changes
По коду в целом ок, но есть бажинка - когда удаляешь пост, он должен удаляться и из данных, не только элемент. То есть я удалил пост, делаю повторный поиск, а пост опять есть)) Поправь плиз и будем мерджить

2020-11-06 15:30 UTC, Anton-Mosquito commented
вроде бы и фиксанул баг но что-то мне не нравится. Все дело в том что я проявил инициативу что бы не рендерить результат каждый раз ни и получилось что та же инициатива возлюбит же инициатора)) короче пойду напьюсь, завтра уже будут новые идеи  и думаю сделаю апгрейд

2020-11-07 18:39 UTC, powerbot15 approved these changes

2020-11-07 18:40 UTC, merged