3-async
MastersAcademy/frontend-course-2020 pull request #114
Opened 2020-11-05 10:51 UTC by batteryfree

[Pages](https://batteryfree.github.io/frontend-course-2020//homeworks/roman.vlasov_batteryfree/3-async/)
![image](https://user-images.githubusercontent.com/44664353/98231791-8fd21580-1f65-11eb-8bb1-32c9d22b3c0f.png)

2020-11-05 11:46 UTC, TArch64 requested changes

2020-11-05 11:46 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/3-async/app/app.js
> +function sortPosts() {
Через функції це все доволі не зрозуміло і перемішано. Зроби через класи

2020-11-05 11:46 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/3-async/app/app.js
> +listPosts.setAttribute('class', 'container posts');
з класами працюй через методи `classList`

2020-11-05 11:46 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/3-async/app/app.js
> +const post = document.querySelector('[data-ctrls-tmp]').content.querySelector('[data-post]');
`document.querySelector('[data-ctrls-tmp]')` поклади в константу а потім з неї шукай елементи

2020-11-05 11:46 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/3-async/index.html
> +                    <option>Unsorted</option>
при зміні сортування в селекторі в списку нічого не змінюється

2020-11-05 11:46 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/3-async/index.html
> +    <template data-ctrls-tmp>
краще зроби одну темплату для ui апа, а іншу для елементу списка

2020-11-05 11:46 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/3-async/index.html
> +        <div data-ctrls class="container ctrls">
не використовуй скорочення в коді, окрім загально прийнятих. Це тільки додає незрозумілості в код

2020-11-06 07:15 UTC, batteryfree commented on homeworks/roman.vlasov_batteryfree/3-async/index.html
> +                    <option>Unsorted</option>
Вибач, не розумію що маєш на увазі в цьому зауваженні.
Перефрозуй або ростлумачь, будь ласка.

2020-11-06 15:03 UTC, TArch64 requested changes

2020-11-06 15:03 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/3-async/app/app.js
> +        this.elements.root.removeChild(this.elements.root.firstElementChild);
`firstElementChild` не є хорошо бо ще зав'язка на структурі твого хтмл. Додай на лодер дата-атрибут та зроби
```js
this.elements.loader.remove()
```

2020-11-06 15:03 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/3-async/app/app.js
> +        this.elements.root.removeChild(this.elements.root.querySelector('[data-posts]'));
Чому не так?
```js
this.elements.listPosts.remove();
```

2020-11-06 15:03 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/3-async/app/app.js
> +        this.filtredPosts = [].concat(this.posts.filter((post) => {
для чого `[].concat`?

2020-11-06 15:03 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/3-async/app/app.js
> +                buttonDelPost.parentNode.style.display = 'none';
винеси рендер елемента списку в окремий метод. Також винеси видалення в окремий метод

2020-11-07 08:20 UTC, batteryfree commented on homeworks/roman.vlasov_batteryfree/3-async/app/app.js
> +        this.elements.root.removeChild(this.elements.root.querySelector('[data-posts]'));
his.elements.listPosts не розміщується в документі, з нього тільки клонується.
Якщо використовувати «remove ()» то доведеться знову його створювати.
Так що буде ось так «this.elements.root.querySelector ('[data-posts]').remove();»

2020-11-07 09:58 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/3-async/index.html
> +                    <option>Unsorted</option>
Тут уже все ок. До цього у мена сторінці не працювало сортування

2020-11-07 10:00 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/3-async/app/app.js
> +        this.elements.root.removeChild(this.elements.root.querySelector('[data-posts]'));
Тоді зроби `this.templateElements` І пенеси туди темплати, а в `elements` Клади тільки ті які в тебе є в домі

2020-11-07 10:14 UTC, TArch64 requested changes

2020-11-07 10:14 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/3-async/app/app.js
> +        this.elements.root.querySelector('[data-posts]').remove();
У тебе тут незрозуміло. Частина елементів дістається через поле `elements` А частину шукаєш на ходу. Зроби щоб скрізь було однаково

2020-11-07 10:14 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/3-async/app/app.js
> +        this.filtredPosts = this.posts.filter((post) => {
```js
const query = input.value.toLowerCase()
```
Закинь перед викликом фільтра обробку значення інпута, бо цей зараз заново робиться для кожноі ітерацї

2020-11-07 10:14 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/3-async/app/app.js
> +    delPost(element, button) {
Не скор назв

2020-11-07 10:14 UTC, TArch64 commented on homeworks/roman.vlasov_batteryfree/3-async/app/app.js
> +            buttonDelPost.parentNode.style.display = 'none';
`parentNode` Не є добре бо це зав‘язка твоєї логіки на темплаті. Прокинь сюди елемент поста, який ти створюєш трохи вище

2020-11-07 12:36 UTC, TArch64 approved these changes

2020-11-07 12:37 UTC, merged