Anton Nemesh, Homework #3 AsyncJS
MastersAcademy/frontend-course-2020 pull request #117
Opened 2020-11-05 19:30 UTC by AntonNemesh

2020-11-06 07:37 UTC, AlexKuskov commented
Закинь, будь ласка, ссилку на гітхаб пейджс

2020-11-06 15:40 UTC, AlexKuskov commented on homeworks/anton.nemesh_AntonNemesh/3-async/style.css
> +  font-weight: 700;
це можна закинути в 	`.deleteButton` правило вище

2020-11-06 15:40 UTC, AlexKuskov commented on homeworks/anton.nemesh_AntonNemesh/3-async/index.html
> +        </div>
було б непогано закинути фільр і сорт в хедер елемент

2020-11-06 15:40 UTC, AlexKuskov commented on homeworks/anton.nemesh_AntonNemesh/3-async/style.css
> +  float: right;
уже вийшли кращі інструменти за допомогою яких можна вирівнювати елементи набагато зручніше. Наприклад flexbox. 
![image](https://user-images.githubusercontent.com/24815257/98382752-43b1ce80-2054-11eb-8904-d6dc5aedb174.png)
можеш навісити флексбокс на хедер елемент, і вирівняти його елементи по краям

2020-11-06 15:40 UTC, AlexKuskov commented on homeworks/anton.nemesh_AntonNemesh/3-async/style.css
> +  float: left;
тут те саме, що я писав на рахунок флоута вище

2020-11-06 15:40 UTC, AlexKuskov commented on homeworks/anton.nemesh_AntonNemesh/3-async/main.js
> +buttonDefault.addEventListener('click', () => { showData().then(); });
`showData().then();` тут '.then();' не треба писати щоб фунція
виконувалась

2020-11-06 15:40 UTC, AlexKuskov commented on homeworks/anton.nemesh_AntonNemesh/3-async/main.js
> +buttonSort.addEventListener('click', () => { showData('sort').then(); });
в тебе виходить так, що кожен раз, коли ти хочеш пересортувати елементи, ти шлеш запит на бекенд. Це не круто, тому що перевантажує бекенд + це довше аніж просто локально міняти порядок елементів.

Кращий варіант - зтягнути їх перший раз, коли загружається сторінка. зберегти їх, і потім маніпулювати з ними локально.

2020-11-07 08:25 UTC, AlexKuskov commented on homeworks/anton.nemesh_AntonNemesh/3-async/style.css
> +  float: right;
можна більш детально почитати про цю штуку тут:
https://css-tricks.com/snippets/css/a-guide-to-flexbox/

2020-11-07 08:28 UTC, AlexKuskov commented
гітхаб пейджс сторінка не доступна по твоїй ссилці
![image](https://user-images.githubusercontent.com/24815257/98436437-e6fdf480-20e3-11eb-8426-ed3cf0ec8e98.png)

2020-11-07 08:33 UTC, AlexKuskov commented
Також деякі коменти все ще не виправлені. 
Добречі, коли виправляєш якийсь із пунктів, то нажимай на резолв, щоб я бачив, що саме ти вже виконав.
![image](https://user-images.githubusercontent.com/24815257/98436503-68558700-20e4-11eb-9cf6-6a99ceb228f1.png)

2020-11-07 15:41 UTC, AntonNemesh commented
> гітхаб пейджс сторінка не доступна по твоїй ссилці
> ![image](https://user-images.githubusercontent.com/24815257/98436437-e6fdf480-20e3-11eb-8426-ed3cf0ec8e98.png)

I have fixed this bug, you can try to use this link again.

2020-11-07 16:08 UTC, AlexKuskov requested changes
Зараз коли застосовується сортування, то результати фільтру скидуються і всі пости показуються. Потрібно, щоб сортувались елементи які були відфільтровані

2020-11-09 19:22 UTC, AlexKuskov requested changes
Виправ будь ласка всі непорезолвені коменти які залишились
![image](https://user-images.githubusercontent.com/24815257/98586570-8df3b380-22d1-11eb-9b85-4bd443d11616.png)

2020-11-09 19:22 UTC, AlexKuskov commented on homeworks/anton.nemesh_AntonNemesh/3-async/main.js
> +dropdownSort.addEventListener('change', () => { sortData(); showData(); });
коли в функції виконується декілька команд. То краще це писати не в 1 строчку
замість `() => { sortData(); showData(); }`
ось так
```
dropdownSort.addEventListener('change', () => {
  sortData();
  showData();
});
```
так більш читабельно

2020-11-10 06:33 UTC, AlexKuskov approved these changes
Все ок. Також добавив 2 комента, що можна було б покращити, але це не критично.

2020-11-10 06:33 UTC, AlexKuskov commented on homeworks/anton.nemesh_AntonNemesh/3-async/index.html
> +        <div class="header">
зі сторони семантики добавлю, що є ще хедер тег, який можна використовувати замість `<div>` в цьому випадку
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header

2020-11-10 06:33 UTC, AlexKuskov commented on homeworks/anton.nemesh_AntonNemesh/3-async/style.css
> +  flex-direction: row;
якщо тобі потрібно `flex-direction: row;` то його не обовязково зазначати, так як воно ставиться по дефолту. Якщо ж тобі треба щоб елементи були по вертикалі, то треба явно вказувати `flex-direction: column;`

2020-11-10 06:46 UTC, merged