3-async
MastersAcademy/frontend-course-2020 pull request #122
Opened 2020-11-06 10:44 UTC by Evapavl

screenshot:
https://prnt.sc/vekukh

githubPage:
https://evapavl.github.io/frontend-course-2020/homeworks/eva.pavlenko_Evapavl/3-async/

2020-11-06 15:58 UTC, MZabolotnev submitted a review, later dismissed
При открытии страницы - бесконечный спиннер загрузки , показ постов происходит только после взаимодействия с сортировкой или фильтром.

2020-11-06 15:58 UTC, MZabolotnev commented on homeworks/eva.pavlenko_Evapavl/3-async/script/script.js
> +    console.log(url);
Перед пушем удаляй логи :)

2020-11-07 13:06 UTC, TArch64 requested changes

2020-11-07 13:06 UTC, TArch64 commented on homeworks/eva.pavlenko_Evapavl/3-async/script/script.js
> +            const query = `&title_like=${inputFilter.value}`;
Тут так же як ти передаєш параметр пошуку передавай і для сортування

2020-11-07 15:33 UTC, TArch64 requested changes

2020-11-07 15:33 UTC, TArch64 commented on homeworks/eva.pavlenko_Evapavl/3-async/script/script.js
> +    const fromAtoZ = `${defaultUrl}_sort=title&_order=asc`;
Я трохи не про те. Залиш тут тільки одну url і назви її якось POSTS_API_URL а оці опиои _sort та _order додавай всередині функції sorting

2020-11-07 15:33 UTC, TArch64 commented on homeworks/eva.pavlenko_Evapavl/3-async/script/script.js
> +        const rows = posts.map(({ body, title, id }) => `<div data-${id} class="post">
Тут можна без змінної rows одразу покласти в postNode.innerHTML

2020-11-07 15:33 UTC, TArch64 commented on homeworks/eva.pavlenko_Evapavl/3-async/script/script.js
> +        const rows = posts.map(({ body, title, id }) => `<div data-${id} class="post">
Заміни `data-${id} ` на `data-post=“${id}”`. Так набагато зрозуміліше що це таке і при цьому ти зможеш знайти як всі пости на сторінці так і один окремо

2020-11-07 16:21 UTC, TArch64 approved these changes

2020-11-07 16:26 UTC, merged