3 Homework (Asynchronous JS)
MastersAcademy/frontend-course-2020 pull request #125
Opened 2020-11-06 18:36 UTC by IlyaBielov

https://ilyabielov.github.io/frontend-course-2020/homeworks/ilya.bielov_IlyaBielov/3-async/index.html
![Screenshot from 2020-11-06 20-29-25](https://user-images.githubusercontent.com/37895784/98402219-9ea4ef00-206f-11eb-998e-09017f64695e.png)

2020-11-07 14:40 UTC, AlexKuskov requested changes
Не вистачає дефолтного значення
![image](https://user-images.githubusercontent.com/24815257/98444019-ebdc9b80-2117-11eb-9208-d7d957751ca5.png)

2020-11-07 15:00 UTC, AlexKuskov requested changes

2020-11-07 15:00 UTC, AlexKuskov commented on homeworks/ilya.bielov_IlyaBielov/3-async/index.html
> +    <div class="border fullHeight">
`fullHeight` виглядає як зайвий селектор

2020-11-07 15:00 UTC, AlexKuskov commented on homeworks/ilya.bielov_IlyaBielov/3-async/index.html
> +                    <input id="sort-2" type="checkbox" class="pointer" data-sort-z-a>
Чекбокси говорять про те, що декілька елементів може вибиратись.
В випадку вибору сортування більше підходить радіо баттон, він обозначає, що тільки 1 елемент серед всіх, може бути вибраний. + тобі не треба буде прибирати checked через джаваскріпт, браузер сам це зробить замість тебе

2020-11-07 15:00 UTC, AlexKuskov commented on homeworks/ilya.bielov_IlyaBielov/3-async/index.html
> +            <li data-spinner class="spinner">loading...</li>
чому спінер являється елементом списку? Можливо варто винести спінер за межі `<ul data-posts-place class="posts-place">`

2020-11-07 15:07 UTC, AlexKuskov commented
аа, зрозумів. Дефолтним значенням включається коли нічого не вибирає, зрозумів
![image](https://user-images.githubusercontent.com/24815257/98444623-61963680-211b-11eb-9251-e6271f059f48.png)

Але всеодно у чекбоксів є ціль, з якою вони використовуються - це можливість вибирати багато варіантів

2020-11-09 12:38 UTC, IlyaBielov commented on homeworks/ilya.bielov_IlyaBielov/3-async/index.html
> +            <li data-spinner class="spinner">loading...</li>
Я вирішив що спінер підгружає список постів а не "поле" в якому вони лежать (грубо говоря)
Тобто список є, але він пустий. Якщо перенести "поле" в друге місце в аплікейшену, то нічого не зміниться і додаткових враперів не потрібно.
 Соррі, але я залишу так як є.

2020-11-09 12:38 UTC, IlyaBielov commented on homeworks/ilya.bielov_IlyaBielov/3-async/index.html
> +                    <input id="sort-2" type="checkbox" class="pointer" data-sort-z-a>
Дякую. Забув що radio button є. 
А то пишу код і думаю чого я сам це перебиваю... Помню шо якось воно автоматом должно :)

2020-11-09 12:45 UTC, IlyaBielov commented on homeworks/ilya.bielov_IlyaBielov/3-async/index.html
> +    <div class="border fullHeight">
Дякую. Забув прибрати як грався із стилями.

2020-11-09 17:02 UTC, AlexKuskov commented on homeworks/ilya.bielov_IlyaBielov/3-async/index.html
> +            <li data-spinner class="spinner">loading...</li>
Окей, без проблем. Я написав цей комент тому, що те що ти вставив спінер в список постів не відповідає семантиці. ul по своїй задумці являється врапером для списку однотипних елементів (постів, котів, країн). Вставляти туди різнотипні речі, не дуже круто в плані семантики.

2020-11-09 17:03 UTC, AlexKuskov approved these changes

2020-11-09 17:04 UTC, merged

2020-11-10 08:03 UTC, IlyaBielov commented on homeworks/ilya.bielov_IlyaBielov/3-async/index.html
> +            <li data-spinner class="spinner">loading...</li>
Добре я зрозумів. Постараюсь у майбутньому більше на це звертати увагу.