3 async
MastersAcademy/frontend-course-2020 pull request #126
Opened 2020-11-06 20:08 UTC by VladimirSkarb

https://vladimirskarb.github.io/frontend-course-2020/homeworks/Vladimir.Karbivnychiy_VladimirSkarb/3-async/
![postRender](https://user-images.githubusercontent.com/44324920/98410002-7ec7f800-207c-11eb-989d-2520c028c088.png)

2020-11-07 17:13 UTC, AlexKuskov requested changes

2020-11-07 17:13 UTC, AlexKuskov commented on homeworks/Vladimir.Karbivnychiy_VladimirSkarb/3-async/app.js
> +                this.postDelete(response, id);
перед тим як відправляти запит на видалення, потрібно тимчасово приховати пост з ДОМ.

2020-11-07 17:13 UTC, AlexKuskov commented on homeworks/Vladimir.Karbivnychiy_VladimirSkarb/3-async/app.js
> +            onePost.classList.add('disabled');
ну і як продовження до коментарію вище, знову робити пост видимим тут

2020-11-07 17:13 UTC, AlexKuskov commented on homeworks/Vladimir.Karbivnychiy_VladimirSkarb/3-async/app.js
> +                fetch(`${this.url}?`)
сортування набагато швидше і менш затратно для бека, краще виконувати локально

2020-11-07 17:13 UTC, AlexKuskov commented on homeworks/Vladimir.Karbivnychiy_VladimirSkarb/3-async/index.html
> +        <input type="text" data-inputText class="input" placeholder="Please, write text">
data-inputText краще перейменувати на data-input-text, для узгодженості стилю в документі

2020-11-07 17:18 UTC, VladimirSkarb commented on homeworks/Vladimir.Karbivnychiy_VladimirSkarb/3-async/app.js
> +                fetch(`${this.url}?`)
Переделать,  чтоб было локально?

2020-11-07 18:26 UTC, AlexKuskov commented on homeworks/Vladimir.Karbivnychiy_VladimirSkarb/3-async/app.js
> +                fetch(`${this.url}?`)
Так

2020-11-08 10:29 UTC, AlexKuskov approved these changes

2020-11-08 10:29 UTC, merged