3 async
MastersAcademy/frontend-course-2020 pull request #127
Opened 2020-11-06 23:43 UTC by RostyslavHavuka

![photo_2020-11-07_01-42-40](https://user-images.githubusercontent.com/70710636/98424504-8f876680-209a-11eb-92ba-cb608215bb92.jpg)

2020-11-07 18:57 UTC, powerbot15 requested changes

2020-11-07 18:57 UTC, powerbot15 commented on .vscode/launch.json
> +}
Это как тут оказалось? Надо ж смотреть что ты коммитишь? Удали этот файл из гита и настрой, чтобы vscode не добавлял файлы в гит автоматически

2020-11-07 18:57 UTC, powerbot15 commented on homeworks/rostyslav.havuka_RostyslavHavuka/3-async/main.js
> +    renderPosts(store);
Стор у тебя объявлен через let, а объявление функций браузер выносит на самый верх, то есть в рантайме функция получется объявлена раньше, чем стор. Передавай стор в функцию как параметр везде где используется

2020-11-09 11:18 UTC, RostyslavHavuka commented on .vscode/launch.json
> +}
Я поцікавився, погуглив і розібрався перед тим як коміти цей файл, мені він здається корисним в репозиторієві коли розробка ведеться в команді і кожному члену команди не потрібно заново витрачати час на конфігурування як запустити відладку в проекті, особливо якщо вона специфічна. Або ще якісь інші корисні файли - налаштування які стосуються відладки - розробки проекту у VS Code. на відміну від WebStorm наприклад який складає в свою папку свої кеші та інші мало корисні в репозиторієві файли для розробників. До того ж це зручно коли повертаєшся з часом до свойого репо, а конфіги запуску - відладки уже є і запускаються в 1 клік 🙂 
Навіть на https://stackoverflow.com/questions/32964920/should-i-commit-the-vscode-folder-to-source-control немає однозначного рішення стосовно ігнорування цих файлів, мені здається потрібно робити так, щоб це було зручно для себе і команди.
Що ви думаєте стосовно цього?

2020-11-09 13:06 UTC, powerbot15 commented on .vscode/launch.json
> +}
Нет, даже в пределах одной команды люди могут юзать разные IDE, и мне например, использующему WebStorm, конфиг для vscode совершенно ни к чему. Удаляй

2020-11-09 15:26 UTC, RostyslavHavuka commented on .vscode/launch.json
> +}
Вибачаюся, я спочатку не помітив, що .vscode знагодиться в рутовій директорії всіх проектів, а не конкретно в моїй папці

2020-11-11 06:46 UTC, RostyslavHavuka commented on homeworks/rostyslav.havuka_RostyslavHavuka/3-async/main.js
> +    renderPosts(store);
Маю запитання що до вашої рекомендації: перенести виклики store який є глобальною змінною в аргументи функцій. Суть зрозумів, ідея подобається. Мені це вдалося скрізь окрім addEventListener() як її передати в цьому випадкові? Складно уявити це синтаксично.
І питання №2. На скільки дієва порада із перенесенням store в аргументи якщо функції починають своє виконання після івенту 'DOMContentLoaded' ? Тобто коли все необхідне для виконання є завантаженим і готовим до запуску

2020-11-11 09:09 UTC, powerbot15 approved these changes

2020-11-11 09:09 UTC, powerbot15 commented on homeworks/rostyslav.havuka_RostyslavHavuka/3-async/main.js
> +    renderPosts(store);
Для addEventListener надо просто юзать прокси функцию, то есть ты добавляешь другую функцию, которая будет обработчиком, а в ней уже вызываешь ту, которую надо и передаешь параметр. По второму вопросу - линтер не читает твой код и не разбирается какие логические связи ты туда заложил. У него есть набор правил которым он тупо следует и нам приходится с этим жить)) Вобщем времени уже почти не осталось, я надеюсь ты понял что я хотел сказать)) Замердживаю пулл-риквест

2020-11-11 09:10 UTC, merged