3 async
MastersAcademy/frontend-course-2020 pull request #129
Opened 2020-11-07 08:41 UTC by AntowkaGor

![Снимок экрана от 2020-11-07 10-28-49](https://user-images.githubusercontent.com/37908673/98436463-347a6180-20e4-11eb-9444-59372316d5a5.png)

https://antowkagor.github.io/frontend-course-2020/homeworks/Anton.Goryshchenko_AntowkaGor/3-async/

2020-11-08 17:55 UTC, MZabolotnev requested changes

2020-11-08 17:55 UTC, MZabolotnev commented on homeworks/Anton.Goryshchenko_AntowkaGor/3-async/script.js
> +    const button = document.createElement('button');
Зачем эта кнопка? Если это заготовка для задания со звездочкой - то доделай или удали 👍

2020-11-08 18:05 UTC, AntowkaGor commented on homeworks/Anton.Goryshchenko_AntowkaGor/3-async/script.js
> +    const button = document.createElement('button');
Хотел доделать но не успеваю, удалить так удалить. Ок

2020-11-08 18:07 UTC, MZabolotnev commented on homeworks/Anton.Goryshchenko_AntowkaGor/3-async/script.js
> +    const button = document.createElement('button');
Время до дедлайна еще есть - занимайся если есть силы и желание) Остальное все ок

2020-11-09 16:36 UTC, MZabolotnev approved these changes

2020-11-09 16:36 UTC, merged