3 async
MastersAcademy/frontend-course-2020 pull request #134
Opened 2020-11-07 16:12 UTC by LigthWarrior

![Снимок экрана от 2020-11-07 15-55-59](https://user-images.githubusercontent.com/58568950/98446207-91960780-2124-11eb-841a-cb340850ebf2.png)
https://ligthwarrior.github.io/frontend-course-2020/homeworks/andrii.stoliarov_lightwarrior/3-async/index.html

2020-11-08 13:52 UTC, AlexKuskov commented
виправ будь ласка деякі баги в завданні:
1. Without sorting повинно відсортовувати елементи до початкового стану
![image](https://user-images.githubusercontent.com/24815257/98466757-2c9ce900-21da-11eb-89b5-3802319b460f.png)
2. Коли відбувається сортування, воно не повинно скидувати результати фільтру
![image](https://user-images.githubusercontent.com/24815257/98466780-5f46e180-21da-11eb-849a-d9c5ab28c02c.png)

2020-11-08 18:45 UTC, AlexKuskov requested changes

2020-11-08 18:45 UTC, AlexKuskov commented on homeworks/andrii.stoliarov_lightwarrior/3-async/style.css
> +p {
вішати стилі на теги погана практика, так як це призводить до випадків коли стилі будуть навішуватись на елементи, на які тоб їх не треба застосовувати (у випадку якщо треба розширювати апп, і тобі треба буде добавити ще один, або декілька <p> елементів). Краще використовувати класовий селектор

2020-11-08 18:45 UTC, AlexKuskov commented on homeworks/andrii.stoliarov_lightwarrior/3-async/style.css
> +  font-size: xx-large;
краще використовувати конкретні пікселі. Так як xx-large значення може відрізнятись в різних браузерах

2020-11-08 18:45 UTC, AlexKuskov commented on homeworks/andrii.stoliarov_lightwarrior/3-async/script.js
> +    container.addEventListener('click', (event) => {
навіщо слухати весь контент елемент, і перевіряти чи клік був зроблений на ремув кнопці, якщо можна просто навішати лісенер на саму кнопку видалення

2020-11-08 18:45 UTC, AlexKuskov commented on homeworks/andrii.stoliarov_lightwarrior/3-async/script.js
> +        event.target.closest('.pane').remove();
тут ще треба добавити тимчасове приховування посту.
відправлення запит на виделення елементу
і реакцію на успішний/неуспішний респонс

2020-11-08 18:45 UTC, AlexKuskov commented on homeworks/andrii.stoliarov_lightwarrior/3-async/script.js
> +    document.querySelector('[data-sort]').addEventListener('change', (event) => {
для більшої зручності можна винести document.querySelector('[data-sort]') в змінні вверх, як ти це зробив з контейнером. Те саме можна зробити і з document.querySelector('[data-filter]'), + я бачив що ти цей виклик використовуєш не один раз

2020-11-08 18:45 UTC, AlexKuskov commented on homeworks/andrii.stoliarov_lightwarrior/3-async/script.js
> +        await initPostsArray(json);
замість цієї функції, можна просто написати `postsArray = json;`. А функцію initPostsArray прибрати

2020-11-08 18:45 UTC, AlexKuskov commented on homeworks/andrii.stoliarov_lightwarrior/3-async/script.js
> +        await insertMessage(json);
тут `await` не потрібен. `await` використовуються для того щоб очікувати на зміну стану Promise

2020-11-10 15:16 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/3-async/style.css
> +p {
fixed

2020-11-10 15:16 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/3-async/style.css
> +  font-size: xx-large;
fixed

2020-11-10 15:23 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/3-async/script.js
> +    container.addEventListener('click', (event) => {
Залишив цей пункт без змін, була спроба перевішати лінсер, не вийшло, якщо критично, відпишить, ще поміркую.

2020-11-10 15:24 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/3-async/script.js
> +    document.querySelector('[data-sort]').addEventListener('change', (event) => {
fixed

2020-11-10 15:24 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/3-async/script.js
> +        await initPostsArray(json);
fixed

2020-11-10 15:24 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/3-async/script.js
> +        await insertMessage(json);
fixed

2020-11-10 15:26 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/3-async/script.js
> +        event.target.closest('.pane').remove();
fixed

2020-11-10 17:24 UTC, AlexKuskov commented on homeworks/andrii.stoliarov_lightwarrior/3-async/script.js
> +    container.addEventListener('click', (event) => {
Краще розібратись в цій штуці зараз. Тому що це лісенери, це базові речі і в будь якому випадку на них доведеться натикатись

2020-11-10 17:28 UTC, AlexKuskov requested changes
Все окей, тільки потрібно дорозібратись з тим одним коментом, який я розвезолвив

2020-11-11 10:48 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/3-async/script.js
> +    container.addEventListener('click', (event) => {
fixed

2020-11-11 11:02 UTC, AlexKuskov approved these changes

2020-11-11 11:02 UTC, merged