3 async
MastersAcademy/frontend-course-2020 pull request #138
Opened 2020-11-07 18:45 UTC by Jul-Bon

https://jul-bon.github.io/frontend-course-2020/homeworks/yulija.bon_Jul-Bon/3-async/
Я зробила. а потім зрозуміла, що не зовсім так як треба, бо в мене за кожним разом йде запит на апі. Зараз вже немає сил переробляти, тому відправляю як є. І  останній пункт нереалізований.
Завдання дуже класне, але втома і брак знань і часу бере своє(

2020-11-08 16:22 UTC, TArch64 requested changes

2020-11-08 16:22 UTC, TArch64 commented on homeworks/yulija.bon_Jul-Bon/3-async/script.js
> +    const html = data.map((article) => `<article id="${article.id}">
ід постів краще писати в `data-post` атрибут. бо ід який сладається тільки з числа не є валідним css селектором і `querySelector` буде кидати ексепшин. Да і якщо писати в дата атрибут то так зрозуміліше + можна шукати як пост окремо так і всі заром на сторінці знайти

2020-11-08 16:22 UTC, TArch64 commented on homeworks/yulija.bon_Jul-Bon/3-async/script.js
> +    loader.style.display = 'none';
краще для приховування елеменів використовувати атрибут або класс `hidden`
```css
.hidden { display: none !important }
```
```js
el.classList.toggle('hidden', !isVisible);
el.hidden = !isVisible;
```

2020-11-08 16:22 UTC, TArch64 commented on homeworks/yulija.bon_Jul-Bon/3-async/script.js
> +getDAtaFromApi();
у тебе тут `DAta` в назві написано

2020-11-08 16:22 UTC, TArch64 commented on homeworks/yulija.bon_Jul-Bon/3-async/script.js
> +    if (selectValue === 'increase') {
такі умови краще робити через switch ... case, бо власне він для такого і робився

2020-11-08 16:22 UTC, TArch64 commented on homeworks/yulija.bon_Jul-Bon/3-async/script.js
> +            titleString += `${article.title.toString().toLowerCase().trim()}`;
чому не `const titleString = article.title.toString().toLowerCase().trim()`?

2020-11-08 16:22 UTC, TArch64 commented on homeworks/yulija.bon_Jul-Bon/3-async/script.js
> +    console.log(filterValue);
у тебе тут консоль лог забувся

2020-11-08 16:22 UTC, TArch64 commented on homeworks/yulija.bon_Jul-Bon/3-async/script.js
> +    const articles = await getDAtaFromApi();
якщо не хочеш кожен раз з апішки питати пости, то можна зробити змінну куди при відкритті сторінки записати початковий список постів, а потім його копію, робити сортування, фільтрацію та показувати на сторінці. Але я нічого страшного в хождінні на апі не бачу

2020-11-08 16:22 UTC, TArch64 commented on homeworks/yulija.bon_Jul-Bon/3-async/style.css
> +article {
Не роби будь-ласка стилі на теги, це дуже погана практика

2020-11-08 16:22 UTC, TArch64 commented on homeworks/yulija.bon_Jul-Bon/3-async/style.css
> +article {
У вівторок розкажу всім чому

2020-11-09 20:05 UTC, Jul-Bon commented on homeworks/yulija.bon_Jul-Bon/3-async/script.js
> +    const html = data.map((article) => `<article id="${article.id}">
це виправила, абсолютно згодна, логічно

2020-11-09 20:05 UTC, Jul-Bon commented on homeworks/yulija.bon_Jul-Bon/3-async/script.js
> +    loader.style.display = 'none';
також виправила

2020-11-09 20:06 UTC, Jul-Bon commented on homeworks/yulija.bon_Jul-Bon/3-async/script.js
> +getDAtaFromApi();
опячаточка))) виправила)

2020-11-09 20:06 UTC, Jul-Bon commented on homeworks/yulija.bon_Jul-Bon/3-async/script.js
> +            titleString += `${article.title.toString().toLowerCase().trim()}`;
та хтозна чому не так) виправила

2020-11-09 20:07 UTC, Jul-Bon commented on homeworks/yulija.bon_Jul-Bon/3-async/script.js
> +    console.log(filterValue);
прибрала

2020-11-09 20:07 UTC, Jul-Bon commented on homeworks/yulija.bon_Jul-Bon/3-async/script.js
> +    const articles = await getDAtaFromApi();
отут менебільше цікавить як правильніше і логічніше, як краще це робити покищо нічого не виправляла

2020-11-09 20:08 UTC, Jul-Bon commented on homeworks/yulija.bon_Jul-Bon/3-async/style.css
> +article {
+ то поспіх, сама ж знаю, шо не треба по тегах стилить)

2020-11-09 20:09 UTC, TArch64 approved these changes

2020-11-09 20:31 UTC, merged