3 async
MastersAcademy/frontend-course-2020 pull request #139
Opened 2020-11-07 18:53 UTC by NataliyaKoval

Знаю, що не вистачає сортування і код жахливий. Але роблю pull request, сподіваючись на підказку, що тут можна виправити, окрім як видалити написане й більше не підпускати мене до редактора коду.
![Screenshot from 2020-11-07 20-43-23](https://user-images.githubusercontent.com/69919727/98449283-efcde500-213a-11eb-8f0b-5de856d016a7.png)

2020-11-08 16:59 UTC, powerbot15 requested changes
В целом норм, не надо впадать в отчаяние)) Помимо ниписанного в комментах еще отсутствует сортировка, добавь.

2020-11-08 16:59 UTC, powerbot15 commented on homeworks/nataliia.koval_NataliyaKoval/3-async/index.html
> +    <div class="container" data-container></div>
здесь наверно закрывающий тег не нужен? Ниже есть еще один

2020-11-08 16:59 UTC, powerbot15 commented on homeworks/nataliia.koval_NataliyaKoval/3-async/style.css
> +li {
Не используй имена тегов в качестве селекторов первого уровня, замени на какой-нибудь класс

2020-11-09 07:51 UTC, NataliyaKoval commented on homeworks/nataliia.koval_NataliyaKoval/3-async/index.html
> +    <div class="container" data-container></div>
Так, зайвий. Видалила.

2020-11-09 07:51 UTC, NataliyaKoval commented on homeworks/nataliia.koval_NataliyaKoval/3-async/style.css
> +li {
Виправила.

2020-11-09 07:59 UTC, NataliyaKoval commented
Глобальна проблема - що функції опиняються всередині іншої функції. Не можу зрозуміти, як отримати доступ до завантажених постів поза межами тієї функції, яка їх завантажила (getResponse). Підкажіть, будь ласка.

2020-11-09 13:08 UTC, powerbot15 approved these changes

2020-11-09 13:09 UTC, merged