3-async
MastersAcademy/frontend-course-2020 pull request #148
Opened 2020-11-08 20:51 UTC by Solowey-A

Это новый пул реквест после дедлайна, так как перве сделал не верно.

2020-11-09 14:46 UTC, TArch64 commented
відміни всі зміни у попочці `1-intro`

2020-11-10 09:51 UTC, Solowey-A commented
Сделал изменения согласно замечанию

2020-11-10 09:52 UTC, TArch64 requested changes

2020-11-10 09:52 UTC, TArch64 commented on homeworks/andrii.soloviov_Solowey-A/3-async/css/style.css
> +    url("../../3-async/fonts/name-font1.svg?72113177#name-font1") format("svg");
З цього всього залиш тільки `woff` і докинь `woff2`. Все інше це легасі типи які зараз нікому не потрібні. woff2 вистачає в 95% видапках

https://caniuse.com/mdn-css_at-rules_font-face_woff_2

2020-11-10 09:52 UTC, TArch64 commented on homeworks/andrii.soloviov_Solowey-A/3-async/css/style.css
> +  font-family: "name-font1";
дав внятну назву для фонта

2020-11-10 09:52 UTC, TArch64 commented on homeworks/andrii.soloviov_Solowey-A/3-async/css/style.css
> +    url("../../3-async/fonts/name-font1.woff?72113177") format("woff"),
для чого потрібно відходити на 2 рівня назад?

2020-11-10 09:52 UTC, TArch64 commented on homeworks/andrii.soloviov_Solowey-A/3-async/css/style.css
> +[class^="icon-"]::before, [class*=" icon-"]::before {
*ніколи* не навішуй стилі отак. Стилі мають додаватися тільки через класи і все. Якщо потрібно винести загальні стилі то зроби базовий клас. Потрібно додати щось до базвих стилів в окремому випадку? Зроби модифікатор. Отакі селектори це шлях в нікуди

2020-11-10 09:52 UTC, TArch64 commented on homeworks/andrii.soloviov_Solowey-A/3-async/css/style.css
> +.loader span {
зроби для `span` клас

2020-11-10 09:52 UTC, TArch64 commented on homeworks/andrii.soloviov_Solowey-A/3-async/css/style.css
> +  /*left: 50%;*/
видаляй коментарений код

2020-11-10 09:52 UTC, TArch64 commented on homeworks/andrii.soloviov_Solowey-A/3-async/fonts/name-font1.svg
> +<font id="name-font1" horiz-adv-x="1000" >
прожени іконки через оптимізатор
```sh
svgo --pretty -p 2 ./path/to/file.svg
```

2020-11-10 09:52 UTC, TArch64 commented on homeworks/andrii.soloviov_Solowey-A/3-async/js/index.js
> +const articleTemplate = document.getElementById('article-template').content;
шукай елементи через `data-` атрибути

2020-11-10 09:52 UTC, TArch64 commented on homeworks/andrii.soloviov_Solowey-A/3-async/js/index.js
> +    loader.style.display = 'none';
замість інлайновий стилів використовуй класи або атрибут `hidden`

2020-11-10 09:52 UTC, TArch64 commented on homeworks/andrii.soloviov_Solowey-A/3-async/js/index.js
> +    myArrayListCopy = posts.slice();
1. немає ніякого сенсу інітити пустий масив щоб його одразу переписати
```js
let myArrayListCopy = posts.slice();
```
2. `myArrayListCopy` Назва дуже довга та нічого не говорить. Назви поточний `posts` як `initalPosts` а `myArrayListCopy` назви `posts`

2020-11-10 09:52 UTC, TArch64 commented on homeworks/andrii.soloviov_Solowey-A/3-async/js/index.js
> +        const copyTemplate = document.importNode(articleTemplate, true);
`document.importNode` використовується не для такого. Використай `articleTemplate.cloneNode(true)`

2020-11-10 09:52 UTC, TArch64 commented on homeworks/andrii.soloviov_Solowey-A/3-async/js/index.js
> +const articleTemplate = document.getElementById('article-template').content;
додавай до всіх змінних елементами дому суфікс `El`

2020-11-10 09:52 UTC, TArch64 commented on homeworks/andrii.soloviov_Solowey-A/3-async/js/index.js
> +        if (optionVal === 'az') {
зроби 2 різних функції та передавай першу або другу в залежності того що обере юзер. Коли всі варіанти сортування в одному місці то тяжко в цьому розбиратися

2020-11-10 09:52 UTC, TArch64 commented on homeworks/andrii.soloviov_Solowey-A/3-async/js/index.js
> +                copyTemplate.querySelector('.article-title').textContent = posts[i].title;
чим відрізняються ці 2 іфи і взагалі чому вони тут?

2020-11-10 09:52 UTC, TArch64 commented on homeworks/andrii.soloviov_Solowey-A/3-async/js/index.js
> +        if (select.value ? 'az' : 'za') {
Ти ж знаєш що тут завжди `true`?

2020-11-10 09:52 UTC, TArch64 commented on homeworks/andrii.soloviov_Solowey-A/3-async/js/index.js
> +            if (!searchVal || articleData[i].textContent.toLowerCase().indexOf(searchVal) > -1) {
```js
articles[i].hidden = searchVal && !articleData[i].textContent.toLowerCase().includes(searchVal);
```
Для чого тобі додавати класс `visible` та інлайнові стилі одночасно?  І ти ж знаєш що такого класу в тебе немає?

2020-11-10 10:06 UTC, TArch64 commented on homeworks/andrii.soloviov_Solowey-A/3-async/css/style.css
> +.demo-icon {
цей клас не використовується. Видали всі класи які не використовуються

2020-11-10 21:55 UTC, Solowey-A commented
Повиксил и доделал фильтр с сортировкой.

2020-11-10 21:55 UTC, Solowey-A commented
https://solowey-a.github.io/frontend-course-2020/homeworks/andrii.soloviov_Solowey-A/3-async/

2020-11-11 12:24 UTC, TArch64 approved these changes

2020-11-11 12:31 UTC, TArch64 approved these changes

2020-11-11 12:31 UTC, TArch64 commented on homeworks/andrii.soloviov_Solowey-A/3-async/js/index.js
> +            if (!searchVal || articleDataEl[i].textContent.toLowerCase().indexOf(searchVal) > -1) {
```js
const isVisible = !searchVal || articleDataEl[i].textContent.toLowerCase().includes(searchVal);
articlesEl[i].classList.toggle('hidden', !isVisible)
```

2020-11-11 12:31 UTC, TArch64 commented on homeworks/andrii.soloviov_Solowey-A/3-async/js/index.js
> +        if (a.title < b.title) {
```js
return a.title < b.title ? -1 : 0;
```

2020-11-11 12:31 UTC, TArch64 commented on homeworks/andrii.soloviov_Solowey-A/3-async/js/index.js
> +        } else if (select.value === 'za') {
такі штуки краще робити через switch ... case. Ця конструктція власне для цього і була задумана

2020-11-11 12:31 UTC, TArch64 commented on homeworks/andrii.soloviov_Solowey-A/3-async/js/index.js
> +        search();
такі штуки краще слухати через `input` івент бо він реагує тільки на зміну значення в інпуті

2020-11-11 12:31 UTC, TArch64 commented on homeworks/andrii.soloviov_Solowey-A/3-async/js/index.js
> +async function getResponse() {
`getResponse` респонс чого? Що станеться якщо я викличу цю функцію?

2020-11-11 12:31 UTC, merged