Ели сделал, успел?
MastersAcademy/frontend-course-2020 pull request #151
Opened 2020-11-10 18:01 UTC by AntonRyabchun

2020-11-10 19:11 UTC, AntonRyabchun commented
Проверте пожалуйста

2020-11-10 20:30 UTC, AntonRyabchun commented
fixed erro

2020-11-10 20:53 UTC, AlexKuskov commented
Looks like not all
![image](https://user-images.githubusercontent.com/24815257/98732219-86064300-23a7-11eb-8546-7301df92fecd.png)

2020-11-11 10:17 UTC, AlexKuskov commented
Також не вистачає ссилки на гітхаб пейджс

2020-11-11 20:05 UTC, AntonRyabchun commented
https://antonryabchun.github.io/frontend-course-2020/homeworks/Anton.Ryabchun_AntonRyabchun/3-async/index.html

2020-11-12 14:18 UTC, AlexKuskov requested changes
1. змінених файлів занадто багато. Потрібно прибрати зайві
2. треба добавити Default опшн для сортування

2020-11-12 14:33 UTC, AntonRyabchun commented
добавил default, конкретнее удалить. коммити?

2020-11-12 14:44 UTC, AntonRyabchun reviewed
deleted unnecessary files

2020-11-12 17:46 UTC, AlexKuskov commented
Домашка списана. Закриваю реквест

2020-11-12 17:46 UTC, closed without merging