Anton Nemesh, Homework #4 Modules - ADDED Time block
MastersAcademy/frontend-course-2020 pull request #157
Opened 2020-11-12 10:13 UTC by AntonNemesh

https://antonnemesh.github.io/frontend-course-2020/homeworks/anton.nemesh_AntonNemesh/4-modules/
![image](https://user-images.githubusercontent.com/10253504/98926638-3e370700-24e0-11eb-892a-a7633a3084f5.png)

2020-11-12 12:33 UTC, powerbot15 requested changes

2020-11-12 12:33 UTC, powerbot15 commented on homeworks/anton.nemesh_AntonNemesh/4-modules/js/time.js
> +}
Этого метода не должно быть тут, в задании на звездочку сказано добавить два метода для прибавления и вычитания часов и соответственно используя их реализовать решение. Ну и работает оно не правильно здесь. Если у нас будет 18:00, то выведется 25:00 для Токио, или при 01:00 будет 0-6:00 для Нью Йорка

2020-11-12 14:44 UTC, AntonNemesh commented on homeworks/anton.nemesh_AntonNemesh/4-modules/js/time.js
> +}
Прошу прощение, невнимательно прочитал описание задания со звездочкой. 
Спасибо за реакцию! 
Уже исправил.

2020-11-13 17:00 UTC, powerbot15 approved these changes

2020-11-13 17:01 UTC, merged