4 - modules
MastersAcademy/frontend-course-2020 pull request #160
Opened 2020-11-12 13:39 UTC by Anton-Mosquito

https://anton-mosquito.github.io/frontend-course-2020/homeworks/anton.komarnitskyi_Anton-Mosquito/4-modules/
![Снимок экрана от 2020-11-12 14-22-06](https://user-images.githubusercontent.com/69711709/98946968-43ef1580-24fd-11eb-97f2-e5997804f883.png)

2020-11-12 13:40 UTC, Anton-Mosquito commented
Тут у меня назрел такой вопрос! Если я допустим заюзаю вебпак и настрою. Есть возможность что бы вы конфиг проверили? или как-то потом по ходу учебы мы все равно с ним столкнемся?

2020-11-12 15:07 UTC, Anton-Mosquito commented
найден баг, можете даже не смотреть. Думаю над его решением

2020-11-12 15:41 UTC, Anton-Mosquito commented
Пофиксил! Готово!

2020-11-14 09:41 UTC, AlexKuskov commented on homeworks/anton.komarnitskyi_Anton-Mosquito/4-modules/script/index.js
> +                if (this.checkInput()) {
замість того, щоб обгортати код в кожному кейсі в if (this.checkInput()), можна написати один
`if (!this.checkInput()) return;` перед `switch (options.text) {`

2020-11-14 09:41 UTC, AlexKuskov commented on homeworks/anton.komarnitskyi_Anton-Mosquito/4-modules/script/index.js
> +        if (this.checkInput()) {
`if (!this.checkInput()) return;` можна вставити один раз тут
![image](https://user-images.githubusercontent.com/24815257/99144306-71f36780-266d-11eb-9f6c-4a773ed8cef5.png)

2020-11-14 09:41 UTC, AlexKuskov commented on homeworks/anton.komarnitskyi_Anton-Mosquito/4-modules/script/index.js
> +            }
в випадках, коли багато іфів, краще заміняти їх switch - case, або if/else

2020-11-14 09:41 UTC, AlexKuskov commented on homeworks/anton.komarnitskyi_Anton-Mosquito/4-modules/script/time.js
> +    return result;
тут замість 
```
let result = null;

    if (checkMonth.getDate() === 31) result = true;
    else result = false;

    return result;
```

2020-11-14 10:07 UTC, AlexKuskov requested changes
також є невелика бага - Shortest week in month повертає неправильне значення. (у випадку з скріном, результат повинен бути "1")
![image](https://user-images.githubusercontent.com/24815257/99144820-c26cc400-2671-11eb-8e99-135dda2f6815.png)

2020-11-14 10:07 UTC, AlexKuskov commented on homeworks/anton.komarnitskyi_Anton-Mosquito/4-modules/styles/styles.css
> +  outline: none;
`outline: none;` для :focus, :active - це погана практика, тому що люди які користуються тільки клавіатурою не можуть бачити який елемент в них в фокусі
більш детально ми це ще будемо проходити в майбутньому, в лекції по доступності (accessibility)

2020-11-14 10:07 UTC, AlexKuskov commented on homeworks/anton.komarnitskyi_Anton-Mosquito/4-modules/styles/styles.css
> +img {
вішати стилі на назви тегів - погана практика. Призводить до того, що майбутні елементи, яким ці стилі зовсім не потрібні, будуть мати їх.
Краще використовувати класові селектори в цьому випадку, і навішувати стилі тіки туди, де тобі потрібно

2020-11-14 11:18 UTC, Anton-Mosquito commented on homeworks/anton.komarnitskyi_Anton-Mosquito/4-modules/script/index.js
> +                if (this.checkInput()) {
fix

2020-11-14 11:18 UTC, Anton-Mosquito commented on homeworks/anton.komarnitskyi_Anton-Mosquito/4-modules/script/index.js
> +        if (this.checkInput()) {
fix

2020-11-14 11:18 UTC, Anton-Mosquito commented on homeworks/anton.komarnitskyi_Anton-Mosquito/4-modules/script/time.js
> +    return result;
fix

2020-11-14 11:19 UTC, Anton-Mosquito commented on homeworks/anton.komarnitskyi_Anton-Mosquito/4-modules/script/index.js
> +            }
fix

2020-11-14 11:21 UTC, Anton-Mosquito commented on homeworks/anton.komarnitskyi_Anton-Mosquito/4-modules/styles/styles.css
> +  border: 0;
я больше не буду использовать обнуление элементов вручную!

2020-11-14 11:21 UTC, Anton-Mosquito commented on homeworks/anton.komarnitskyi_Anton-Mosquito/4-modules/styles/styles.css
> +  outline: none;
fix

2020-11-14 11:26 UTC, Anton-Mosquito commented
Дело в том что я проверил свой календарь на телефоне и календарь компьютере и получается такая картина что бага и нет вовсе. На данную дату в 13 января 2021 года там действительно 3 дня в первую неделю.
![Снимок экрана от 2020-11-14 13-25-29](https://user-images.githubusercontent.com/69711709/99146037-0addaf00-267d-11eb-9e68-971d2ee09a70.png)

2020-11-14 11:49 UTC, Anton-Mosquito commented
я понял в чем ошибка у вас неделя начинается с воскресенья. Такой вариант я неучел

2020-11-14 15:01 UTC, AlexKuskov commented
на рахунок бага з "Shortest week in month". Там була проблема з локалізацією. Поверни будь ласка фікси по цій штуці назад, я перевірю в твоїй локалізації і я вмерджу домашку якщо все буде так само ок, як і було

2020-11-14 15:06 UTC, Anton-Mosquito commented
окончательный fix!

2020-11-14 15:14 UTC, AlexKuskov commented
тут повинно бути число 4 а не 6
![image](https://user-images.githubusercontent.com/24815257/99150368-ca8e2900-269c-11eb-8ca4-5ff072eb2b24.png)

2020-11-14 15:15 UTC, AlexKuskov requested changes
тут повинно бути число 4 а не 6. Найменший тиждень в грудні має 4 дня
![image](https://user-images.githubusercontent.com/24815257/99150368-ca8e2900-269c-11eb-8ca4-5ff072eb2b24.png)

2020-11-14 19:51 UTC, Anton-Mosquito commented
fix

2020-11-14 20:33 UTC, AlexKuskov requested changes
в січні в найменшому тижні 3 дня, а не 0
![image](https://user-images.githubusercontent.com/24815257/99156418-6170da80-26c9-11eb-8aff-2616d54eb07c.png)

2020-11-14 21:03 UTC, Anton-Mosquito commented
![Снимок экрана от 2020-11-14 23-02-25](https://user-images.githubusercontent.com/69711709/99156901-86674c80-26cd-11eb-85a8-55a4ecedba50.png)
надеюсь это последнее что я сделал в этом коде

2020-11-15 10:31 UTC, AlexKuskov approved these changes

2020-11-15 10:31 UTC, merged