4-modules
MastersAcademy/frontend-course-2020 pull request #162
Opened 2020-11-12 16:09 UTC by Schweppes-JS

https://schweppes-js.github.io/frontend-course-2020/homeworks/dmytro.shvets_Schweppes-JS/4-modules/

Скрипти чомусь не підгружає.

2020-11-14 13:05 UTC, AlexKuskov requested changes
Схоже ця штука зайва
![image](https://user-images.githubusercontent.com/24815257/99147565-bc371180-268a-11eb-91e2-04863b5a0dbf.png)

2020-11-14 13:05 UTC, AlexKuskov commented on homeworks/dmytro.shvets_Schweppes-JS/4-modules/script.js
> +                default: break;
якщо в дефолті нічого немає, то можна його прибрати

2020-11-14 19:05 UTC, AlexKuskov commented
потрібно переробити програму, щоб вона рахувала тижні з понеділка, а не з неділі
![image](https://user-images.githubusercontent.com/24815257/99155004-f9b49280-26bc-11eb-83ed-6fb8798aac8a.png)
![image](https://user-images.githubusercontent.com/24815257/99155025-13ee7080-26bd-11eb-9f47-d1d4558a5a72.png)

2020-11-14 22:49 UTC, Schweppes-JS commented
> Схоже ця штука зайва
> ![image](https://user-images.githubusercontent.com/24815257/99147565-bc371180-268a-11eb-91e2-04863b5a0dbf.png)

Це пуста папка, я незнаю як її видалити і як вона там взагалі з'явилась. По ідеї вона повинна проігноруватись.

2020-11-14 22:50 UTC, Schweppes-JS commented on homeworks/dmytro.shvets_Schweppes-JS/4-modules/script.js
> +                default: break;
> якщо в дефолті нічого немає, то можна його прибрати

![linter](https://user-images.githubusercontent.com/68691816/99158545-891d6e00-26dc-11eb-84ec-6911bacb04b4.png)

Лінер не пропускає без дефолту.

2020-11-15 10:36 UTC, AlexKuskov requested changes
так як ця папка показується в твоєму репозиторії, вона так само буде показуватись в основному репозиторію, якщо я вмерджу
![image](https://user-images.githubusercontent.com/24815257/99182684-0e396f00-273f-11eb-9071-8b518e1f7646.png)

2020-11-15 10:37 UTC, AlexKuskov commented on homeworks/dmytro.shvets_Schweppes-JS/4-modules/script.js
> +                default: break;
зрозумів. Тоді нехай залишається

2020-11-15 15:37 UTC, closed without merging