4 modules
MastersAcademy/frontend-course-2020 pull request #164
Opened 2020-11-12 20:07 UTC by RostyslavHavuka

![photo_2020-11-12_22-07-21](https://user-images.githubusercontent.com/70710636/98990699-7ae01e00-2533-11eb-822a-d1a7ce9dcc9a.jpg)

2020-11-12 20:11 UTC, RostyslavHavuka commented
https://rostyslavhavuka.github.io/frontend-course-2020/homeworks/rostyslav.havuka_RostyslavHavuka/4-modules/

2020-11-14 14:13 UTC, AlexKuskov requested changes

2020-11-14 14:13 UTC, AlexKuskov commented on homeworks/rostyslav.havuka_RostyslavHavuka/4-modules/time.js
> +    weeks[6] = [];
такий спосіб додавання елементів в масив крайнє неефективний. що, якби елементів було не 6, а 100? Також індекси в масивів починаються з 0 а не з 1.
Кращий варіант буде присвоювати пустий масив всередині фор:
```
for (let i = 0; i <= daysInMonth; i++) {
        weeks[i] = [];
```
в циклі я об'явив `let i = 0;` тому що елементи масиву повинні починатись з 0 (як я зазначив вище)

2020-11-14 14:15 UTC, AlexKuskov commented
Також є деякі баги:
1. в лютому показується неправильна кількість повних тижнів
2. неправильно показується кількість днів в найкоротшому тижні
![image](https://user-images.githubusercontent.com/24815257/99149063-7717dd00-2694-11eb-953c-942193affe01.png)

2020-11-14 15:19 UTC, RostyslavHavuka commented on homeworks/rostyslav.havuka_RostyslavHavuka/4-modules/time.js
> +    weeks[6] = [];
Дякую, досить цікаве рішення !)

2020-11-14 21:31 UTC, AlexKuskov requested changes

2020-11-14 21:31 UTC, AlexKuskov commented on homeworks/rostyslav.havuka_RostyslavHavuka/4-modules/main.js
> +        default:
`default`: і `break` теж тут не потрібний

2020-11-14 21:31 UTC, AlexKuskov commented on homeworks/rostyslav.havuka_RostyslavHavuka/4-modules/index.html
> +        <input class="inputDate" id="inputDate" type="date" value="2020-11-11">
тут потрібен відступ

2020-11-14 21:31 UTC, AlexKuskov commented on homeworks/rostyslav.havuka_RostyslavHavuka/4-modules/index.html
> +            <span class="span" id="showIsLong"></span></div>
`</div>` потрібно перенести на новий рядок, тому що коли він тут, то трохи збиває, де закінчується `<div class="button2">`

2020-11-14 21:31 UTC, AlexKuskov commented on homeworks/rostyslav.havuka_RostyslavHavuka/4-modules/main.css
> +.button1 { grid-area: button1; }
по цьому селектору можна подумати, що він навішаний на кнопку. Насправді ж він навішаний на секцію яка охоплює окрему частину getMonth, getFullWeeks... Я пропоную їх назвати типу `get-month`, `get-full-weeks`...

2020-11-15 10:27 UTC, AlexKuskov requested changes

2020-11-15 10:27 UTC, AlexKuskov commented on homeworks/rostyslav.havuka_RostyslavHavuka/4-modules/main.css
> +.getMonth { grid-area: getMonth; }
селектори повинні бути в кебаб кейсі

2020-11-15 15:34 UTC, merged