4 modules
MastersAcademy/frontend-course-2020 pull request #171
Opened 2020-11-13 13:27 UTC by NataliyaKoval

https://nataliyakoval.github.io/frontend-course-2020/homeworks/nataliia.koval_NataliyaKoval/4-modules/

2020-11-14 18:07 UTC, MZabolotnev commented
![image](https://user-images.githubusercontent.com/25617217/99153967-e1407a00-26b4-11eb-9524-c13813c486fc.png)
В сентябре последняя неделя -  с 3 днями

2020-11-14 18:16 UTC, MZabolotnev requested changes

2020-11-14 18:16 UTC, MZabolotnev commented on homeworks/nataliia.koval_NataliyaKoval/4-modules/module.js
> +    // eslint-disable-next-line no-restricted-syntax
Зачем тут пропускать правило линтера? Есть более подходящие способы итерации по массиву - forEach к примеру

2020-11-14 22:15 UTC, NataliyaKoval commented on homeworks/nataliia.koval_NataliyaKoval/4-modules/module.js
> +    // eslint-disable-next-line no-restricted-syntax
Змінила на forEach. Не певна, чи правильно.

2020-11-15 16:08 UTC, MZabolotnev approved these changes

2020-11-15 16:09 UTC, merged