4-modules
MastersAcademy/frontend-course-2020 pull request #172
Opened 2020-11-13 14:08 UTC by batteryfree

2020-11-14 10:13 UTC, MZabolotnev requested changes
На твоем скриншоте уже видно что возвращается неверный результат) Вот что должно быть
![image](https://user-images.githubusercontent.com/25617217/99144925-d9f87c80-2672-11eb-8331-be933f1fe354.png)

2020-11-14 13:02 UTC, batteryfree commented
Исправил.
По поводу пятниц если я правил понял описание функции, то вывести все пятницы месяца  начиная с даты...

2020-11-14 18:00 UTC, MZabolotnev commented
> Исправил.
> По поводу пятниц если я правил понял описание функции, то вывести все пятницы месяца начиная с даты...

Нет, всех

2020-11-14 18:01 UTC, MZabolotnev requested changes
Нужно выводить все пятницы месяца

2020-11-15 16:08 UTC, MZabolotnev approved these changes

2020-11-16 07:17 UTC, merged