homework number 4
MastersAcademy/frontend-course-2020 pull request #178
Opened 2020-11-14 17:21 UTC by Anastasia0101

https://anastasia0101.github.io/frontend-course-2020/

2020-11-14 19:23 UTC, MZabolotnev requested changes

2020-11-14 19:23 UTC, MZabolotnev commented on homeworks/anastasia.storozhenko_Anastasia0101/4-modules/time.js
> +    let result;
Можно укоротить, `return result === 31`

2020-11-14 19:43 UTC, MZabolotnev approved these changes

2020-11-14 19:43 UTC, merged

2020-11-16 20:49 UTC, Anastasia0101 commented on homeworks/anastasia.storozhenko_Anastasia0101/4-modules/time.js
> +    let result;
В завданні потрібно повернути true або false, тому в мене так. Не зрозуміла, що саме можна заміти цим?