4 modules
MastersAcademy/frontend-course-2020 pull request #181
Opened 2020-11-14 20:02 UTC by LigthWarrior

![Снимок экрана от 2020-11-14 21-53-09](https://user-images.githubusercontent.com/58568950/99155789-e0631480-26c3-11eb-9582-c772c90ce09b.png)
https://ligthwarrior.github.io/frontend-course-2020/homeworks/andrii.stoliarov_lightwarrior/4-modules/index.html

2020-11-14 20:31 UTC, LigthWarrior commented
Під час перевірки eslint повідомляе про помилку Unexpected use of file extension "js" for "./time.js", коли ії виправляю, прибираючи з імя .js, помилка зникає, але туді модуль не імпортується і застосунок не працює.

2020-11-15 11:38 UTC, powerbot15 requested changes
Чтобы с импортом не ругалось, стяни апдейты из главного репозитория в ветку мастер, а потом смердж ее в эту (4-modules)

2020-11-15 11:38 UTC, powerbot15 commented on homeworks/andrii.stoliarov_lightwarrior/4-modules/script.js
> +                time = subtractHours(currentHour, 5);
Проверь таймзоны, в Лондоне точно должно быть -2, в Нью-Йорке -7, а в Токио не уверен, но проверь тоже

2020-11-15 11:38 UTC, powerbot15 commented on homeworks/andrii.stoliarov_lightwarrior/4-modules/index.html
> +        <form class="form">
По клику на кнопки происходит сабмит формы и логика не отрабатывает, добавь всем кнопкам type="button"

2020-11-15 11:38 UTC, powerbot15 commented on homeworks/andrii.stoliarov_lightwarrior/4-modules/time.js
> +    const currentHours = date - 2 - hours;
А зачем-тут -2? Мы добавляем и вычитаем из времени нашей таймзоны

2020-11-15 15:21 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/4-modules/script.js
> +                time = subtractHours(currentHour, 5);
fixed

2020-11-15 15:22 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/4-modules/index.html
> +        <form class="form">
fixed

2020-11-15 15:22 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/4-modules/time.js
> +    const currentHours = date - 2 - hours;
fixed

2020-11-15 15:44 UTC, powerbot15 approved these changes

2020-11-15 15:47 UTC, merged