4 modules (updated homeWork with extra task)
MastersAcademy/frontend-course-2020 pull request #192
Opened 2020-11-18 20:06 UTC by andrey241991

https://andrey241991.github.io/frontend-course-2020/homeworks/andrey.kushch_andrey241991/4-modules/

2020-11-19 10:12 UTC, TArch64 commented
@andrey241991 Дедалйн пройшов, я трохи заглянув туди але пару комментів можу кинути. Якщо хочеш то можу тобі сюди відписати по коментах та замержити, але відмітку в докі змінювати вже не буду

2020-11-19 22:29 UTC, andrey241991 commented
@TArch64  Да отлично, спасибо, отметка в доке не принципиально, пара коментов это то что нужно)

2020-11-22 19:52 UTC, TArch64 requested changes

2020-11-22 19:52 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/4-modules/index.js
> +    'new-york': 'America/New_York',
Можна ключ в селекті назвати `newYork` тоді в js можна буде по людськи стучатися до цього поля

2020-11-22 19:52 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/4-modules/index.js
> +    /*eslint-disable */
не відключай esint якщо в цьому немає реальної необхідності

2020-11-22 19:52 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/4-modules/index.js
> +    /*eslint-disable */
А якщо вона все ж таки є то пиши нам про це

2020-11-22 19:52 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/4-modules/time.js
> +    return firstDay === 0 ? 7 : firstDay;
`firstDay === 0 ? 7 : firstDay;` Для чого робиця оця умова?

2020-12-12 12:35 UTC, TArch64 commented
Дуже довго висить без ніякої активності

2020-12-12 12:35 UTC, closed without merging