5 rxjs
MastersAcademy/frontend-course-2020 pull request #200
Opened 2020-11-19 22:32 UTC by VladimirSkarb

https://vladimirskarb.github.io/frontend-course-2020/homeworks/Vladimir.Karbivnychiy_VladimirSkarb/5-rxjs/
![rxjs](https://user-images.githubusercontent.com/44324920/99732254-daa46f00-2ac7-11eb-802b-8161d8f7f2dd.png)

2020-11-20 13:02 UTC, DrSmile444 requested changes

2020-11-20 13:02 UTC, DrSmile444 commented on homeworks/Vladimir.Karbivnychiy_VladimirSkarb/5-rxjs/index.html
> +    <header class="header" data-header>
Headers disappear without any animation. "**Має обов'язково бути анімація ховання\показу хедера**"
Please, add animation for each header

You can read about this here: https://www.w3schools.com/css/css3_transitions.asp

2020-11-20 13:26 UTC, Vladmaked commented on homeworks/Vladimir.Karbivnychiy_VladimirSkarb/5-rxjs/index.html
> +    <header class="header" data-header>
Так є ж анімація.

2020-11-20 13:27 UTC, Vladmaked commented on homeworks/Vladimir.Karbivnychiy_VladimirSkarb/5-rxjs/index.html
> +    <header class="header" data-header>
.header {
  position: fixed;
  display: flex;
  justify-content: space-between;
  align-items: center;
  width: calc(50% - 40px);
  height: 80px;
  padding: 0 20px;
  color: #C6CFCA;
  background-color: #333;
  box-shadow: 0 4px 20px rgba(0, 0, 0, .4);
  **transition: all .3s;**
}

+ 
.hidden {
  opacity: 0;
  visibility: hidden;
  height: 0;
}

.visible {
  opacity: 1;
  visibility: visible;
}

Власне так ми плавно показуємо і ховаємо хедер. Хіба ні?

2020-11-20 14:33 UTC, DrSmile444 requested changes

2020-11-20 14:33 UTC, DrSmile444 commented on homeworks/Vladimir.Karbivnychiy_VladimirSkarb/5-rxjs/index.html
> +    <header class="header" data-header>
There's no animation between **"Get an amazing discount BUY NOW"** and **"Logo BUY NOW"**. In the example that Taras has provided, your old **"Get an amazing discount BUY NOW"** header should hide, and **"Logo BUY NOW"** header should appear.

You can find an example of how it should work here at 0:20 - 0:30
https://www.dropbox.com/s/5t29uz3yvkqox3a/advanced-task.mov?dl=0

I suggest you create each header separately and then just hide/show needed 😄

2020-11-20 17:13 UTC, DrSmile444 requested changes

2020-11-20 17:13 UTC, DrSmile444 commented on homeworks/Vladimir.Karbivnychiy_VladimirSkarb/5-rxjs/app.js
> +    filter(([num1, num2]) => (num1 - num2) > 50 || (num2 - num1) > 50),
Choose better names for the variables. (previousHeight, currentHeight)
Use Math.abs to avoid several checks

2020-11-21 10:10 UTC, DrSmile444 approved these changes

2020-11-21 10:11 UTC, merged