RxJs header animation
MastersAcademy/frontend-course-2020 pull request #202
Opened 2020-11-20 12:13 UTC by BohdanKasian

![image](https://user-images.githubusercontent.com/29584285/99798914-7d95d100-2b3a-11eb-93da-4dab1699198c.png)
https://bohdankasian.github.io/frontend-course-2020/homeworks/bohdan.kasian_BohdanKasian/5-rxjs/index.html

2020-11-20 16:57 UTC, MZabolotnev requested changes
Поставь небольшое время задержки при проверке значения скролла - сейчас я не спеша при непрерывном скролле могу скроллить до низа - хедер не спрячется

2020-11-22 19:02 UTC, BohdanKasian commented
блин, не знаю, вроде задержку поставил, но все равно если медленно скролить не спрячется(
нужна подсказка. не понимаю чтото ничего

2020-11-22 20:30 UTC, MZabolotnev commented
Не стесняйся ставить больше задержку просто - при 600 все работает лучше. Домашку засчитываю

2020-11-22 20:32 UTC, MZabolotnev approved these changes

2020-11-22 20:32 UTC, merged