5 rxjs
MastersAcademy/frontend-course-2020 pull request #204
Opened 2020-11-20 14:11 UTC by LigthWarrior

![Снимок экрана от 2020-11-20 15-47-09](https://user-images.githubusercontent.com/58568950/99809271-b6d63d00-2b4a-11eb-99f0-4bb4f262bc7f.png)
https://ligthwarrior.github.io/frontend-course-2020/homeworks/andrii.stoliarov_lightwarrior/5-rxjs

2020-11-20 15:46 UTC, TArch64 requested changes

2020-11-20 15:46 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/5-rxjs/script.js
> +    debounceTime(50),
В такі моменти потрібно використовувати `throttleTime` і думаю що 50ms маловато. Дай хоча б 100-150. Коли в тебе є такий хедер на сторінці то юзер має отримувати візуальний результат як можна раніше, а в тебе виходить що уже після того як юзер закінче скролити

2020-11-20 15:46 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/5-rxjs/script.js
> +    filter((pxArr) => pxArr[1] - pxArr[0] >= 50),
Для чого тобі 2 стріма робити? ти не можеш тут дивитися чи був скролл вверх або вниз та по цьому булеан полі тогглити класс (див `classList.toggle(className, isActive)`)

2020-11-20 15:46 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/5-rxjs/script.js
> +    filter((pxArr) => pxArr[1] - pxArr[0] >= 50),
щоб відфільровувати випадок коли юзер проскролив трошки без прив'язки до напрямку скрола можна використовувати функцію `Math.abs`

2020-11-20 15:46 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/5-rxjs/script.js
> +    filter((pxArr) => pxArr[1] - pxArr[0] >= 50),
`(pxArr) => pxArr[1] - pxArr[0] >= 50` роби в таких випадках деструкторизацію масива. Індекси в коді є доволі не зрозумілими
```js
([previousPosition, currentPosition]) => currentPosition - previousPosition >= 50
```

2020-11-20 15:46 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/5-rxjs/script.js
> +    map(() => wallNode.scrollTop),
щоб в мапові не стучатися в глобальний контекст можна робити отак `map(event => event.target.scrollTop)`

2020-11-20 15:46 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/5-rxjs/style.css
> +.container .wall .hidden-pane-header {
для чого потрібна додаткова специфічність з ` .container .wall`?

2020-11-20 15:46 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/5-rxjs/style.css
> +  transition: opacity .3s linear 0s;
Воно не таке ж як і в `.pane-header`

2020-11-20 21:50 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/5-rxjs/script.js
> +    debounceTime(50),
fixed

2020-11-20 21:50 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/5-rxjs/script.js
> +    filter((pxArr) => pxArr[1] - pxArr[0] >= 50),
fixed

2020-11-20 21:50 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/5-rxjs/script.js
> +    filter((pxArr) => pxArr[1] - pxArr[0] >= 50),
fixed

2020-11-20 21:50 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/5-rxjs/script.js
> +    filter((pxArr) => pxArr[1] - pxArr[0] >= 50),
fixed

2020-11-20 21:50 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/5-rxjs/script.js
> +    map(() => wallNode.scrollTop),
fixed

2020-11-20 21:50 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/5-rxjs/style.css
> +.container .wall .hidden-pane-header {
fixed

2020-11-20 21:50 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/5-rxjs/style.css
> +  transition: opacity .3s linear 0s;
fixed

2020-11-21 19:06 UTC, TArch64 approved these changes

2020-11-21 19:07 UTC, merged