commit
MastersAcademy/frontend-course-2020 pull request #205
Opened 2020-11-20 21:46 UTC by MatviienkoOleh

2020-11-20 22:49 UTC, MatviienkoOleh commented
https://matviienkooleh.github.io/frontend-course-2020/homeworks/oleh.matviienko_MatviienkoOleh/5-rxjs/

2020-11-21 11:52 UTC, powerbot15 requested changes

2020-11-21 11:52 UTC, powerbot15 commented on homeworks/oleh.matviienko_MatviienkoOleh/5-rxjs/style.css
> +  transition: all .4s ease-in-out;
Транзишн надо перенести в .header. Когда ты убираешь этот класс, транзишн тоже убирается и скрытие хедера происходит мгновенно, без анимации

2020-11-21 11:52 UTC, powerbot15 commented on homeworks/oleh.matviienko_MatviienkoOleh/5-rxjs/main.js
> +            if ((a - b) >= 50) direction = 'Up';
Оператор сравнения имеет меньший приоритет, чем арифметические операторы - скобки не нужны. (и в нижнем ифе тоже)

2020-11-21 11:52 UTC, powerbot15 commented on homeworks/oleh.matviienko_MatviienkoOleh/5-rxjs/main.js
> +    }
Слышал что нибудь про мета-программирование? Вместо этого свича можно сделать так:
```
header.classList[event === 'Up' ? 'add' : 'remove']('header-show');
```
Не уверен правда пропустит ли линтер)) Попробуй

2020-11-22 12:08 UTC, powerbot15 approved these changes

2020-11-22 12:10 UTC, merged