5 rxjs
MastersAcademy/frontend-course-2020 pull request #206
Opened 2020-11-20 22:58 UTC by spavel-gh

[**GitHub Pages link**](https://spavel-gh.github.io/frontend-course-2020/homeworks/sokurenko.pavel_spavel_gh/5-rxjs/index.html)

![image](https://user-images.githubusercontent.com/71533482/99857724-8d420380-2b94-11eb-9e71-a74d6eb69698.png)

2020-11-20 23:01 UTC, spavel-gh commented
todo:

- дописать алгоритм отслеживания 50px
- привести код к чистоте и порядку

2020-11-21 05:25 UTC, spavel-gh commented on homeworks/sokurenko.pavel_spavel_gh/5-rxjs/index.js
> +scrollStream.subscribe((/* event */) => {
У меня вопрос. После реализации всей логики, для `scrollStream.subscribe` ничего не осталось. Все целевые действия выполняются по ходу обработки и взаимодействия с потоком. 

В таком случае я не вижу смысла искусственно модифицировать поток, чтобы доставить какие-то сигналы в `scrollStream.subscribe` на выполнение целевых функций.

Из этого следует вопрос, могу ли я оставить такую реализацию, или нужно работу с внешними функциями 
любой ценой вытеснить в `scrollStream.subscribe` ?

2020-11-21 05:29 UTC, spavel-gh commented
Если успею до дедлайна, постараюсь сдать задание со звёздочкой.

2020-11-21 10:09 UTC, powerbot15 requested changes

2020-11-21 10:09 UTC, powerbot15 commented on homeworks/sokurenko.pavel_spavel_gh/5-rxjs/index.js
> +    }
Как и ниже, тут надо заменить на `if`. Экшены должны быть названы по другому, ты ж не закрываешь-открываешь хедер, а показываешь или прячешь. Закрыть или открыть можно модальное окно, или окно браузера, но никак не в этом кейсе. И название функции вызывает сомнения. `работа заголовка` - так его прочитает разработчик. Какая работа, почему заголовок работает?

2020-11-21 10:09 UTC, powerbot15 commented on homeworks/sokurenko.pavel_spavel_gh/5-rxjs/index.js
> +let watch = false;
Не надо перемешивать объявления функций и переменных. Сначала все объявления функций, потом все объявления переменных, потом логика которая использует переменные и вызывает функции.

2020-11-21 10:09 UTC, powerbot15 commented on homeworks/sokurenko.pavel_spavel_gh/5-rxjs/index.js
> +            if (wayPointer === 'down') {
Используй тут && и ниже тоже: 
```
if (wayPointer === 'down' && yNew > yPointer) {
```

2020-11-21 10:09 UTC, powerbot15 commented on homeworks/sokurenko.pavel_spavel_gh/5-rxjs/index.js
> +        }
Здесь чтобы не делать вложенности лучше сделать
```
if (!watch) {
    return;
}
```
А ниже уже иф с вычислениями

2020-11-21 11:58 UTC, powerbot15 commented on homeworks/sokurenko.pavel_spavel_gh/5-rxjs/index.js
> +let watch = false;
Вернее даже сначала все переменные, потом функции, потом логика

2020-11-21 12:00 UTC, powerbot15 commented on homeworks/sokurenko.pavel_spavel_gh/5-rxjs/index.js
> +let watch = false;
Или может быть даже вариант когда все переменные, потом логика, потом функции.

Вобщем главное чтобы не было мешанины, когда идет объявление переменной, потом функции, потом опять переменные. Все должно быть сгруппировано

2020-11-21 13:39 UTC, spavel-gh commented on homeworks/sokurenko.pavel_spavel_gh/5-rxjs/index.js
> +    }
Эта функция управляет статусом отслеживания 50px-логики. Функция инициализирует отслеживание или прекращает его. Можно было бы обойтись без нее, но я решил выделить эту логику в функцию так как код используется повторно в разных местах. Согласен, более подходящее имя ей будет `makeTrackingStatus`.

2020-11-21 13:49 UTC, spavel-gh commented on homeworks/sokurenko.pavel_spavel_gh/5-rxjs/index.js
> +    }
Переменную `action` оставлю. В в контексте нового заголовка она должна стать более понятной и уместной. Скрыть-показать - это же действия, которые выполняет функция. Остальное перепишу

2020-11-21 13:56 UTC, spavel-gh commented on homeworks/sokurenko.pavel_spavel_gh/5-rxjs/index.js
> +let watch = false;
> Или может быть даже вариант когда все переменные, потом логика, потом функции.

Если логка использует функцию, функция должна быть определена выше логики.
Я Вас понял.

2020-11-21 14:08 UTC, spavel-gh commented on homeworks/sokurenko.pavel_spavel_gh/5-rxjs/index.js
> +            if (wayPointer === 'down') {
Да, я тоже сперва так думал упростить сделать. 
Но в выражение
`(wayPointer === 'down' && yNew > yPointer)` всегда выполняет каждый раз 3 сравнения, а
`if (watch === true) { if (wayPointer === 'down') {` 
в половине случаев выполняет 2 сравнения, в другой половине случаев 1 сравнение, что на 50% производительнее.

Мне показалось, что стараться всегда писать производительный код - это хорошо. К тому же не в ущерб читаемости кода. Теперь вот я не знаю)

2020-11-21 14:16 UTC, powerbot15 commented on homeworks/sokurenko.pavel_spavel_gh/5-rxjs/index.js
> +            if (wayPointer === 'down') {
Логический оператор это не сравнение, там не происходит приведение типов одного к другому. А вот ветвление с точки зрения производительности немного сложнее выполнить чем логическую операцию.  В целом оба варианта по производительности сработают примерно одинаково, а вот размер кода в случае с вложенными ифами увеличится.

2020-11-21 14:31 UTC, spavel-gh commented on homeworks/sokurenko.pavel_spavel_gh/5-rxjs/index.js
> +            if (wayPointer === 'down') {
В таком случае как композиционно правильнее будет:

> `            if (wayPointer === 'down' && yNew > yPointer) {`
> `                setTrackingStatus(false);`
> `            }`
> `            if (wayPointer === 'up' && yNew < yPointer) {`
> `                setTrackingStatus(false);`
> `            }`

или

> `            if (wayPointer === 'down' && yNew > yPointer) setTrackingStatus(false);`
> `            if (wayPointer === 'up' && yNew < yPointer) setTrackingStatus(false);`

2020-11-21 14:41 UTC, spavel-gh commented on homeworks/sokurenko.pavel_spavel_gh/5-rxjs/index.js
> +});
> Ты ж тут подписался, зачем еще раз?

Нет, так не получится. Главный pipe работает через `throttleTime(80)`, мы можем вернуться в `yNow = 0`, а логика об этом даже не узнает, поскольку протротлила этот момент 🙈. В таком случае хеадер не появится, когда мы вернёмся наверх страницы. Этот баг очень часто давал о себе знать.
По этому я делаю вторую подписку , которая закрывает эту дыру `throttleTime(80)`

2020-11-21 16:50 UTC, powerbot15 commented on homeworks/sokurenko.pavel_spavel_gh/5-rxjs/index.js
> +            if (wayPointer === 'down') {
А тут без разницы, даже если в одну строку, то тут она короткая и читается достаточно легко

2020-11-21 17:54 UTC, spavel-gh commented
[**GitHub Pages link**](https://spavel-gh.github.io/frontend-course-2020/homeworks/sokurenko.pavel_spavel_gh/5-rxjs/index.html)

![image](https://user-images.githubusercontent.com/71533482/99883963-43f4c100-2c33-11eb-809d-2e483ffa39c1.png)

2020-11-21 18:06 UTC, powerbot15 commented on homeworks/sokurenko.pavel_spavel_gh/5-rxjs/index.js
> +});
Да это потому, что ты очень усложнил решение. Я потратил пол-часа, посмотрел как работает rxjs (я его не использую) и переделал код из твоего js. Не надо там двойных подписок, и много чего еще. Вот примерное решение

```javascript
const headerNode = document.querySelector('[data-heaader-content]');
const scrollNode = document.querySelector('[data-scroll]');

const { fromEvent } = window.rxjs;
const {
  map, throttleTime
} = window.rxjs.operators;

const scroll = fromEvent(scrollNode, 'scroll');
let zeroPointCoord = 0;
let totalDelta = 0;
let lastAction = 'show';

function headerHideShow(action) {
  headerNode.style.top = '0px';
  if (action === 'hide') {
    headerNode.style.top = `${(headerNode.offsetHeight + 2) * -1}px`;
  }
}

scroll.pipe(
  map(() => scrollNode.scrollTop),
  throttleTime(50),
  map((scrollCoord) => {
    totalDelta += scrollCoord - zeroPointCoord;
    zeroPointCoord = scrollCoord;
    if (totalDelta < -50) {
      totalDelta = 0;
      if (lastAction === 'hide') {
        lastAction = 'show';
        return 'show';
      }
    }
    if (totalDelta > 50) {
      totalDelta = 0;
      if (lastAction === 'show') {
        lastAction = 'hide';
        return 'hide';
      }
    }
  })
).subscribe((action) => {
  if(action) {
    headerHideShow(action);
  }
});
```

2020-11-21 18:32 UTC, powerbot15 requested changes
Работает неправильно, при скролле вверх видно две области сразу https://www.awesomescreenshot.com/video/1808470
Посмотри внимательно видео из задания. Когда юзер находится ниже кнопки - при скролле дальше вниз показывается текст про скидку, когда скроллится вверх - текст из хедера

2020-11-21 22:06 UTC, spavel-gh reviewed
Окей. Я предполагал, что header должен остаться. Но если идём чётко по тз, я изсправил всё по ТЗ.

2020-11-22 12:02 UTC, powerbot15 approved these changes
О, вот теперь норм

2020-11-22 12:03 UTC, merged