5-rxjs
MastersAcademy/frontend-course-2020 pull request #209
Opened 2020-11-21 11:30 UTC by MykYarovenko36

https://mykyarovenko36.github.io/frontend-course-2020/homeworks/mykola.yarovenko_MykYarovenko36/5-rxjs/

2020-11-21 12:09 UTC, AlexKuskov requested changes
В роботі є деякі баги які потрібно виправити:
1. При скролі вниз, хедер не зникає
https://monosnap.com/direct/RSg6DZuZvwRad5RMoEBjp0e26OXjld
2. Бувають моменти, коли після Buy Now, юзер опускається вниз і показується Лого, і піднімається вверх показується amazing discount
https://monosnap.com/direct/ZxMaEWYhpNO8iwMloJNTVgFyqxppjN

2020-11-21 17:08 UTC, AlexKuskov requested changes

2020-11-21 17:08 UTC, AlexKuskov commented on homeworks/mykola.yarovenko_MykYarovenko36/5-rxjs/index.html
> +            <p><button class='wpapper-sale_btn sale_btn' id='#'>BUY NOW</button></p>
навіщо добавляти айді, якщо він не використовується?

2020-11-21 17:08 UTC, AlexKuskov commented on homeworks/mykola.yarovenko_MykYarovenko36/5-rxjs/index.js
> +            headerEl.classList.toggle('active', false);
тут краще заюзати `headerEl.classList.remove('active');`

2020-11-21 17:08 UTC, AlexKuskov commented on homeworks/mykola.yarovenko_MykYarovenko36/5-rxjs/index.js
> +            headerEl.classList.toggle('active', true);
а тут `headerEl.classList.add('active');`

2020-11-21 21:40 UTC, MykYarovenko36 commented on homeworks/mykola.yarovenko_MykYarovenko36/5-rxjs/index.css
> +  background-color: rgb(255, 255, 255);
Проводил эксперименты с цветами фона и забыл убрать)))

2020-11-22 09:06 UTC, AlexKuskov approved these changes

2020-11-22 09:08 UTC, merged