complete minimum task
MastersAcademy/frontend-course-2020 pull request #211
Opened 2020-11-21 12:23 UTC by Anna1o1Vrana

https://anna1o1vrana.github.io/frontend-course-2020/homeworks/anna.vrana_Anna1o1Vrana/5-rxjs
![Screenshot from 2020-11-21 14-23-11](https://user-images.githubusercontent.com/72143197/99877199-23157700-2c05-11eb-852e-861df9bf259b.png)
/

2020-11-21 13:34 UTC, TArch64 commented
лінка на гітхаб пейджес не працює

2020-11-21 13:41 UTC, TArch64 requested changes

2020-11-21 13:41 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/5-rxjs/scripts/main.js
> + * map +
видали цей коммент. він тут не потрібен

2020-11-21 13:41 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/5-rxjs/scripts/main.js
> +const header = document.querySelector('[data-header]');
додай `El` до всіх змінних з елементами дому

2020-11-21 13:41 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/5-rxjs/scripts/main.js
> +    filter(([a, b]) => Math.abs(a - b) >= 50),
Не використовуй назви з однієї літери. Ми не в школі та не в універі. Назви мають давати розуміння що саме лежить в змінній або що саме робить ця конкретна функція. Якщо боїшся довгих назв, то незрозуміла назва зі скороченнями більш страшно ніж довга але зрозуміла

2020-11-21 13:41 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/5-rxjs/scripts/main.js
> +    distinctUntilChanged(),
як часто у тебе може повторюватися значення `window.pageYOffset` підряд. Тут точно потрібен оператор `distinctUntilChanged`?

2020-11-21 13:41 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/5-rxjs/scripts/main.js
> +    .subscribe((active) => header.classList.toggle('sticky', active));
Зараз у тебе якщо в хедера є клас `sticky` то може прийти булеан щоб він ще раз додався. це точно необхідно чи можна зробити якимось оператором так щоб такого не було?

2020-11-21 13:41 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/5-rxjs/style.css
> +  transition: 3s;
думаю що 3 секунди це багато для анімації. і додавай транзішин на конкретні властивості css. Анімувати все є поганою практикою

2020-11-22 06:01 UTC, Anna1o1Vrana commented
> лінка на гітхаб пейджес не працює

Fixed

2020-11-22 06:03 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/5-rxjs/scripts/main.js
> + * map +
Done)

2020-11-22 06:03 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/5-rxjs/scripts/main.js
> +const header = document.querySelector('[data-header]');
Done)

2020-11-22 06:08 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/5-rxjs/scripts/main.js
> +    filter(([a, b]) => Math.abs(a - b) >= 50),
Changed name of variables)

2020-11-22 06:13 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/5-rxjs/scripts/main.js
> +    distinctUntilChanged(),
distinctUntilChanged - was recommended as needed. It removes duplicates in the array. There can't be them in our array, so I don't think he's doing anything here? 
I delete operator 'distinctUntilChanged'

2020-11-22 19:35 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/5-rxjs/scripts/main.js
> +    distinctUntilChanged(),
@Anna1o1Vrana Often `distinctUntilChanged` is good stuff but not in this case. There are no many cases when you have duplicated `pageYOffset` so it's just running a lot of js to do nothing

2020-11-22 19:38 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/5-rxjs/scripts/main.js
> +    distinctUntilChanged(),
Adding `distinctUntilChanged` makes sense  when you have a lot of duplicated events that following one by one

2020-11-22 19:41 UTC, TArch64 requested changes

2020-11-22 19:41 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/5-rxjs/scripts/main.js
> +    // eslint-disable-next-line max-len
Не відключай eslint без реальної на то потреба, а в даному випадку її тут немає

2020-11-22 19:41 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/5-rxjs/scripts/main.js
> +)
я говорив про те що коли ти скролиш в одному напрямку то сюди тобі буде приходити одне і те ж значення булеан і ти можеш додати в кінець `distinctUntilChanged` щоб фільтрувати це і не робити зайву роботу в домі

2020-11-22 19:41 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/5-rxjs/style.css
> +  transition: 3s;
тут так і залишилося 3 секунди і анімування всього на світі

2020-11-22 19:43 UTC, TArch64 requested changes
3 секунди для анімції це багато. і анімуватися має ховання\показання хедера на сторінці а не просто викривоюватися щось. Я говорив про те що хедер має не просто раптово зникнути зі сторінки, а має бути якась плавна анімація цього

2020-11-23 02:07 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/5-rxjs/style.css
> +  transition: 3s;
Виправила

2020-11-23 02:08 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/5-rxjs/scripts/main.js
> +    // eslint-disable-next-line max-len
Не пускає з помилками лінтера :( Змінила назви

2020-11-23 02:09 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/5-rxjs/scripts/main.js
> +)
повернула distinctUntilChanged() в кінець пайпу

2020-11-23 02:11 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/5-rxjs/scripts/main.js
> +    .subscribe((active) => header.classList.toggle('sticky', active));
Перенесла sticky до основних властивостей хедера і змінила анімацію

2020-11-24 12:23 UTC, TArch64 approved these changes

2020-11-24 12:23 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/5-rxjs/style.css
> +  transition: top .5s ease-in-out;
я б ще зменшив анімацію до .3s, бо ця теж трохи довгою здається. Ну і Доволі часто роблять на вихід швидшу анімацію ніж на вхід

2020-11-24 12:23 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/5-rxjs/style.css
> +  transition: top .5s ease-in-out;
Але поки і так норм

2020-11-24 12:26 UTC, merged