Add rxjs task
MastersAcademy/frontend-course-2020 pull request #214
Opened 2020-11-21 16:53 UTC by andrey241991

https://andrey241991.github.io/frontend-course-2020/homeworks/andrey.kushch_andrey241991/5-rxjs/

2020-11-21 19:10 UTC, TArch64 requested changes

2020-11-21 19:10 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/5-rxjs/index.js
> +    currentScrollPossition = window.scrollY;
Використовуй оператори замість оцих сабскрайб та зберігання глобальну змінну

2020-11-21 19:10 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/5-rxjs/index.js
> +    if (scrollPossition - currentSP <= -50) {
однією з умов завдання було те щоб в `subscribe` була тільки логіка додаання чи віднімання класів. Все інше включаючи `scrollPossition - currentSP <= -50` має бути в операторах

2020-11-21 19:16 UTC, TArch64 requested changes
перероби з використанням операторів

2020-11-25 17:49 UTC, andrey241991 commented on homeworks/andrey.kushch_andrey241991/5-rxjs/index.js
> +    if (scrollPossition - currentSP <= -50) {
Переделал, вроде как надо

2020-11-27 10:55 UTC, TArch64 commented
Ти запушив це за 20 хвилин до дедлайну і там ще не одну ітерацію правок потрібно буде робити. Тому закриваю

2020-11-27 10:55 UTC, closed without merging

2020-11-27 12:30 UTC, andrey241991 commented
Так за  20 минут до дедлайна, а не после, и я запушил задание со звездочкой. Обычное задание я еще в обед запушил.

2020-11-27 12:36 UTC, TArch64 commented
> @TArch64 Так за 20 минут до дедлайна, а не после, и я запушил задание со звездочкой. Обычное задание я днем запушил.

Я тобі залишив коммент практично в той де день що ти відкрив пулл реквест. Потім ніяких змін не було до ночі середи. Да, там, можливо, завдання із зірочкою. Але там я можу ще не один коммент залишити. По правилах у нас дедлайн правок на кінець середи. Якби там було пару правок і все то я б на щось закиив очі, трохи підправили і все, але тут не той випадок

2020-11-27 12:59 UTC, andrey241991 commented
@TArch64  Я б и рад был кинуть раньше, но у меня не было возможности. Ну вот я запушил таск с основным заданием в 19.44. Это вроде как не прям ночь, просто я так понимал полночь среды это дедлайн для меня, а по факту выходит если я даже кину заранее, а преподаватель будет смотреть в среду и решит что там много правок нужно, то домашку просто не засчитают?
![2020-11-27_14h45_14](https://user-images.githubusercontent.com/26023192/100451230-b811e780-30bf-11eb-8f7c-d2d899425d70.png)