6 typescript
MastersAcademy/frontend-course-2020 pull request #220
Opened 2020-11-26 18:35 UTC by VolodymyrUstilkin

github pages:
https://volodymyrustilkin.github.io/frontend-course-2020/homeworks/volodymyr.ustilkin_VolodymyrUstilkin/6-typescript/dist/

2020-11-30 22:20 UTC, smithua commented on homeworks/volodymyr.ustilkin_VolodymyrUstilkin/6-typescript/src/index.css
> +button {
никогда не используй обращения к тегам, уже 100 раз проговаривали )

2020-11-30 22:20 UTC, smithua commented on homeworks/volodymyr.ustilkin_VolodymyrUstilkin/6-typescript/src/index.css
> +section, div {
никогда не используй обращения к тегам, уже 100 раз проговаривали )

2020-11-30 22:20 UTC, smithua commented on homeworks/volodymyr.ustilkin_VolodymyrUstilkin/6-typescript/src/index.css
> +body {
никогда не используй обращения к тегам, уже 100 раз проговаривали )

2020-11-30 22:21 UTC, smithua commented on homeworks/volodymyr.ustilkin_VolodymyrUstilkin/6-typescript/src/index.css
> +  font-size: xx-large;
Всегда лучше указывать в какой то из величин, чем браузерное значение типа (xx-large)

2020-11-30 22:27 UTC, smithua commented on homeworks/volodymyr.ustilkin_VolodymyrUstilkin/6-typescript/src/index.html
> +    <div class="cube-score" style="background-color: #F00" data-cube></div>
А зачем задавать цвет в теге? почему в CSS не прописать?

2020-11-30 22:36 UTC, smithua requested changes
Хей, нужно немного подфиксить коменты )

И сейчас когда нажимаешь на любую клавишу, игра стартует, но время не уменьшается.
Т.е сейчас игру можно стартонуть только по клику на кнопку **Start**, а хотелось бы что бы при нажатии на любую кнопку игра начиналась.

2020-12-01 14:51 UTC, VolodymyrUstilkin commented on homeworks/volodymyr.ustilkin_VolodymyrUstilkin/6-typescript/src/index.css
> +button {
fixed

2020-12-01 14:51 UTC, VolodymyrUstilkin commented on homeworks/volodymyr.ustilkin_VolodymyrUstilkin/6-typescript/src/index.css
> +section, div {
fixed )

2020-12-01 14:52 UTC, VolodymyrUstilkin commented on homeworks/volodymyr.ustilkin_VolodymyrUstilkin/6-typescript/src/index.css
> +body {
fixed )

2020-12-01 14:52 UTC, VolodymyrUstilkin commented on homeworks/volodymyr.ustilkin_VolodymyrUstilkin/6-typescript/src/index.css
> +  font-size: xx-large;
fixed

2020-12-01 14:59 UTC, VolodymyrUstilkin commented on homeworks/volodymyr.ustilkin_VolodymyrUstilkin/6-typescript/src/index.html
> +    <div class="cube-score" style="background-color: #F00" data-cube></div>
Думал что неправильно ради одного унакального параметра елемента создавать отдельный css класс )
Fixed

2020-12-01 16:45 UTC, smithua commented on homeworks/volodymyr.ustilkin_VolodymyrUstilkin/6-typescript/src/index.css
> +.body-class {
есть исключения по названию, обычно теги `html, body` - называют просто `.html, .body`

2020-12-01 16:47 UTC, smithua approved these changes
Все, теперь окей. Хорошая работа!

2020-12-01 16:48 UTC, merged

2020-12-01 16:54 UTC, VolodymyrUstilkin commented on homeworks/volodymyr.ustilkin_VolodymyrUstilkin/6-typescript/src/index.css
> +.body-class {
спасибо, буду знать )
fixed