6-typescript
MastersAcademy/frontend-course-2020 pull request #223
Opened 2020-11-27 09:44 UTC by Evapavl

githubPage:
 https://evapavl.github.io/frontend-course-2020/homeworks/eva.pavlenko_Evapavl/6-typescript/

2020-11-27 10:59 UTC, TArch64 commented on homeworks/eva.pavlenko_Evapavl/6-typescript/src/index.ts
> +const keyElement = document.querySelector('[data-key]') as HTMLDivElement;
`querySelector` приймає дженерік тип. Використання `as` не дуже добре впливає на типізацію, тому це краще уникати `document.querySelector<HTMLDivElement>('[data-key]')`

2020-11-27 18:44 UTC, AlexKuskov requested changes

2020-11-27 18:44 UTC, AlexKuskov commented on homeworks/eva.pavlenko_Evapavl/6-typescript/src/index.ts
> +const elemBar = document.querySelector<HTMLDivElement>('[data-my-bar]');
щоб легше читалось пиши назву а потім тип - barElement
Взагалі можна підписати навіть barEl, і так зрозуміло що це елемент, але буде менше тексту

2020-11-27 18:44 UTC, AlexKuskov commented on homeworks/eva.pavlenko_Evapavl/6-typescript/src/index.ts
> +    }
якщо функція пуста то пиши скобки так - {}

2020-11-27 19:53 UTC, AlexKuskov requested changes

2020-11-27 19:53 UTC, AlexKuskov commented on homeworks/eva.pavlenko_Evapavl/6-typescript/src/index.ts
> +        private scoreElement: HTMLHeadingElement,
тут теж треба виправити HTMLHeadingElement

2020-11-27 19:53 UTC, AlexKuskov commented on homeworks/eva.pavlenko_Evapavl/6-typescript/src/index.ts
> +            if (scoreCurr == 200 || scoreCurr == 0) {
завжди використовуй === замість ==. Цей метод більш точний

2020-11-27 19:53 UTC, AlexKuskov commented on homeworks/eva.pavlenko_Evapavl/6-typescript/src/index.ts
> +            let scoreCurr = Number.parseInt(this.scoreElement.innerHTML);
ти використовуєш тут let, при тому що це значення не переписується

2020-11-27 19:53 UTC, AlexKuskov commented on homeworks/eva.pavlenko_Evapavl/6-typescript/src/index.ts
> +            let scoreCurr = Number.parseInt(this.scoreElement.innerHTML);
переглянь будь ласка, всі місця де ти писала let, і позаміняй їх, якщо потрібно

2020-11-27 19:53 UTC, AlexKuskov commented on homeworks/eva.pavlenko_Evapavl/6-typescript/src/index.ts
> +            this.scoreElement.innerHTML = '200';
навіщо переписувати результат? якщо в юзера 205 балів, то нехай стільки і буде. Те саме стосується і програша

2020-11-27 19:53 UTC, AlexKuskov commented on homeworks/eva.pavlenko_Evapavl/6-typescript/src/index.ts
> +            this.cubeElement.style.height = '100px';
старайся не повторяти ідентичний код

2020-11-27 19:53 UTC, AlexKuskov commented on homeworks/eva.pavlenko_Evapavl/6-typescript/src/index.ts
> +        if (score < 0) {
я б виніс код двох if в 1, який покривав би умови виграшу і програшу.
`this.resultElement.innerHTML = 'Проигрыш';` - а це я б вирішив за допомогою тернарки яка перевіряла, якщо `score < 0` тру - то програш, якщо ні то виграш.

2020-11-27 19:53 UTC, AlexKuskov commented on homeworks/eva.pavlenko_Evapavl/6-typescript/src/index.ts
> +        }
тут теж варто подумати, як зробити так, щоб код не повторювався

2020-11-27 20:37 UTC, Evapavl commented on homeworks/eva.pavlenko_Evapavl/6-typescript/src/index.ts
> +            this.cubeElement.style.height = '100px';
таким образом я виповнюю залежність 
if (scoreCurr == 200 || scoreCurr == 0) {
                clearInterval(id);
            }
щоб зачистити шнтервал

2020-11-27 21:20 UTC, AlexKuskov commented on homeworks/eva.pavlenko_Evapavl/6-typescript/src/index.ts
> +            this.cubeElement.style.height = '100px';
такі залежності це не дуже круто
`let scoreCurr = Number.parseInt(this.scoreElement.innerHTML);`
якщо тобі треба scoreCurr значення, то закинь його в глобальну змінну, і діставай і змінюй її де тобі потрібно. Мінять текстовку елементу для того щоб помінять внутрішню змінну - додає більше залежностей а потім і головного болю при дебагінгу

2020-11-27 21:26 UTC, AlexKuskov commented on homeworks/eva.pavlenko_Evapavl/6-typescript/src/index.ts
> +        if (score < 0) {
так виглядає лаконічніше
`if (score < 0) this.stopGame('Проигрыш', '0');`

2020-11-28 08:07 UTC, AlexKuskov approved these changes

2020-11-28 08:14 UTC, merged