6 typescript
MastersAcademy/frontend-course-2020 pull request #227
Opened 2020-11-28 04:31 UTC by MatviienkoOleh

2020-11-28 04:35 UTC, MatviienkoOleh commented
не могу понять , пишет ошибка при обращении к методу через this

2020-11-28 04:37 UTC, MatviienkoOleh commented
https://matviienkooleh.github.io/frontend-course-2020/homeworks/oleh.matviienko_MatviienkoOleh/6-typescript/dist/

2020-11-28 07:30 UTC, powerbot15 requested changes

2020-11-28 07:30 UTC, powerbot15 commented on homeworks/oleh.matviienko_MatviienkoOleh/6-typescript/src/index.ts
> +        this.interval = setInterval(this.setChar, 2000);
`setInterval` вызывает метод с глобальным контекстом, надо туда передать контекст класса
```
  this.interval = setInterval(this.setChar.bind(this), 2000);
```

2020-11-28 07:30 UTC, powerbot15 commented on homeworks/oleh.matviienko_MatviienkoOleh/6-typescript/src/index.ts
> +        document.addEventListener('keydown', this.compareSymbols);
Тут то же самое, неверный контекст

2020-11-28 07:30 UTC, powerbot15 commented on homeworks/oleh.matviienko_MatviienkoOleh/6-typescript/src/index.ts
> +          clearInterval(this.interval);
Этот кусок повторяется и в следующем ифе, сделай метод `showEndMessage(message: string, class: string)` и вынеси туда эту логику

2020-11-28 07:30 UTC, powerbot15 commented on homeworks/oleh.matviienko_MatviienkoOleh/6-typescript/src/index.ts
> +          }
Этот кусок мне не очень нравится, можно подумать над оптимизацией

2020-11-30 07:06 UTC, powerbot15 requested changes
Есть баг, можно успеть нажать правильно или неправильно клавишу несколько раз для одной и тойже буквы и получить экстра-плюс или экстра-минус. Надо после детекта клавиши сразу переключать на новую и заново считать таймаут

2020-11-30 10:53 UTC, powerbot15 requested changes

2020-11-30 10:53 UTC, powerbot15 commented on homeworks/oleh.matviienko_MatviienkoOleh/6-typescript/src/index.ts
> +    }
Вот тут должна быть проверка(вызов проверки) соответствия введенного и сгенерированного. А потом перезапуск таймаута с новой буквой. У юзера есть две секунды, чтобы нажать на кнопку, но это не значит, что он не нажмет быстрее. А твой алгоритм полюбому ждет две секунды, даже если кнопка уже нажата. Причем в процессе ожидания я могу несколько раз нажать неправильную кнопку, потом правильную и получить плюс))

2020-11-30 12:03 UTC, powerbot15 approved these changes

2020-11-30 12:10 UTC, powerbot15 commented
Риквест замерджился, но гитхаб что-то глюкнул и не отметил это. Закрываю чтобы пофиксить.

2020-11-30 12:10 UTC, closed without merging