typescript
MastersAcademy/frontend-course-2020 pull request #228
Opened 2020-11-28 07:26 UTC by Anton-Mosquito

https://anton-mosquito.github.io/frontend-course-2020/homeworks/anton.komarnitskyi_Anton-Mosquito/6-typescript/dist
![Снимок экрана от 2020-11-28 09-23-31](https://user-images.githubusercontent.com/69711709/100496324-ca416380-315b-11eb-968e-0cb24f8b50fe.png)

2020-11-28 09:50 UTC, MZabolotnev requested changes
Проигрыш и выигрыш никак не выделяются. 
Я могу нажать на кнопку в отведенное время много раз - и выиграть игру за один заход ( начинай новый цикл и клавишу после нажатия юзера ).

2020-11-28 09:50 UTC, MZabolotnev commented on homeworks/anton.komarnitskyi_Anton-Mosquito/6-typescript/src/index.ts
> +        // document.addEventListener("click", (e) => {
Почисть ненужный закомментированый код

2020-11-28 12:45 UTC, powerbot15 commented
@Anton-Mosquito откати изменения корневого `package.json` @MZabolotnev не забудь проконтролировать

2020-11-28 17:46 UTC, MZabolotnev commented
Линтер тоже ругается

2020-12-01 19:15 UTC, MZabolotnev approved these changes

2020-12-01 19:16 UTC, merged