6-typescript
MastersAcademy/frontend-course-2020 pull request #229
Opened 2020-11-28 10:07 UTC by Schweppes-JS

2020-11-28 20:06 UTC, AlexKuskov requested changes
Є деякі зауваження до коду, але саме оформлення гри зроблено класно

2020-11-28 20:06 UTC, AlexKuskov commented on homeworks/dmytro.shvets_Schweppes-JS/6-typescript/src/index.ts
> +        this.cyclProgressAnimation();
орфографічна помилка в `cyclProgressAnimation`

2020-11-28 23:18 UTC, Schweppes-JS commented
Прийшлось в багатьох місцях проставити   !   незнаю чи це нормаль.

2020-11-29 07:25 UTC, AlexKuskov requested changes

2020-11-29 07:25 UTC, AlexKuskov commented on homeworks/dmytro.shvets_Schweppes-JS/6-typescript/dist/style.css
> +    box-sizing: border-box;
цю штуку треба було залишити в * {}

2020-11-29 07:25 UTC, AlexKuskov commented on homeworks/dmytro.shvets_Schweppes-JS/6-typescript/src/index.ts
> +    private timerBottom!: number;
тип number не підходить, використовуй `NodeJS.Timer`
`private timerBottom: NodeJS.Timer;`
так і знаки оклику використовувати не доведеться

2020-11-29 14:00 UTC, AlexKuskov approved these changes

2020-11-29 14:01 UTC, merged