6 typescript
MastersAcademy/frontend-course-2020 pull request #233
Opened 2020-11-28 17:07 UTC by andrey241991

https://andrey241991.github.io/frontend-course-2020/homeworks/andrey.kushch_andrey241991/6-typescript/dist/index.html

2020-11-28 19:23 UTC, TArch64 requested changes

2020-11-28 19:23 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/6-typescript/src/game.ts
> +                if (this.score >= 200) {
розбий це на методи. Замість свіча з true/false використай звичайний if. Результат один і той же, просто світч більш громіздка конструкція. Але тут більше потрібно це розділити на методи бо дуже багато всього намішано

2020-11-28 19:23 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/6-typescript/src/game.ts
> +export default Game;
Використовуй замість дефолтних експортів найменовані. Про це ми на лекції раніше говорили

2020-11-28 19:23 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/6-typescript/src/index.ts
> +    game.start(subscription as Observable<KeyboardEvent>)
назви `subscription` по іншому бо сабскрипція та observable це різні речі. Наприклад `keypress$`

2020-11-28 19:23 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/6-typescript/src/index.ts
> +        map((e) => e),
`map((e) => e)`, нічого не робить. це можна скоротити до
```js
const subscription = fromEvent(document, 'keypress').pipe(throttleTime(1500));
```

2020-11-28 19:23 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/6-typescript/src/style.css
> +select {
Для написання стилів не старайся не використовувати вкладеності та теги. Це крайній випадок. Якщо можна зробити клас для якихось стилів то зроби клас

2020-11-28 19:23 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/6-typescript/src/style.css
> +body {
у тебе стилі дублюються

2020-11-28 19:23 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/6-typescript/webpack.config.js
> +        game: "./src/game.ts",
зазвичай на ентріпоінти розділяють коли у тебе є декілька сторінок і ти хочеш для окремої сторінки зробити свій js файл. У твоєму випадку робити для кожного модуля ентріпоінт це зайве і краще зробити одним
`entry: './src/index.ts'`

2020-11-28 19:23 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/6-typescript/webpack.config.js
> +            "@models": path.resolve(__dirname, "src/models"),
у тебе ці аліаси не використовуються

2020-11-28 19:23 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/6-typescript/webpack.config.js
> +                test: /\.(ttf|woff|woff2|eot)$/,
```js
            {
                test: /\.(png|jpg|svg|gif)$/,
                use: ["file-loader"],
            },
            {
                test: /\.(ttf|woff|woff2|eot)$/,
                use: ["file-loader"],
            },
            {
                test: /\.xml$/,
                use: ["xml-loader"],
            },
```
У тебе немає ніяких файлів для цих лодерів тому вони тобі не потрібні

2020-11-28 19:23 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/6-typescript/webpack.config.js
> +                test: /\.ts(x?)$/,
у тебе немає tsx файлів тому зроби `/\.ts$/`

2020-11-28 19:23 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/6-typescript/src/game.ts
> +        this.clearData();
Для чого ти в методи передаєш `this.interval` та `this.timeoutId`? Це робити не потрібно бо всередині тих методів куди ти їх передаєш вони і так доступні в this

2020-11-28 19:23 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/6-typescript/src/index.ts
> +const subscription = fromEvent(document, 'keypress')
Ти тут використовуєш `rxjs` тільки для того щоб зробити `throttleTime` для keypress. Кожна бібліотека має свою ціну використання і перед тим як використовувати щось потрібно подумати чи дійсно воно тобі потрібно. Якби класною ця бібліотека не була, але все має свою ціну. Якщо тобі потрібно тільки фільтрувати кількість виклитів то просто зроби собі `throttle` хелпер і використовуй його

2020-11-28 19:23 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/6-typescript/src/index.ts
> +        throttleTime(1500),
Можеш пояснити для чого конкретно тут використовується `throttleTime`?

2020-12-01 14:15 UTC, andrey241991 commented on homeworks/andrey.kushch_andrey241991/6-typescript/src/game.ts
> +    private subscriptionId: Subscription = new Subscription;
поправил

2020-12-01 14:15 UTC, andrey241991 commented on homeworks/andrey.kushch_andrey241991/6-typescript/src/index.ts
> +    game.start(subscription as Observable<KeyboardEvent>)
понял

2020-12-01 14:15 UTC, andrey241991 commented on homeworks/andrey.kushch_andrey241991/6-typescript/webpack.config.js
> +                test: /\.(ttf|woff|woff2|eot)$/,
поправил

2020-12-01 14:15 UTC, andrey241991 commented on homeworks/andrey.kushch_andrey241991/6-typescript/src/game.ts
> +        this.clearData();
поправил

2020-12-01 14:18 UTC, andrey241991 commented on homeworks/andrey.kushch_andrey241991/6-typescript/src/index.ts
> +        throttleTime(1500),
Я его заюзал что б нельзя было пару раз подряд нажать кнопку и до того как появятся новые буквы.

2020-12-01 14:41 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/6-typescript/src/index.ts
> +        throttleTime(1500),
@andrey241991 Поняв. Тоді краще заміни тут rxjs на кастомний throttle хелпер. В інтернеті нагуглити їх можна

2020-12-01 14:43 UTC, andrey241991 commented on homeworks/andrey.kushch_andrey241991/6-typescript/src/index.ts
> +const subscription = fromEvent(document, 'keypress')
Я планировал больше его заюзать, я сейчас переписал с использованием RX в силу своих знаний.

2020-12-01 14:44 UTC, andrey241991 commented on homeworks/andrey.kushch_andrey241991/6-typescript/webpack.config.js
> +                test: /\.ts(x?)$/,
Поправил, спасибо

2020-12-01 14:44 UTC, andrey241991 commented on homeworks/andrey.kushch_andrey241991/6-typescript/src/game.ts
> +export default Game;
Поправил, спасибо

2020-12-01 14:44 UTC, andrey241991 commented on homeworks/andrey.kushch_andrey241991/6-typescript/src/game.ts
> +                if (this.score >= 200) {
Переписал

2020-12-01 14:45 UTC, andrey241991 commented on homeworks/andrey.kushch_andrey241991/6-typescript/.gitignore
> +/out-tsc
Ну не уверен, нужно его убрать?

2020-12-01 14:50 UTC, andrey241991 commented on homeworks/andrey.kushch_andrey241991/6-typescript/src/style.css
> +body {
поправил

2020-12-01 15:05 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/6-typescript/.gitignore
> +/out-tsc
@andrey241991 рутового файлу має вистачати

2020-12-01 15:11 UTC, TArch64 approved these changes

2020-12-01 15:11 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/6-typescript/src/game.ts
> +        this.keyElement.classList.add(keyElementStyle);
Замість отакого
```ts
const keyElementStyle = isKeyRight ? 'key-container__key--pass' : 'key-container__key--fail'
this.keyElement.classList.remove('key-container__key--pass', 'key-container__key--fail');
this.keyElement.classList.add(keyElementStyle);
```
Можна робити отак
```ts
this.keyElement.classList.toggle('key-container__key--pass', isKeyRight);
this.keyElement.classList.toggle('key-container__key--fail', !isKeyRight);
```

2020-12-01 15:11 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/6-typescript/src/game.ts
> +            this.keyElement.classList.remove('key-container__key--pass', 'key-container__key--fail');
Так як в тебе ці класи повторюються в декількох місцях то хорошою ідеєю є винести їх в константи

2020-12-01 15:12 UTC, merged

2020-12-01 15:22 UTC, andrey241991 commented on homeworks/andrey.kushch_andrey241991/6-typescript/src/game.ts
> +        this.keyElement.classList.add(keyElementStyle);
Понял, спасибо.

2020-12-01 15:23 UTC, andrey241991 commented on homeworks/andrey.kushch_andrey241991/6-typescript/src/game.ts
> +            this.keyElement.classList.remove('key-container__key--pass', 'key-container__key--fail');
Понял, спасибо.

2020-12-01 15:25 UTC, andrey241991 commented on homeworks/andrey.kushch_andrey241991/6-typescript/.gitignore
> +/out-tsc
Сори не до конца понял, под рутовым ты имеешь ввиду "/dist" ?