6 type script
MastersAcademy/frontend-course-2020 pull request #235
Opened 2020-11-28 18:41 UTC by MykYarovenko36

https://mykyarovenko36.github.io/frontend-course-2020/homeworks/mykola.yarovenko_MykYarovenko36/6-TypeScript/

2020-11-29 07:32 UTC, AlexKuskov requested changes
В роботі є невелика бага, гра не зупиняється, коли юзер досягнув результат 200
![image](https://user-images.githubusercontent.com/24815257/100535855-2c19d000-3225-11eb-9fb7-9cc577a7e486.png)

2020-11-29 11:14 UTC, AlexKuskov commented
для того, щоб розглядати це завдання, як завдання з зірочкою, потрібно доробити один пункт. Всі інші пункти виконані
![image](https://user-images.githubusercontent.com/24815257/100540239-bfaec900-3244-11eb-9b90-b36766c1d877.png)

2020-11-29 13:52 UTC, AlexKuskov requested changes

2020-11-29 13:52 UTC, AlexKuskov commented on homeworks/mykola.yarovenko_MykYarovenko36/6-typescript/index.ts
> +const currentScoreEl = document.querySelector('[data-current-points]') as HTMLParagraphElement;
більш кращим способом для `querySelector` замість `as HTMLParagraphElement`, вважаються дженерики:
`document.querySelector<HTMLParagraphElement>('[data-current-points]')`

2020-11-29 13:52 UTC, AlexKuskov commented on homeworks/mykola.yarovenko_MykYarovenko36/6-typescript/index.ts
> +        this.currentScore.innerText = '' + this.score;
`this.score` запишеться в `this.currentScore.innerText` навіть без переведення в строковий тип

2020-11-29 13:52 UTC, AlexKuskov commented on homeworks/mykola.yarovenko_MykYarovenko36/6-typescript/index.ts
> +        let currentPoints: number = Number(this.currentScore.innerText);
`let` використовується для змінних, які в подальшому будуть переписуватись. Якщо змінна не переписується використовуй `const`. Виправ будь ласка скрізь, де є подібна штука

2020-11-29 13:52 UTC, AlexKuskov commented on homeworks/mykola.yarovenko_MykYarovenko36/6-typescript/index.ts
> +        let currentPoints: number = Number(this.currentScore.innerText);
замість `Number(this.currentScore.innerText)`, цей варіант більш лаконічний:
`+this.currentScore.innerText`

2020-11-29 13:52 UTC, AlexKuskov commented on homeworks/mykola.yarovenko_MykYarovenko36/6-typescript/index.ts
> +                }
замість двох іфів можна замінити таким чином:
`targetEl.innerText === this.gameKey.innerText ? this.plusPoints() : this.minusPoints();`

2020-11-29 14:28 UTC, MykYarovenko36 commented on homeworks/mykola.yarovenko_MykYarovenko36/6-typescript/index.ts
> +        this.currentScore.innerText = '' + this.score;
Пишет что -  Type 'number' is not assignable to type 'string', я изначально пробовал сделать запись без приведения к строке, но другого выбора оно мне просто не оставило.

2020-11-29 21:16 UTC, AlexKuskov commented on homeworks/mykola.yarovenko_MykYarovenko36/6-typescript/index.ts
> +        this.currentScore.innerText = '' + this.score;
okay

2020-11-29 21:20 UTC, AlexKuskov requested changes
https://github.com/MastersAcademy/frontend-course-2020/pull/235#issuecomment-735376802
там зазначено не тільки реагувати на зміни (мінять колір), але і збільшувати і зменшувати квадрат.
А так то все добре, реалізуєш цю штуку і буду мерджити

2020-11-30 10:07 UTC, AlexKuskov approved these changes

2020-11-30 10:17 UTC, merged