8 components templates
MastersAcademy/frontend-course-2020 pull request #243
Opened 2020-12-10 21:14 UTC by oleg20Kovalenko

https://oleg20kovalenko.github.io/frontend-course-2020/homeworks/oleg.kovalenko_oleg20Kovalenko/8-components-templates/dist/components-templates/

2020-12-11 08:11 UTC, powerbot15 requested changes

2020-12-11 08:11 UTC, powerbot15 commented on homeworks/oleg.kovalenko_oleg20Kovalenko/8-components-templates/src/app/app.component.html
> +      </li>
Не работает потому что нету лоадера)) Когда плитка показывается - должен быть включен лоадер, другая картинка, которая показывает загрузку, типа такой 
![image](https://user-images.githubusercontent.com/5908792/101878338-0df28f00-3b98-11eb-92f5-2d340bdb18ff.png)
А сама картинка галереи должна быть спрятана классом со стилем `display: none`. А когда сработает load ивент, просто надо спрятать лоадер, а с картинки убрать скрывающий класс.

2020-12-11 08:11 UTC, powerbot15 commented on homeworks/oleg.kovalenko_oleg20Kovalenko/8-components-templates/src/app/app.component.ts
> +  clickBox(item: any) {
`any` не пойдет, напиши модели для данных

2020-12-11 12:18 UTC, powerbot15 requested changes

2020-12-11 12:18 UTC, powerbot15 commented on homeworks/oleg.kovalenko_oleg20Kovalenko/8-components-templates/src/app/app.component.html
> +        <div class="loader" [class.hidden]="load" (load)="loader()"></div>
Событие load  надо слушать на картинке, и плюс перепутана логика добавления класса хидден. Подумай на каких элементах будет этот класс если переменная load будет тру во время загрузки

2020-12-11 13:45 UTC, powerbot15 requested changes
Обнови билд для гитхаб пейджес и напиши модель(тип данных) для объекта картинки из массива (коммент я оставлял)

2020-12-11 15:38 UTC, oleg20Kovalenko commented
я пишу тип данных ts выдает ошибки

пт, 11 дек. 2020 г. в 15:46, Oleh Kastornov <notifications@github.com>:

> *@powerbot15* requested changes on this pull request.
>
> Обнови билд для гитхаб пейджес и напиши модель(тип данных) для объекта
> картинки из массива (коммент я оставлял)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/MastersAcademy/frontend-course-2020/pull/243#pullrequestreview-550109411>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANF5BWW35HXLB27ELDB56XTSUIPCPANCNFSM4UVTTQHA>
> .
>

2020-12-12 10:16 UTC, powerbot15 commented
> я пишу тип данных ts выдает ошибки
Значит ты что-то неправильно делаешь. Почитай доку по тайпскрипту, как создавать типы данных(интерфейсы) для объектов. https://www.typescriptlang.org/docs/handbook/interfaces.html

2020-12-12 10:18 UTC, powerbot15 requested changes

2020-12-12 10:18 UTC, powerbot15 commented on homeworks/oleg.kovalenko_oleg20Kovalenko/8-components-templates/src/app/app.component.ts
> +  images = images;
У `images` должен быть тип, например `Image[]`

2020-12-12 10:18 UTC, powerbot15 commented on homeworks/oleg.kovalenko_oleg20Kovalenko/8-components-templates/src/app/app.component.ts
> +  clickBox(item: any): void {
Тут должен быть тип, например `item: Image`

2020-12-12 10:18 UTC, powerbot15 commented on homeworks/oleg.kovalenko_oleg20Kovalenko/8-components-templates/src/app/app.component.ts
> +  clickActive(item: any) {
Тут должен быть тип, например `item: Image`

2020-12-12 12:10 UTC, powerbot15 approved these changes

2020-12-12 12:11 UTC, merged