8 components templates
MastersAcademy/frontend-course-2020 pull request #246
Opened 2020-12-11 03:22 UTC by VladimirSkarb

https://vladimirskarb.github.io/frontend-course-2020/homeworks/Vladimir.Karbivnychiy_VladimirSkarb/8-components-templates/pictures-slider/dist/pictures-slider/
![angular](https://user-images.githubusercontent.com/44324920/101857720-cdcbe600-3b70-11eb-8ce7-ad74fe205968.png)

2020-12-11 03:25 UTC, VladimirSkarb commented
Я сделал бесконечную карусель. После последнего фото, идет первое, и наоборот в обратном порядке.

2020-12-12 13:52 UTC, DrSmile444 requested changes

2020-12-12 13:52 UTC, DrSmile444 commented on homeworks/Vladimir.Karbivnychiy_VladimirSkarb/8-components-templates/pictures-slider/src/app/components/image-item/image-item.component.ts
> +  loader: any = true;
Don't use `any` in your code

2020-12-12 13:52 UTC, DrSmile444 commented on homeworks/Vladimir.Karbivnychiy_VladimirSkarb/8-components-templates/pictures-slider/src/app/components/image-gallery/gallery.component.ts
> +  nextEl(): void {
I assume that this method **show** next element. Each function in JS should be named from the verb:
- `showList`
- `hideItem`
- `matchString`
- `replaceAll`

Fix your `nextEl` and `prevEl` names

2020-12-12 13:52 UTC, DrSmile444 commented on homeworks/Vladimir.Karbivnychiy_VladimirSkarb/8-components-templates/pictures-slider/src/app/components/image-item/image-item.component.ts
> +  hiddenLoader(): void {
`hideLoader` sounds better

2020-12-12 13:52 UTC, DrSmile444 commented on homeworks/Vladimir.Karbivnychiy_VladimirSkarb/8-components-templates/pictures-slider/src/app/components/image-item/image-item.component.ts
> +  @Input() item?: DataInterface;
`item` is required, isn't it?

2020-12-12 13:52 UTC, DrSmile444 commented on homeworks/Vladimir.Karbivnychiy_VladimirSkarb/8-components-templates/pictures-slider/src/app/interfaces/dataInterface.ts
> +export interface DataInterface {
1) You don't need to add the `Interface` postfix for each interface you create

2) `Data` name is too abstract. `Image` name would be better and easier to understand

3) Move all your image related interfaces into the one file 

**Applicable to all interfaces**

2020-12-12 20:33 UTC, DrSmile444 approved these changes

2020-12-12 20:33 UTC, DrSmile444 commented on homeworks/Vladimir.Karbivnychiy_VladimirSkarb/8-components-templates/pictures-slider/src/app/interfaces/Image.ts
> +export interface Image {
I didn't mean merge all interfaces into the one)
I mean to just move all interfaces into one file. But this is not blocking

2020-12-12 20:36 UTC, merged