8-components-templates
MastersAcademy/frontend-course-2020 pull request #249
Opened 2020-12-11 12:10 UTC by Anton-Mosquito

https://anton-mosquito.github.io/frontend-course-2020/homeworks/anton.komarnitskyi_Anton-Mosquito/8-components-templates/HW8/dist/HW8/

x-special/nautilus-clipboard
copy
file:///home/anton0886/%D0%98%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%20%D0%BE%D1%82%202020-12-11%2014-09-18.png

2020-12-12 16:21 UTC, MZabolotnev requested changes

2020-12-12 16:21 UTC, MZabolotnev commented on homeworks/anton.komarnitskyi_Anton-Mosquito/8-components-templates/HW8/src/app/gallery/gallery.component.ts
> +    public galleryLoad(): void {
Сейчас ( особенно при не самом быстром интернете) при нажатии на картинку - кнопка next  появляется по центру картинки , после мигрирует на свое место. Не совсем понимаю, зачем ты рулишь стилями в логике,  и какую проблему ты этим решил? Используй ngStyle если это действительно нужно - или используй к примеру flex.

2020-12-12 16:21 UTC, MZabolotnev commented on homeworks/anton.komarnitskyi_Anton-Mosquito/8-components-templates/HW8/src/app/gallery/gallery.component.ts
> +    if(!(event.target instanceof HTMLDivElement)) {
Зачем эта проверка?

2020-12-12 16:21 UTC, MZabolotnev commented on homeworks/anton.komarnitskyi_Anton-Mosquito/8-components-templates/HW8/src/app/gallery/gallery.component.html
> +    [class.hidden]="activePrevArrow"
Тут можно написать сразу условие ( например iterator === 0 и тд ) - что бы не захламлять логику кучей if-else

2020-12-12 16:21 UTC, MZabolotnev commented on homeworks/anton.komarnitskyi_Anton-Mosquito/8-components-templates/HW8/src/app/gallery/gallery.component.ts
> +  public activePrevArrow : boolean = false;
Можно и нужно сделать условие в тимплате - не плодить лишних переменных

2020-12-12 16:21 UTC, MZabolotnev commented on homeworks/anton.komarnitskyi_Anton-Mosquito/8-components-templates/HW8/src/app/gallery/gallery.component.ts
> +      if ( this.iterator === 0) {
Это можно написать в тимплате ( к примеру  [class.hidden]="iterator === 0" ). И в общем - если у тебя куча if-else с кучей вложенных if-else - значит что то идет не так. Поправь это везде

2020-12-12 16:21 UTC, MZabolotnev commented on homeworks/anton.komarnitskyi_Anton-Mosquito/8-components-templates/HW8/src/app/gallery/images-data.ts
> +export class ImagesData {
В чем цель использования класса вместо интерфейса?

2020-12-13 06:40 UTC, Anton-Mosquito commented on homeworks/anton.komarnitskyi_Anton-Mosquito/8-components-templates/HW8/src/app/gallery/gallery.component.ts
> +    public galleryLoad(): void {
ок !

2020-12-13 06:43 UTC, Anton-Mosquito commented on homeworks/anton.komarnitskyi_Anton-Mosquito/8-components-templates/HW8/src/app/gallery/images-data.ts
> +export class ImagesData {
исправил

2020-12-13 07:26 UTC, Anton-Mosquito commented on homeworks/anton.komarnitskyi_Anton-Mosquito/8-components-templates/HW8/src/app/gallery/gallery.component.ts
> +    if(!(event.target instanceof HTMLDivElement)) {
Это гард на то что клик будет произведен по элементу в котором есть дата атрибут. Тоесть клик может быть произведен и по белой области не по картинке. Без него ошибка вылетает
![Снимок экрана от 2020-12-13 09-23-28](https://user-images.githubusercontent.com/69711709/102005903-3956b480-3d25-11eb-86e2-1ccaa8f247b8.png)
!

2020-12-16 12:24 UTC, MZabolotnev requested changes
![image](https://user-images.githubusercontent.com/25617217/102347852-ab3f3000-3fa9-11eb-8caf-7aa8ad08e809.png)
Проблема с кнопкой не пофикшена. Я бы советовал избегать абсолютного позиционирования без крайней необходимости. В данной ситуации ты можешь например убрать position:absolute и добавить margin кнопкам

2020-12-16 20:31 UTC, MZabolotnev approved these changes

2020-12-16 20:31 UTC, merged