8 components templates
MastersAcademy/frontend-course-2020 pull request #252
Opened 2020-12-11 17:46 UTC by LigthWarrior

![Screenshot from 2020-12-11 17-56-16](https://user-images.githubusercontent.com/58568950/101936127-d3fda900-3be8-11eb-97a7-a9bf8e9ee512.png)
https://ligthwarrior.github.io/frontend-course-2020/homeworks/andrii.stoliarov_lightwarrior/8-components-templates/angular-gallery/dist/angular-gallery

2020-12-12 12:54 UTC, TArch64 requested changes
Також у тебе візуально сабнейли імеджів прямокутні, а мають бути квадратні

2020-12-12 12:54 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/8-components-templates/angular-gallery/src/app/app-routing.module.ts
> +  imports: [RouterModule.forRoot(routes)],
Якщо тобі роутинг не потрібен то і не підключай його. Видали цей файл та всі його використання

2020-12-12 12:54 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/8-components-templates/angular-gallery/src/app/app-routing.module.ts
> +  imports: [RouterModule.forRoot(routes)],
Якщо тобі роутинг не потрібен то і не підключай його. Видали цей файл та всі його використання

2020-12-12 12:54 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/8-components-templates/angular-gallery/src/app/app.component.css
> +h1 {
Стилі вішаються тільки на класи. Навіть в ангулярі. Теги нізя

2020-12-12 12:54 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/8-components-templates/angular-gallery/src/app/app.component.html
> +<h1>{{title}}</h1>
```suggestion
<h1>Gallery</h1>
```
Якщо `title` не є динамічним то і робити для нього інтерполяцію не потрібно

2020-12-12 12:54 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/8-components-templates/angular-gallery/src/app/collection-images.ts
> +import { from } from 'rxjs';
для чого тут тобі `import { from } from 'rxjs';`?

2020-12-12 12:54 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/8-components-templates/angular-gallery/src/app/gallery/gallery.component.css
> +  margin: 0 5em;  /* justify-content: center; */
видаляй коментарений код.

2020-12-12 12:54 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/8-components-templates/angular-gallery/src/app/gallery/gallery.component.css
> +.images div {
стилі тільки через класи і без вкладеностей

2020-12-12 12:54 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/8-components-templates/angular-gallery/src/app/gallery/gallery.component.css
> +.images div.selected {
для чого додаткова специфічність з div тега? Не зав'язуй свої стилі на конкретних тегах в темплаті

2020-12-12 12:54 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/8-components-templates/angular-gallery/src/app/gallery/gallery.component.html
> +      <img [class.hide-img]="!loaded" src="https://nabir.np.gov.ua/images/loading.gif">
лодер краще ховати через `*ngIf` щоб потім він в домі постіне не висів

2020-12-12 12:54 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/8-components-templates/angular-gallery/src/app/gallery/gallery.component.html
> +    (click)="onSelect(image)">
винеси елемент списку в коремий компонент і передавай туди потрібні дані та повертай наверх івент селекту. Завжди роби декомпозицію оскільки потім такий код буде простіше розвивати, ніж коли все навалено в купу

2020-12-12 12:54 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/8-components-templates/angular-gallery/src/app/gallery/gallery.component.ts
> +  //   urls: 'string',
видаляй коментарений код

2020-12-12 12:54 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/8-components-templates/angular-gallery/src/app/gallery/gallery.component.ts
> +  ngOnInit(): void {
видаляй пусті конструкції. Потрібно слідкувати за своїм кодом щоб він не перетворювався на звалище. Все що не використовується -- видаляй. Це або можна додати, або можна знайти в історії гіта

2020-12-12 12:54 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/8-components-templates/angular-gallery/src/app/gallery/gallery.component.ts
> +    this.loaded = false;
у тебе буде це працювати так що лодери на всіх картинках приберуться тоді, коли завантажеться хоч один імедж. Винеси кожен імедж в окремий компонент і там уже слухай завантаження імеджів. Так і тебе кожен імедж буде прибирати лодер тільки тоді коли він завантажеться, а не всі одразу

2020-12-12 12:54 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/8-components-templates/angular-gallery/src/app/image.ts
> +      regular: string,
зроби вверху цього файлу інтерфейси для лінок та урлів. Роздувати один інтерфейс літералами це не ок, бо він тоді може бути завеликий. Ну і в ідеалі потрібно робити під кожен тип окремий файл

2020-12-12 12:54 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/8-components-templates/angular-gallery/src/styles.css
> +  font-family: Arial, Helvetica, sans-serif;
перенеси ці стилі туди, де вони використовуються і зроби для них клас

2020-12-12 12:54 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/8-components-templates/angular-gallery/src/styles.css
> +  font-family: Arial, Helvetica, sans-serif;
Є тільки одне використання * селектора і це додавання box-sizing властивості. Фонти задаються на рутовому тегові або через клас для елементів індивідуально

2020-12-13 13:25 UTC, TArch64 commented
@LigthWarrior Пропоную робити все слідуючим чином: Я пишу якісь комменти і коли ти це фіксиш, то нажимаєш кнопку `Resolve conversation`. Можна навіть нічого не пушити на гітхаб. Таким чином я буду знати що тут нічого не зависло і йде якась робота над правками

2020-12-13 14:58 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/8-components-templates/angular-gallery/src/app/app-routing.module.ts
> +  imports: [RouterModule.forRoot(routes)],
fixed

2020-12-13 14:58 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/8-components-templates/angular-gallery/src/app/app.component.css
> +h1 {
fixed

2020-12-13 14:58 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/8-components-templates/angular-gallery/src/app/app.component.html
> +<h1>{{title}}</h1>
fixed

2020-12-13 14:58 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/8-components-templates/angular-gallery/src/app/collection-images.ts
> +import { from } from 'rxjs';
fixed

2020-12-13 14:59 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/8-components-templates/angular-gallery/src/app/gallery/gallery.component.ts
> +  ngOnInit(): void {
fixed

2020-12-13 14:59 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/8-components-templates/angular-gallery/src/app/image.ts
> +      regular: string,
fixed

2020-12-13 15:00 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/8-components-templates/angular-gallery/src/styles.css
> +  font-family: Arial, Helvetica, sans-serif;
fixed

2020-12-13 15:00 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/8-components-templates/angular-gallery/src/styles.css
> +  font-family: Arial, Helvetica, sans-serif;
fixed

2020-12-13 15:00 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/8-components-templates/angular-gallery/src/app/app-routing.module.ts
> +  imports: [RouterModule.forRoot(routes)],
fixed

2020-12-13 15:01 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/8-components-templates/angular-gallery/src/app/gallery/gallery.component.css
> +  margin: 0 5em;  /* justify-content: center; */
fixed

2020-12-13 15:01 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/8-components-templates/angular-gallery/src/app/gallery/gallery.component.css
> +.images div {
fixed

2020-12-13 15:01 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/8-components-templates/angular-gallery/src/app/gallery/gallery.component.css
> +.images div.selected {
fixed

2020-12-13 15:01 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/8-components-templates/angular-gallery/src/app/gallery/gallery.component.html
> +      <img [class.hide-img]="!loaded" src="https://nabir.np.gov.ua/images/loading.gif">
fixed

2020-12-13 15:01 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/8-components-templates/angular-gallery/src/app/gallery/gallery.component.ts
> +  //   urls: 'string',
fixed

2020-12-14 21:06 UTC, TArch64 requested changes

2020-12-14 21:06 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/8-components-templates/angular-gallery/src/app/gallery-image/gallery-image.component.css
> +/* GalleryImageComponent's private CSS styles */
якщо тобі не потрібен файл зі стилями то ти його можеш видалити та видалити поле `styleUrls` в класі компоненту

2020-12-14 21:06 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/8-components-templates/angular-gallery/src/app/gallery/gallery.component.css
> +.regular figcaption {
стилі тільки та класи. Стилі на теги це тільки в дуже рідких випадках

2020-12-14 21:06 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/8-components-templates/angular-gallery/src/app/gallery/gallery.component.html
> +    <figure>
Для чого зайві теги з дів? Не можна отак?
```html
<figure class="regular">
  <figcaption>Image</figcaption>
  <img src="{{selectedImage.urls.small}}">
</figure>
```

2020-12-15 12:41 UTC, TArch64 approved these changes

2020-12-15 12:41 UTC, merged