8 components templates
MastersAcademy/frontend-course-2020 pull request #254
Opened 2020-12-12 03:05 UTC by Anna1o1Vrana

https://anna1o1vrana.github.io/frontend-course-2020//homeworks/anna.vrana_Anna1o1Vrana/8-components-templates/templates/dist/templates/index.html

2020-12-12 13:12 UTC, TArch64 requested changes
не вистачає лінки на гітхаб пейджес

2020-12-12 13:12 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/8-components-templates/my-app-gallery/src/app/all-images/all-images.component.html
> +      <img src="{{img.urls.thumb}}" alt="" class="img">
1. не вистачає лодера для картинок.
2. винеси елемент списку в окремий компонент і передавай туди потрібні дані та повертай наверх івент селекту. Завжди роби декомпозицію оскільки потім такий код буде простіше розвивати, ніж коли все навалено в купу

2020-12-12 13:12 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/8-components-templates/my-app-gallery/src/app/all-images/all-images.component.html
> +    <li *ngFor="let img of images" (click)="onActiveImg(img)" class="{{ active?.id === img.id ? 'active' : '' }} items">
використовуй конструктці. `[class.class-name]="should-add-this-class"` для динамічних класів

2020-12-12 13:12 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/8-components-templates/my-app-gallery/src/app/all-images/all-images.component.html
> +    <div *ngIf="active">
навіщо тобі   <div class="img-wrapper"> якщо він пустий коли нічого не вибрано? перемісти іф сюди щоб його взагалі не рендерити

2020-12-12 13:12 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/8-components-templates/my-app-gallery/src/app/all-images/all-images.component.html
> +  <div class="img-wrapper">
для чого тобі тут клас, який використовується для списку? Щоб поцентру поставити? Зроби окремий клас для цього

2020-12-12 13:12 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/8-components-templates/my-app-gallery/src/app/all-images/all-images.component.html
> +  <ul class="img-wrapper">
img-wrapper говорить про один елемент а ти це використовуєш для списку. Більш правильно буде назвати це `images` а елемент буде `images-item`. Давай внятні назви класам щоб по них можна було зрозуміти для чого вони використовуються бо img-wrapper items про це взагалі нічого не кажуть

2020-12-12 13:12 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/8-components-templates/my-app-gallery/src/app/all-images/all-images.component.ts
> +  public active: Img | undefined;
`public active:? Img;`

2020-12-12 13:12 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/8-components-templates/my-app-gallery/src/app/all-images/all-images.component.ts
> +    this.active = this.active?.id === activeImg.id ? undefined : activeImg;
перепиши оце з використанням if

2020-12-12 13:12 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/8-components-templates/my-app-gallery/src/app/all-images/all-images.component.ts
> +  ngOnInit(): void {
видаляй пусті конструкції. Потрібно слідкувати за своїм кодом щоб він не перетворювався на звалище. Все що не використовується -- видаляй. Це або можна додати, або можна знайти в історії гіта

2020-12-12 13:12 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/8-components-templates/my-app-gallery/src/app/app.component.css
> +  width: 1600px;
задавай у таких випадках бо не завжди у користувача екран більше 1600 пікселів
```css
max-width: 1600px;
width: 100%;
```

2020-12-12 13:12 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/8-components-templates/my-app-gallery/src/app/app.component.html
> +  <h1 class="gallery-title">{{appTitle}}</h1>
```suggestion
  <h1 class="gallery-title">Gallery</h1>
```
**Не потрібно** прокидати динамічно текст який **завжди** статичний

2020-12-12 13:12 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/8-components-templates/my-app-gallery/src/app/constants/data.ts
> +}
```ts
class Urls {
  constructor(
    public raw: string,
    public full: string,
    public regular: string,
    public small: string,
    public thumb: string
  ) {}
}
```

2020-12-12 14:14 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/8-components-templates/my-app-gallery/src/app/all-images/all-images.component.html
> +    <div *ngIf="active">
done)

2020-12-12 14:17 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/8-components-templates/my-app-gallery/src/app/all-images/all-images.component.html
> +  <div class="img-wrapper">
done)

2020-12-12 14:19 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/8-components-templates/my-app-gallery/src/app/all-images/all-images.component.html
> +  <ul class="img-wrapper">
done)

2020-12-12 14:22 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/8-components-templates/my-app-gallery/src/app/all-images/all-images.component.ts
> +  ngOnInit(): void {
done)

2020-12-12 14:24 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/8-components-templates/my-app-gallery/src/app/app.component.html
> +  <h1 class="gallery-title">{{appTitle}}</h1>
done)

2020-12-12 14:26 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/8-components-templates/my-app-gallery/src/app/constants/data.ts
> +}
done)

2020-12-13 13:26 UTC, TArch64 commented
@Anna1o1Vrana Пропоную робити все слідуючим чином: Я пишу якісь комменти і коли ти це фіксиш, то нажимаєш кнопку `Resolve conversation`. Можна навіть нічого не пушити на гітхаб. Таким чином я буду знати що тут нічого не зависло і йде якась робота над правками

2020-12-16 17:30 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/8-components-templates/my-app-gallery/src/app/all-images/all-images.component.html
> +      <img src="{{ active?.urls?.small }}" alt="">
Done)

2020-12-16 18:13 UTC, TArch64 requested changes

2020-12-16 18:13 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/8-components-templates/my-app-gallery/src/app/all-images/all-images.component.html
> +      class="{{ active?.id === img.id ? 'active' : '' }} images-item">
динамічні класи додавай через ангуляровський `[class.your-class-name]`

2020-12-16 18:13 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/8-components-templates/my-app-gallery/src/app/all-images/all-images.component.ts
> +
пусті конструкції. В коді не має бути нічого зайвого

2020-12-16 18:13 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/8-components-templates/my-app-gallery/src/app/all-images/all-images.component.ts
> +  public active: Img | undefined;
```suggestion
  public active?: Img;
```

2020-12-16 18:13 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/8-components-templates/my-app-gallery/src/app/all-images/all-images.component.ts
> +  onActiveImg(activeImg: Img): any {
Став any тільки якщо в тебе немає іншого хляху. Якщо функція нічого не повертає то там має бути `void`. Простав на всі функції та змінні нормальні типи

2020-12-16 18:13 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/8-components-templates/my-app-gallery/src/app/all-images/all-images.component.ts
> +
тут зайві пусті рядочки

2020-12-16 18:13 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/8-components-templates/my-app-gallery/src/app/constants/data.ts
> +  id: number;
винеси `Img` в окремий файл. І якщо робиш `Urls` класом то і `Img` теж зроби класом

2020-12-16 21:56 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/8-components-templates/my-app-gallery/src/app/all-images/all-images.component.ts
> +    this.active = this.active?.id === activeImg.id ? undefined : activeImg;
done)

2020-12-16 21:58 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/8-components-templates/my-app-gallery/src/app/all-images/all-images.component.ts
> +  public active: Img | undefined;
done)

2020-12-16 23:19 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/8-components-templates/my-app-gallery/src/app/all-images/all-images.component.html
> +      class="{{ active?.id === img.id ? 'active' : '' }} images-item">
done)

2020-12-16 23:58 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/8-components-templates/my-app-gallery/src/app/all-images/all-images.component.html
> +    <li *ngFor="let img of images" (click)="onActiveImg(img)" class="{{ active?.id === img.id ? 'active' : '' }} items">
done)

2020-12-16 23:58 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/8-components-templates/my-app-gallery/src/app/all-images/all-images.component.ts
> +
Deleted)

2020-12-16 23:58 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/8-components-templates/my-app-gallery/src/app/all-images/all-images.component.ts
> +  onActiveImg(activeImg: Img): any {
done)

2020-12-18 12:38 UTC, closed without merging