8 components templates - spavel
MastersAcademy/frontend-course-2020 pull request #258
Opened 2020-12-12 18:34 UTC by spavel-gh

_[GitHub Pages link](https://spavel-gh.github.io/frontend-course-2020/homeworks/sokurenko.pavel_spavel_gh/8-components-templates/gallery-spavel/dist/gallery-spavel/) (рабочий прототип)_

Todo:

- [ ] Выделение превью при их выборе.
- [ ] Заменить бесконечную галерею на замкнутую с блокировкой кнопок на краях
- [ ] Дизайн

2020-12-12 18:45 UTC, powerbot15 requested changes
Добавление к твоим туду: еще нужен лоадер, пока картинки грузятся

2020-12-12 19:21 UTC, spavel-gh commented
> Добавление к твоим туду: еще нужен лоадер, пока картинки грузятся

Как я понимаю, это просто заглушка

2020-12-13 02:08 UTC, spavel-gh commented
> Добавление к твоим туду: еще нужен лоадер, пока картинки грузятся

Не могу протестировать. Похоже, картинки грузятся быстрее, чем лоадер с гитхаба. Но локальном сервере всё работало.

2020-12-13 10:58 UTC, powerbot15 requested changes

2020-12-13 10:58 UTC, powerbot15 commented on homeworks/sokurenko.pavel_spavel_gh/8-components-templates/gallery-spavel/src/app/gallery/image/image.component.html
> +  <input
Не используй инпут для кнопки, у него есть ограничения. Замени на `<button type="button">` здесь и вторую кнопку тоже

2020-12-13 10:58 UTC, powerbot15 commented on homeworks/sokurenko.pavel_spavel_gh/8-components-templates/gallery-spavel/src/app/gallery/image/image.component.html
> +<div class="grid-item"></div>
Это тут лишнее

2020-12-13 10:58 UTC, powerbot15 commented on homeworks/sokurenko.pavel_spavel_gh/8-components-templates/gallery-spavel/src/app/gallery/image/image.component.scss
> +input {
не используй имена тегов как селекторы

2020-12-13 10:58 UTC, powerbot15 commented on homeworks/sokurenko.pavel_spavel_gh/8-components-templates/gallery-spavel/src/app/gallery/gallery.component.scss
> +img {
не используй имена тегов как селекторы

2020-12-13 10:58 UTC, powerbot15 commented on homeworks/sokurenko.pavel_spavel_gh/8-components-templates/gallery-spavel/src/app/gallery/gallery.component.ts
> +  maxIndexOfImagesObj = this.images.length - 1;
По дефолту это все паблик, какой смысл в одном месте явно это указывать? Надо тогда ко всем свойствам тоже добавить паблик, или тот удалить

2020-12-13 14:14 UTC, spavel-gh commented on homeworks/sokurenko.pavel_spavel_gh/8-components-templates/gallery-spavel/src/app/gallery/image/image.component.html
> +<div class="grid-item"></div>
> Это тут лишнее

Хочу поинтересоваться. Если в ТЗ будет задание сделать квадратики в стиле превью картинок (как здесь реализовано), то как верстать эти квадратики с теми-же относительными rem размерами как и у превью?

Сейчас всё в css, вёрстку можно сделать достаточно простой и поддерживаемой, применив css переменные размеров. Если задача - избавиться от дивов, я вижу только решение в попытке переписать всё под svg, где отдельно написанная библиотека будет читать актуальные размеры карточек и генерировать svg фигуры вместо текущих div квадратов. Да, мы избавимся от дивов, но рационально ли такое сложное решение?

2020-12-13 15:45 UTC, powerbot15 requested changes

2020-12-13 15:45 UTC, powerbot15 commented on homeworks/sokurenko.pavel_spavel_gh/8-components-templates/gallery-spavel/src/app/gallery/image/image.component.html
> +<div class="grid-item"></div>
В этом ТЗ не было такого пункта) Я не имею ввиду избавляться от дивов как от элементов разметки, просто тут этот набор дивов не имеет смысла. На нем нет никакой логики, ты просто показываешь этот кусок верстки и все. Да еще и находится он в компоненте image. Какая связь между вьюхой большой картинки и этими заглушками?

2020-12-14 06:43 UTC, powerbot15 approved these changes

2020-12-14 06:44 UTC, merged