8 components templates
MastersAcademy/frontend-course-2020 pull request #261
Opened 2020-12-12 21:58 UTC by andrey241991

https://andrey241991.github.io/frontend-course-2020/homeworks/andrey.kushch_andrey241991/8_components_templates/dist/index.html

2020-12-13 13:51 UTC, TArch64 requested changes

2020-12-13 13:51 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/8_components_templates/components-templates/src/app/app.component.css
> +  margin: 8px 0;
Вважається не дуже хорошим задавати так стилі на всі хедінги на інші теги. Такі відступи можуть змінюватися (і я мовчу про те, що маржін можна робити тільки в одному напрямку) в залежності від ситуації і тобі потрібно буде робити оверрайд цих стилів. Краще зробити хелпер клас в якому будуть ці стилі і вішати на теги де це потрібно. Доволі частою практикою є робити класи типу `offset-bottom--xs` це буде `margin-bottom: 8px` і використовувати в таких випадках

2020-12-13 13:51 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/8_components_templates/components-templates/src/app/app.component.html
> +  <app-gallery-container></app-gallery-container>
Якщо не використовуєш роутинг (а ти його тут не використовуєш), то видали його з проекту. отут прибери зроби просто тег `<app-gallery-container></app-gallery-container>` без `<router-outlet>` і видали файл `app-routing.module.ts`

2020-12-13 13:51 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/8_components_templates/components-templates/src/app/app.component.ts
> +  title = 'components-templates';
`title` у тебе не використовується. Потрібно слідкувати за своїм кодом і прибирати те що не потрібно (пусті методи, конструктори, поля які не використовуюся чи файли). Так код буде набагато чистішим та зрозумілішим. В разі чого гіт пам'ятає все і це можна дістати з пам'яті гіта, або ж самому заново написати

2020-12-13 13:51 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/8_components_templates/components-templates/src/app/data.ts
> +export const images = [
покрий типами оцю констану. Зроби якісь інтерфейси чи класи для цього
```ts
export const images: Image[] = [.....]
```

2020-12-13 13:51 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/8_components_templates/components-templates/src/app/gallery-container/gallery-container.component.css
> +  margin: 0;
Хоч стилі компонентів інкапсулюються, але ніхто не відміняв того що стилі вішаємо тільки через класи. Як мінімум це набагато зрозуміліше для іниших розібратися що тут відбувається

2020-12-13 13:51 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/8_components_templates/components-templates/src/app/gallery-container/gallery-container.component.html
> +<div>
для чого потрібен оцей дів без ніяких атрибутів?

2020-12-13 13:51 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/8_components_templates/components-templates/src/app/gallery-container/gallery-container.component.ts
> +    this.currentImg = images[imgPosition]
замість того щоб зберігати окрему позицію імеджа та його інтекс краще замінити `currentImg` на геттер, а тут ставити `imgPosition` замість `currentImg`
```ts
get currentImg(): Image {
  return this.images[this.imgPosition];
}

setCurrentImg(position: number): void {
  this.imgPosition = position;
}
```

2020-12-13 13:51 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/8_components_templates/components-templates/src/app/gallery-container/gallery-container.component.ts
> +  currentImg = images[0]
Скрізь крім примітивів (а ще краще навіть і на примітивах) проставляй типи. Типізація це гарантія того що коли щось змінюється то ти не пропустиш ті місця де це потрібно також змінити. Вся суть типізації щоб завжди знати що приходить в тому чи іншому місці і чи приходить туди те що потрібно

2020-12-13 13:51 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/8_components_templates/components-templates/src/app/image-gallery/image-gallery.component.ts
> +  @Input() images: any;
`any` тип вбиває типізацію. Ця штука використовується тільки в дуже особливих випадках і якщо є можливість зробити тип то його потрібно робити

2020-12-13 13:51 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/8_components_templates/components-templates/src/app/image-slider/image-slider.component.ts
> +  @Input() currentImg: any;
вся суть типізації щоб знати в темплейтові що у тебе буде в цьому полі і чи коли ти будеш діставати `currentImg.urls.regular` у тебе не впаде помилка бо немає поля `regular`

2020-12-13 13:51 UTC, TArch64 commented on package.json
>          "eslint": "^7.9.0",
відміни всі зміни в рутових `package.json` та `package-lock.json`

2020-12-13 13:51 UTC, TArch64 commented
@andrey241991 Пропоную робити все слідуючим чином: Я пишу якісь комменти і коли ти це фіксиш, то нажимаєш кнопку `Resolve conversation`. Можна навіть нічого не пушити на гітхаб. Таким чином я буду знати що тут нічого не зависло і йде якась робота над правками

2020-12-15 18:43 UTC, andrey241991 commented on homeworks/andrey.kushch_andrey241991/8_components_templates/components-templates/src/app/app.component.ts
> +  title = 'components-templates';
Поправил, просто Ангулар столько всего создает, и не ясно что тут нужно, что не нужно =/

2020-12-15 18:48 UTC, andrey241991 commented on homeworks/andrey.kushch_andrey241991/8_components_templates/components-templates/src/app/app.component.css
> +  margin: 8px 0;
Это ангулар сам создал) а можно сюда допустим reset всех стилей поставить, или это плохая практика и лучше ставить его в index.html?
И если мне допустим тут стиля не нужны нормальная практика просто удалить css файл?

2020-12-15 18:50 UTC, andrey241991 commented on homeworks/andrey.kushch_andrey241991/8_components_templates/components-templates/src/app/gallery-container/gallery-container.component.css
> +  margin: 0;
Линтер ругался, пришлось хоть что то добавить, сейчас просто удалил этот файл

2020-12-15 20:04 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/8_components_templates/components-templates/src/app/app.component.css
> +  margin: 8px 0;
Ну файл то ангуляр створив, але ці стилі він сам не додає. Вся суть ресета доволі дивна, бо він скидає там де потрібно і там де не потрібно стилі. Краще там де потрібно там і правити стилі

2020-12-15 21:04 UTC, andrey241991 commented on homeworks/andrey.kushch_andrey241991/8_components_templates/components-templates/src/app/app.component.css
> +  margin: 8px 0;
Понял, спасибо

2020-12-15 21:18 UTC, andrey241991 commented on package.json
>          "eslint": "^7.9.0",
Ну я их руками не менял, а что в них не так?

2020-12-15 21:21 UTC, TArch64 commented on package.json
>          "eslint": "^7.9.0",
Ти запустив npm install packake-name який і змінив цей файл. Якщо пропускаєш опшин -g то воно змінить локальні файли. Ця команда встановлює пакет який ти скажеш і фіксує ці зміни у package.json та package-lock.json

2020-12-15 21:40 UTC, TArch64 requested changes
Все ще є зміни в `package.json` та `package-lock.json`.

Так як сьогодні лекції не було то можеш за завтра ще доробити ці комменти

2020-12-15 21:40 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/8_components_templates/components-templates/src/app/gallery-container/gallery-container.component.ts
> +const LAST_IMG_POSITION: number = images.length - 1
замість такого краще робити в компоненті геттери. Так вся перевірка винесеться окремо що буде трохи більш зрозуміліше і простіше використовувати + буде простіше зробити тут динамічну кількість імеджів в списку
```ts
get isFirstImage(): boolean {
  return this.imgPosition === 0;
}

get lastImageIndex(): number {
  return this.images.length - 1;
};

get isLastImage(): boolean {
  return this.imgPosition === this.lastImageIndex;
}
```

2020-12-15 21:40 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/8_components_templates/components-templates/src/app/gallery-container/gallery-container.component.ts
> +  onNext() {
Краще на всіх методах ставити тип який повертається. Навіть якщо там void то воно буде в майбутньому слідкувати щоб ніхто не повертав з цього метода те що не потрібно і не зав'язував на цьому якусь логіку

2020-12-15 21:40 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/8_components_templates/components-templates/src/app/image-gallery/image-gallery.component.css
> +  width: 100%;
вішати на імедж погана ідея (якщо не використовуєш object-fit) бо у випадку коли відношення сторін імеджа та парента різні, то контент імеджа буде розтягуватися. Краще використовуй `max-width` та `max-height` у таких випадках

2020-12-15 21:40 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/8_components_templates/components-templates/src/app/image-gallery/image-gallery.component.html
> +    <div class="item" [ngClass]="i === imgPosition ? 'item--active' : ''">
```suggestion
    <div class="item" [сlass.item--active]="i === imgPosition">
```
Для одного динамічного класу краще використовуй такий синтаксис. Він більш простий у читанні

2020-12-15 21:40 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/8_components_templates/components-templates/src/app/image-gallery/image-gallery.component.ts
> +  @Input() images: Image[] = [] as Image[];
для пустого масиву не потрібно робити приведення типу до `Image[]`. Головне щоб було вказано це у поля

2020-12-15 21:40 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/8_components_templates/components-templates/src/app/image-slider/image-slider.component.html
> +  <img class="slider__img" src="{{ currentImg?.urls?.regular }}" alt="" />
можна ховати всю секцію слайдера якщо немає активного імеджа

2020-12-15 21:40 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/8_components_templates/components-templates/src/app/image-slider/image-slider.component.ts
> +  @Input() currentImg: Image = {} as Image;
якщо поле опціональне то краще вказати `currentImg?: Image` та перевірки де це потрібно. Приведення типу у даному випадку не рулить бо ти називаєш пустий об'єкт не тим що він є насправді. Хтось буде думати що там поля ті що йому потрібно а по факту там буде пусто. Якщо поле опційне то краще вказати його як опційне

2020-12-15 21:40 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/8_components_templates/components-templates/src/app/image-slider/image-slider.component.ts
> +  @Output() onNext = new EventEmitter();
Для `EventEmitter` краще завжди вказуй тип щоб той хто це використовує знав що він отримає в івенті. Якщо нічого передавати не потрібно то можна вказувати `null`

2020-12-15 21:40 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/8_components_templates/components-templates/src/app/models/image.ts
> +export default Image;
Дефолтні експорти мають проблему в тому що не зберігається неймінг того що ти імпортиш і коли ти шукаєш це в коді то воно може бути названо по іншому просто тому що так назвали. Використовуй найменовані експорти

2020-12-16 13:59 UTC, andrey241991 commented on homeworks/andrey.kushch_andrey241991/8_components_templates/components-templates/src/app/image-slider/image-slider.component.ts
> +  @Output() onNext = new EventEmitter();
ругается на null

2020-12-16 14:00 UTC, andrey241991 commented on package.json
>          "eslint": "^7.9.0",
Ага, я понял. А как мне это поправить?

2020-12-16 18:03 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/8_components_templates/components-templates/src/app/image-slider/image-slider.component.ts
> +  @Output() onNext = new EventEmitter();
ну бо потрібно і робити `@Output() onPrev = new EventEmitter<null>();` та `this.onPrev.emit(null)`;

2020-12-16 18:05 UTC, TArch64 commented
Всеще є зміни в оцих файлах. Я пулл реквест не прийму поки оці зміни тут не зникнуть. Я не знаю як ти це зробиш, але їх тут не повинно бути. У тебе ще є час завтра на це 
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/29049264/102388110-f96c2780-3fd9-11eb-886d-d689090673d0.png">

2020-12-17 00:42 UTC, andrey241991 commented on homeworks/andrey.kushch_andrey241991/8_components_templates/components-templates/src/app/image-slider/image-slider.component.ts
> +  @Output() onNext = new EventEmitter();
Ок, пасиб, поправил

2020-12-17 00:43 UTC, andrey241991 commented on package.json
>          "eslint": "^7.9.0",
А чекни плиз, я всё пересобрал, так как надо или нет?

2020-12-17 20:59 UTC, TArch64 approved these changes

2020-12-17 20:59 UTC, merged