8-components-templates
MastersAcademy/frontend-course-2020 pull request #262
Opened 2020-12-12 22:09 UTC by MykYarovenko36

https://mykyarovenko36.github.io/frontend-course-2020/homeworks/mykola.yarovenko_MykYarovenko36/8-components-templates/dist/my-app/

2020-12-13 12:19 UTC, AlexKuskov requested changes
Не вистачає наступних моментів в роботі:
1. При клікові мишки на саму картинку, вона не вибирається і не відображається знизу
2. У вибраної картинки не змінюється колір її бордера

2020-12-15 19:52 UTC, AlexKuskov requested changes
Ping

2020-12-16 07:51 UTC, AlexKuskov requested changes

2020-12-16 07:51 UTC, AlexKuskov commented on homeworks/mykola.yarovenko_MykYarovenko36/8-components-templates/src/app/data.ts
> +export const data =
в JS такого типу конструкції записуються так:
```
export const data = [
  { ...
```

2020-12-16 07:51 UTC, AlexKuskov commented on homeworks/mykola.yarovenko_MykYarovenko36/8-components-templates/src/app/gallary/gallary.component.html
> +                [disabled]="btnPrevIsDisabled? 'disabled' : null"
можна просто залишити
`[disabled]="btnPrevIsDisabled"`

2020-12-16 07:51 UTC, AlexKuskov commented on homeworks/mykola.yarovenko_MykYarovenko36/8-components-templates/src/app/gallary/gallary.component.html
> +                [disabled]="btnNextIsDisabled? 'disabled' : null"
тут те саме, що і в коменті зверху

2020-12-16 07:51 UTC, AlexKuskov commented on homeworks/mykola.yarovenko_MykYarovenko36/8-components-templates/src/app/data.ts
> +export const data =
такі файли зазвичай зберігаються в папці app/mocks

2020-12-16 07:51 UTC, AlexKuskov commented on homeworks/mykola.yarovenko_MykYarovenko36/8-components-templates/src/app/dataItems.ts
> +export interface dataItems {
назви цей інтерфейс типу Image, чи щось таке. dataItems - дуже розпливчато

2020-12-16 07:51 UTC, AlexKuskov commented on homeworks/mykola.yarovenko_MykYarovenko36/8-components-templates/src/app/dataItems.ts
> +  id: string,
структура його складається з більшої кількості полів, аніж тільки 2.
```
id: 'YhWRSEdBXUE',
description: null,
urls: {
    raw: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?ixid=MXwxODg5MjR8MXwxfGFsbHwxfHx8fHx8Mnw&ixlib=rb-1.2.1',
    full: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?crop=entropy&cs=srgb&fm=jpg&ixid=MXwxODg5MjR8MXwxfGFsbHwxfHx8fHx8Mnw&ixlib=rb-1.2.1&q=85',
    regular: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MXwxODg5MjR8MXwxfGFsbHwxfHx8fHx8Mnw&ixlib=rb-1.2.1&q=80&w=1080',
    small: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MXwxODg5MjR8MXwxfGFsbHwxfHx8fHx8Mnw&ixlib=rb-1.2.1&q=80&w=400',
    thumb: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MXwxODg5MjR8MXwxfGFsbHwxfHx8fHx8Mnw&ixlib=rb-1.2.1&q=80&w=200'
},
links: {
    self: 'https://api.unsplash.com/photos/YhWRSEdBXUE',
    html: 'https://unsplash.com/photos/YhWRSEdBXUE',
    download: 'https://unsplash.com/photos/YhWRSEdBXUE/download',
    download_location: 'https://api.unsplash.com/photos/YhWRSEdBXUE/download'
},
likes: 86
```

2020-12-16 07:51 UTC, AlexKuskov commented on homeworks/mykola.yarovenko_MykYarovenko36/8-components-templates/src/app/dataItems.ts
> +export interface dataItems {
цей файл це модель. Він має бути в папці app/models

2020-12-16 07:51 UTC, AlexKuskov commented on homeworks/mykola.yarovenko_MykYarovenko36/8-components-templates/src/app/gallary/gallary.component.ts
> +            if (item.id === id) {
якщо є тільки 1 умова при якій має виконуватись код в функції, то щоб не вкладувати все в огроменний іф, просто напиши
```
if (item.id !== id) return;

some code
```

2020-12-16 07:51 UTC, AlexKuskov commented on homeworks/mykola.yarovenko_MykYarovenko36/8-components-templates/src/app/gallary/gallary.component.ts
> +    itemIsActive: boolean;
роби відступи між змінними і конструктором, а також між функціями. Так легше читати код

2020-12-16 07:51 UTC, AlexKuskov commented on homeworks/mykola.yarovenko_MykYarovenko36/8-components-templates/src/app/gallary-item/gallary-item.component.html
> +    [ngStyle]="{
не використовуй інлайнові стилі без зайвої необхідності. Схоже, що вони тту не потрібні

2020-12-16 07:51 UTC, AlexKuskov commented on homeworks/mykola.yarovenko_MykYarovenko36/8-components-templates/src/app/gallary-item/gallary-item.component.html
> +    [hidden]="itemIsLoad? null: 'hidden'"
можна замінити цим
`[hidden]="!itemIsLoad"`

2020-12-16 07:51 UTC, AlexKuskov commented on homeworks/mykola.yarovenko_MykYarovenko36/8-components-templates/src/app/gallary-item/gallary-item.component.html
> +  <div *ngIf="!itemIsLoad" class="item-loader"><div></div><div></div></div>
Схоже, що ці діви `<div></div><div></div></div>` тут зайві

2020-12-16 11:46 UTC, MykYarovenko36 commented on homeworks/mykola.yarovenko_MykYarovenko36/8-components-templates/src/app/gallary-item/gallary-item.component.html
> +  <div *ngIf="!itemIsLoad" class="item-loader"><div></div><div></div></div>
Це частина лоадеру, вони були стилізовані як loader div {} ... etc. Додав до них class.

2020-12-16 13:45 UTC, AlexKuskov commented
як закінчиш роботу над помилками, зареквесть ревью будь ласка
![image](https://user-images.githubusercontent.com/24815257/102356313-bb5d0c80-3fb5-11eb-93e5-a78f2ddf2bea.png)

2020-12-16 14:19 UTC, MykYarovenko36 commented on homeworks/mykola.yarovenko_MykYarovenko36/8-components-templates/src/app/gallary-item/gallary-item.component.html
> +  <div *ngIf="!itemIsLoad" class="item-loader"><div></div><div></div></div>
thanks for your code review!

2020-12-16 14:50 UTC, AlexKuskov commented on homeworks/mykola.yarovenko_MykYarovenko36/8-components-templates/src/app/data.ts
> +export const data =
назва папки має бути mocks, а не moks

2020-12-16 14:56 UTC, AlexKuskov commented on homeworks/mykola.yarovenko_MykYarovenko36/8-components-templates/src/app/gallary-item/gallary-item.component.html
> +  <div *ngIf="!itemIsLoad" class="item-loader"><div></div><div></div></div>
you're welcome!

2020-12-16 15:08 UTC, AlexKuskov requested changes

2020-12-16 15:08 UTC, AlexKuskov commented on homeworks/mykola.yarovenko_MykYarovenko36/8-components-templates/src/app/models/dataImage.ts
> +export interface dataGallary {
зазвичай моделі називають Image, Gallery, Block, Page (зверни увагу на те, що всі вони починаються з великої букви і в них немає data в назві). 
Файл теж потрібно перейменувати. По типу `models/image.ts`

2020-12-16 15:08 UTC, AlexKuskov commented on homeworks/mykola.yarovenko_MykYarovenko36/8-components-templates/src/app/models/dataImage.ts
> +export interface dataImage {
ця модель не потрібна. Тобі достатньо тієї що зверху (ту що зверху я б назвав Image, так як вона відповідає за дані картинки)

2020-12-16 15:08 UTC, AlexKuskov commented on homeworks/mykola.yarovenko_MykYarovenko36/8-components-templates/src/app/gallary/gallary.component.ts
> +        this.cards = data.map((item: dataGallary): dataImage => {
якщо ти залишиш тільки 1 модель (я про це написав в інших коментах), то тобі і не доведеться робити трасформування данних через .map

2020-12-16 16:06 UTC, MykYarovenko36 commented on homeworks/mykola.yarovenko_MykYarovenko36/8-components-templates/src/app/gallary/gallary.component.ts
> +        this.cards = data.map((item: dataGallary): dataImage => {
Суперски, это хороший подход.

2020-12-16 16:41 UTC, AlexKuskov requested changes
Клас, майже все готово, ось ці штуки підправ, і буду мерджити
1. коммент
![image](https://user-images.githubusercontent.com/24815257/102378153-29153280-3fce-11eb-84b7-faf87d0f75a9.png)
2. не працює лінка на апп
![image](https://user-images.githubusercontent.com/24815257/102378188-34685e00-3fce-11eb-8da9-284ec15e6e47.png)

2020-12-16 17:26 UTC, AlexKuskov approved these changes

2020-12-16 17:32 UTC, merged