9 layouts
MastersAcademy/frontend-course-2020 pull request #263
Opened 2020-12-13 20:04 UTC by VolodymyrUstilkin

2020-12-14 18:24 UTC, smithua commented
Я замежил твою домашку, можешь переключить и добавить с GH pages ссылку на верстку. Спасибо!

2020-12-14 18:25 UTC, smithua requested changes
Я замежил твою домашку предыдущую, можешь переключить и добавить с GH pages ссылку на верстку. Спасибо!

2020-12-14 18:57 UTC, VolodymyrUstilkin commented
https://volodymyrustilkin.github.io/frontend-course-2020/homeworks/volodymyr.ustilkin_VolodymyrUstilkin/9-layouts/flexbox/index.html

https://volodymyrustilkin.github.io/frontend-course-2020/homeworks/volodymyr.ustilkin_VolodymyrUstilkin/9-layouts/grid/index.html

2021-01-27 22:04 UTC, smithua approved these changes
Достаточно хорошо, учел коменты которые я проговаривал на лекции.

2021-01-27 22:08 UTC, merged