8 components
MastersAcademy/frontend-course-2020 pull request #271
Opened 2020-12-15 16:54 UTC by MatviienkoOleh

2020-12-15 16:55 UTC, MatviienkoOleh commented
https://matviienkooleh.github.io/frontend-course-2020/homeworks/oleh.matviienko_MatviienkoOleh/8-components/myProgect/dist/myProgect/

2020-12-15 17:00 UTC, MatviienkoOleh commented
linter tellling me that i have empty space in scc file but i dont , cant find the way to fix it

2020-12-15 19:46 UTC, TArch64 commented
@MatviienkoOleh почитай уважніше що означає ця помилка
> Unexpected empty source   no-empty-source

2020-12-16 10:48 UTC, powerbot15 requested changes

2020-12-16 10:48 UTC, powerbot15 commented on homeworks/oleh.matviienko_MatviienkoOleh/8-components/myProgect/src/app/components/components/gallery/gallery.component.ts
> +    bigPicture.setAttribute('Src', src);
Не надо так делать, работать напрямую с элементами из компонента используя поиск в DOM плохая практика. Сделай через data binding, чтобы использовалась интерполяция или рендер переменных в темплейт. У тебя ж есть `selectedItem`, его поля и прокидывай в темплейт.

2020-12-16 10:48 UTC, powerbot15 commented on homeworks/oleh.matviienko_MatviienkoOleh/8-components/myProgect/src/app/components/components/gallery/gallery.component.ts
> +  increasePicture(pictures:any) {
Сюда приходит одна картинка, а у тебя название как будто их много, picture**s**

2020-12-16 10:48 UTC, powerbot15 commented on homeworks/oleh.matviienko_MatviienkoOleh/8-components/myProgect/src/app/components/components/gallery/gallery.component.ts
> +  public selectedItem : any ;
у `selectedItem` должен быть определенный тип, а не `any`

2020-12-16 10:48 UTC, powerbot15 commented on homeworks/oleh.matviienko_MatviienkoOleh/8-components/myProgect/src/app/components/components/gallery/gallery.component.ts
> +  description: any;
тут у тебя может быть или текст или null, значит тип `string | null`

2020-12-16 12:58 UTC, powerbot15 requested changes

2020-12-16 12:58 UTC, powerbot15 commented on homeworks/oleh.matviienko_MatviienkoOleh/8-components/myProgect/src/app/components/components/gallery/gallery.component.ts
> +}
Что-то ты с этими типами совсем запутался(( Смотри, у тебя есть две переменных одного типа, это `picture` и `selectedItem`. Поставь им обоим тип `ImagesObj`. А то у тебя одна `any`, вторая `string`, а на самом деле там объект)) Не спеши, подумай почему это так должно быть. На этой неделе по жс домашки нет, так что не обязательно сегодня все закончить

2020-12-16 20:04 UTC, MatviienkoOleh commented on homeworks/oleh.matviienko_MatviienkoOleh/8-components/myProgect/src/app/components/components/gallery/gallery.component.ts
> +}
Есть такое , немного запутался . Упустил из виду что получаю объект , при том что обращался к его полям )))

2020-12-18 08:05 UTC, powerbot15 approved these changes

2020-12-18 08:07 UTC, merged