Anton Nemesh, Homework #11 Angular: dependency injection
MastersAcademy/frontend-course-2020 pull request #291
Opened 2020-12-23 22:36 UTC by AntonNemesh

https://antonnemesh.github.io/frontend-course-2020/homeworks/anton.nemesh_AntonNemesh/11-dependency-injection/dist/
![image](https://user-images.githubusercontent.com/10253504/103041774-0eb7f780-4580-11eb-8f62-03088aee8655.png)

2020-12-24 21:16 UTC, MZabolotnev approved these changes

2020-12-24 21:18 UTC, MZabolotnev requested changes
homeworks/anton.nemesh_AntonNemesh/10-media/style.css - прорвался файл из другой домашки)

2020-12-24 21:51 UTC, AntonNemesh commented
> homeworks/anton.nemesh_AntonNemesh/10-media/style.css - прорвался файл из другой домашки)

Да, я видел этот конфликт, но файла этого найти я не могу в пулл риквесте, в этом пулл риквесте у меня нет ни 10-й, ни 9-й домашки. Знаю это точно, уже не один раз это проверял)

2020-12-25 13:03 UTC, AntonNemesh commented
> homeworks/anton.nemesh_AntonNemesh/10-media/style.css - прорвался файл из другой домашки)

Пофиксил

2020-12-27 16:21 UTC, MZabolotnev approved these changes

2020-12-27 16:21 UTC, merged