11 dependency injection
MastersAcademy/frontend-course-2020 pull request #300
Opened 2020-12-25 17:06 UTC by LigthWarrior

2020-12-25 17:09 UTC, LigthWarrior commented
![Screenshot from 2020-12-25 18-43-52](https://user-images.githubusercontent.com/58568950/103139437-a3d40100-46e4-11eb-8ca5-8fd713bb828e.png)
https://ligthwarrior.github.io/frontend-course-2020/homeworks/andrii.stoliarov_lightwarrior/11-dependency-injection/angular-vehicles/dist/angular-vehicles/

2020-12-27 12:03 UTC, TArch64 requested changes

2020-12-27 12:03 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/11-dependency-injection/angular-vehicles/src/app/pipes/tranform-field-vehicle.pipe.ts
> +export class TransformFieldVehicle implements PipeTransform {
Переназви цей пайп щоб було зрозуміло що він робить

2020-12-27 12:03 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/11-dependency-injection/angular-vehicles/src/styles.css
> +  line-height: 1.6;
перенеси це в стилі компонента. Чим менше глобальних стилів тим краще

2020-12-27 12:03 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/11-dependency-injection/angular-vehicles/src/styles.css
> +@import url("https://fonts.googleapis.com/css?family=Roboto");
Вкажи які жирності використовуєш і не забувай про `display swap`

2020-12-27 12:03 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/9-layouts/flexbox/index.html
> +    <div class="wrapper">
Файлів з папки `9-layouts` тут не має бути

2020-12-27 15:13 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/11-dependency-injection/angular-vehicles/src/app/app.component.html
> +<span class="loader" *ngIf="loaded">Loading...</span>
fixed

2020-12-27 15:26 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/11-dependency-injection/angular-vehicles/src/app/app.component.html
> +  <ul class="uList" *ngIf="!loaded">
fixed

2020-12-27 15:38 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/11-dependency-injection/angular-vehicles/src/app/app.component.html
> +      <a class="aLink" appPostFieldVehicles href="{{ vehicle | searchLinkPost }}">
fixed

2020-12-27 15:41 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/11-dependency-injection/angular-vehicles/src/app/app.component.ts
> +  loaded: boolean = false;
fixed

2020-12-27 15:52 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/11-dependency-injection/angular-vehicles/src/app/models/vehicle.model.ts
> +export interface Vehicle {
fixed

2020-12-27 16:13 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/11-dependency-injection/angular-vehicles/src/app/pipes/tranform-field-vehicle.pipe.ts
> +export class TransformFieldVehicle implements PipeTransform {
fixed

2020-12-27 16:52 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/11-dependency-injection/angular-vehicles/src/styles.css
> +  line-height: 1.6;
fixed

2020-12-27 17:01 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/11-dependency-injection/angular-vehicles/src/app/mocks/vechicles.mock.ts
> +function getFakeVehicle() {
fixed

2020-12-27 17:01 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/11-dependency-injection/angular-vehicles/src/app/pipes/index.ts
> +import { from } from 'rxjs';
fixed

2020-12-28 14:02 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/11-dependency-injection/angular-vehicles/src/app/app.component.ts
> +      .subscribe((vehicles: Vehicle[]) => this.vehicles = vehicles);
fixed

2020-12-28 17:44 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/11-dependency-injection/angular-vehicles/src/app/app.component.ts
> +      .subscribe((vehicles: Vehicle[]) => this.vehicles = vehicles);
fixed

2020-12-28 19:41 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/11-dependency-injection/angular-vehicles/src/styles.css
> +@import url("https://fonts.googleapis.com/css?family=Roboto");
fixed

2020-12-29 11:42 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/11-dependency-injection/angular-vehicles/src/app/directives/post-field-vehicles.directive.ts
> +      this.el.nativeElement.style.pointerEvents = 'none';
fixed

2020-12-30 18:32 UTC, TArch64 requested changes

2020-12-30 18:32 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/11-dependency-injection/angular-vehicles/src/app/app.component.css
> +@import url("https://fonts.googleapis.com/css?family=Roboto");
зайди на font.google.com і згенерь нормальну урлу з вказанням потрібних жирностів і використай замість оцих @import та @font-face

2020-12-30 18:32 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/11-dependency-injection/angular-vehicles/src/app/app.component.html
> +            <span>{{ vehicle | reduceExpressionToSimple }}</span>
назви цей пайп так щоб було зрозуміло для чого він або що він робить

2020-12-30 20:27 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/9-layouts/flexbox/index.html
> +    <div class="wrapper">
fixed

2020-12-30 20:27 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/9-layouts/flexbox/index.html
> +                <div class="logo">
fixed

2020-12-31 10:53 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/11-dependency-injection/angular-vehicles/src/app/app.component.css
> +@import url("https://fonts.googleapis.com/css?family=Roboto");
fixed

2020-12-31 11:34 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/11-dependency-injection/angular-vehicles/src/styles.css
> +  padding: 0;
fixed

2021-01-07 12:37 UTC, TArch64 approved these changes

2021-01-07 12:39 UTC, merged