11 dependency injection
MastersAcademy/frontend-course-2020 pull request #302
Opened 2020-12-26 09:02 UTC by Anna1o1Vrana

2020-12-27 13:36 UTC, TArch64 requested changes

2020-12-27 13:36 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/app.component.ts
> +  title = 'dependency-injection';
це поле десь використовується?

2020-12-27 13:36 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/directive/decoration-protocol.directive.ts
> +    if(this.el.nativeElement.innerHTML === 'http'){
напряму змінювати елементи в домі це погано. Використай ангуляровський сервіс `Renderer2`

2020-12-27 13:36 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/directive/decoration-protocol.directive.ts
> +    if(this.el.nativeElement.innerHTML === 'http'){
Дивитися в текстовий контент елемента також погано, бо там може щось змінитися і в тебе все заламається

2020-12-27 13:36 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/directive/decoration-protocol.directive.ts
> +    if(this.el.nativeElement.innerHTML === 'http'){
Форматинг даних може бути різний і на нього не потрібно зав'язуватися

2020-12-27 13:36 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/directive/decoration-protocol.directive.ts
> +    if(this.el.nativeElement.innerHTML === 'http'){
ти сюди передаєш через інпут `appDecorationProtocol` то його і використовуй

2020-12-27 13:36 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/mocks/vehicles.mock.ts
> +function getFakeVehicle() {
додай до цієї функції який тип даних вона повертає

2020-12-27 13:36 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/mocks/vehicles.mock.ts
> +// tslint:disable-next-line:typedef
для чого тс лінт відключила?

2020-12-27 13:36 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/models/vehicle.model.ts
> +export interface VehiclePost {
якщо у тебе в назві файла `model` то я тут хочу бачити класи. Якщо ти хочеш інтерфейси то назви файл по іншому

2020-12-27 13:36 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/services/vehicle.service.ts
> +  }
прибирай мусор у файлах

2020-12-27 13:36 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/table/table.component.html
> +<div *ngIf="areVehicleLoading">Loading...</div>
більш звично бачити в назвах `is` а не `are`. Хоч це граматично не правильно, але назви змінних не мають бути граматично правильні. Зазвичай додають `is` навіть якщо там і множина

2020-12-27 13:36 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/table/table.component.html
> +<table class="table" *ngIf="!areVehicleLoading">
замість 2х `*ngIf` використовуй `else`.
https://stackoverflow.com/a/43006589/9904159https://stackoverflow.com/a/43006589/9904159

2020-12-27 13:36 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/table/table.component.html
> +    <td appDecorationProtocol>{{ vehicle.post.protocol }}</td>
У тебе описане інпут поле в дірективі, але ти його не передаєш сюди

2020-12-27 13:36 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/table/table.component.scss
> +/*style for table*/
`/*style for table*/` не потрібно писати бо у тебе компонент називається `table`

2020-12-27 13:36 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/table/table.component.scss
> +  padding: 10px 20px;
всі. стилі. додавай. через. класи

2020-12-27 13:36 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/table/table.component.scss
> +  //background-color: rgb(245, 245, 245);
цей слектор щось робить?

2020-12-27 13:36 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/table/table.component.ts
> +    this.vehicleService.getVehicle()
Якщо є можливість то замість такої `.subscribe(( vehicle: Vehicle[] ) => this.vehicles = vehicle);` використовуй пайп `async`

```ts
  public vehicles$: Observable<Vehicle[]>;

  constructor(private vehicleService: VehicleService) {
    this.vehicles$ = this.getVehicle();
  }

  private getVehicle(): Observable<Vehicle[]> {
    this.areVehicleLoading = true;

    return this.vehicleService.getVehicle().pipe(
      finalize(() => this.areVehicleLoading = false)
    );
  }
```

```html
<tr *ngFor="let vehicle of vehicles$ | async; let i=index">
      <td appDecorationProtocol>{{ vehicle.post.protocol }}</td>
</tr>
```

2020-12-27 13:36 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/9--layouts/index.html
> +<head>
Зроби так щоб тут була тільки 11 домашка

2020-12-27 21:39 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/app.component.ts
> +  title = 'dependency-injection';
ні, видалила його

2020-12-27 22:23 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/mocks/vehicles.mock.ts
> +function getFakeVehicle() {
додала)

2020-12-27 22:23 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/mocks/vehicles.mock.ts
> +// tslint:disable-next-line:typedef
включила)

2020-12-27 22:45 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/models/vehicle.model.ts
> +export interface VehiclePost {
rename)

2020-12-27 22:53 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/services/vehicle.service.ts
> +  }
deleted)

2020-12-27 23:27 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/table/table.component.html
> +<table class="table" *ngIf="!areVehicleLoading">
change)

2020-12-27 23:28 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/table/table.component.scss
> +/*style for table*/
ok

2020-12-27 23:29 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/9--layouts/index.html
> +<head>
done)

2020-12-27 23:50 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/table/table.component.html
> +<div *ngIf="areVehicleLoading">Loading...</div>
change)

2020-12-27 23:50 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/table/table.component.scss
> +/*style for table*/
deleted)

2020-12-27 23:50 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/table/table.component.scss
> +  //background-color: rgb(245, 245, 245);
deleted)

2020-12-28 00:01 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/table/table.component.scss
> +  padding: 10px 20px;
done)

2020-12-28 00:01 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/9--layouts/index.html
> +<head>
done)

2020-12-28 19:36 UTC, TArch64 requested changes

2020-12-28 19:36 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/mocks/vehicles.mock.ts
> +function getFakeVehicle(): any {
`any` Ніколи не використовуй цей тип без поважної причини. Вказуй нормальні типи

2020-12-28 19:36 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/table/table.component.scss
> +.table-row:nth-child(even) td {
тут стилі на тегові `td`

2020-12-28 19:36 UTC, TArch64 commented on package.json
> +        "husky": "^4.3.0"
У тебе тут зміни в цьому файлику, а їх тут не має бути

2020-12-29 04:51 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/directive/decoration-protocol.directive.ts
> +    if(this.el.nativeElement.innerHTML === 'http'){
done)

2020-12-29 04:56 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/table/table.component.html
> +    <td appDecorationProtocol>{{ vehicle.post.protocol }}</td>
ok)

2020-12-29 23:51 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/table/table.component.ts
> +    this.vehicleService.getVehicle()
fixed)

2020-12-29 23:52 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/mocks/vehicles.mock.ts
> +function getFakeVehicle(): any {
changed)

2020-12-29 23:52 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/table/table.component.scss
> +.table-row:nth-child(even) td {
renamed)

2020-12-29 23:54 UTC, Anna1o1Vrana commented on package.json
> +        "husky": "^4.3.0"
reverted changes)

2020-12-30 22:41 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/directive/decoration-protocol.directive.ts
> +    if(this.el.nativeElement.innerHTML === 'http'){
used)

2020-12-31 15:43 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/table/table.component.html
> +    <td appDecorationProtocol>{{ vehicle.post.protocol }}</td>
passed)

2020-12-31 15:43 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/11-dependency-injection/dependency-injection/src/app/directive/decoration-protocol.directive.ts
> +    if(this.el.nativeElement.innerHTML === 'http'){
used)

2021-01-07 13:06 UTC, TArch64 approved these changes

2021-01-07 13:08 UTC, merged