11 dependency injection
MastersAcademy/frontend-course-2020 pull request #303
Opened 2020-12-26 15:29 UTC by MatviienkoOleh

не успеваю сегодня закончить , залил хоть что-то

2020-12-27 08:53 UTC, powerbot15 requested changes
Ок, доделывай

2020-12-28 08:04 UTC, MatviienkoOleh commented
https://matviienkooleh.github.io/frontend-course-2020/

2020-12-28 15:31 UTC, powerbot15 requested changes

2020-12-28 15:31 UTC, powerbot15 commented on homeworks/oleh.matviienko_MatviienkoOleh/11-dependency-injection/newProg/src/app/app.component.html
> +  <ul *ngFor = "let cars of arrayOfVehicles" class = "list_Of_Cars">
Поправь тут отступы и переменная `cars` - это когда их много, у тебя в итерацию попадает одна - значит `car`

2020-12-28 15:31 UTC, powerbot15 commented on homeworks/oleh.matviienko_MatviienkoOleh/11-dependency-injection/newProg/src/app/models/vehicle.model.ts
> +
отступы хромают

2020-12-28 15:31 UTC, powerbot15 commented on homeworks/oleh.matviienko_MatviienkoOleh/11-dependency-injection/newProg/src/app/pipes/characteristics.pipe.ts
> +export class PricePipe implements PipeTransform {
`PricePipe` - название не соответствует содержимому

2020-12-28 15:31 UTC, powerbot15 commented on homeworks/oleh.matviienko_MatviienkoOleh/11-dependency-injection/newProg/src/app/pipes/index.ts
> +];
Тут то же самое - `PricePipe` - не соответствует внутренностям пайпа

2020-12-29 18:00 UTC, powerbot15 approved these changes

2020-12-29 18:02 UTC, merged