11 dependency injection
MastersAcademy/frontend-course-2020 pull request #305
Opened 2020-12-26 17:43 UTC by andrey241991

https://andrey241991.github.io/frontend-course-2020/homeworks/andrey.kushch_andrey241991/dependency-injection/dist/dependency-injection/

2020-12-27 14:22 UTC, TArch64 requested changes

2020-12-27 14:22 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/dependency-injection/src/app/app.component.css
> +th {
всі стилі тільки через класи

2020-12-27 14:22 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/dependency-injection/src/app/app.component.css
> +.--color-red {
для чого `--` на початку класа?

2020-12-27 14:22 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/dependency-injection/src/app/app.component.html
> +  <table *ngIf="!areVehicleLoading">
замість 2х `*ngIf` використовуй `else`.
https://stackoverflow.com/a/43006589/9904159https://stackoverflow.com/a/43006589/9904159

2020-12-27 14:22 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/dependency-injection/src/app/app.component.html
> +  <div *ngIf="areVehicleLoading">Loading...</div>
більш звично бачити в назвах `is` а не `are`. Хоч це граматично не правильно, але назви змінних не мають бути граматично правильні. Зазвичай додають `is` навіть якщо там і множина

2020-12-27 14:22 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/dependency-injection/src/app/app.component.html
> +        {{ vehicle.manufacturer }} - {{ vehicle.model }} {{ vehicle.fuel }}
В завданні казалось щоб покласти отак в пайп

2020-12-27 14:22 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/dependency-injection/src/app/app.component.ts
> +    this.vehicleService.getVehicles().subscribe((vehicles: Vehicle[]) => {
коли ти робиш `subscribe` то потрібно слідкувати ще за підписками самому і відписуватися якщо це потрібно. Якщо є можливість то старайся використовувати пайп `async` і тоді ангуляр це буде робити замість тебе

```ts
  public vehicles$: Observable<Vehicle[]>;

  constructor(private vehicleService: VehicleService) {
    this.vehicles$ = this.getVehicles();
  }

  private getVehicles(): Observable<Vehicle[]> {
    this.vehicleService.getVehicles().pipe(
      tap(() => this.setVehicleLoading(false))
    );
  }
```
```html
<tr *ngFor="let vehicle of vehicles$ | async">
  <td>{{ vehicle.manufacturer }}</td>
</tr>
```

2020-12-27 14:22 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/dependency-injection/src/app/models/vechicle.ts
> +        slug: string;
винеси типи post та cost в окремі інтерфейси

2020-12-27 14:22 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/dependency-injection/src/app/services/vehicle.service.ts
> +            delay(3000)
в завданні казалось по 2 секунди, а у тебе тут 3

2020-12-27 14:22 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/dependency-injection/src/app/services/vehicle.service.ts
> +    constructor() { }
видаляй пусті конструкції

2020-12-29 19:26 UTC, andrey241991 commented on homeworks/andrey.kushch_andrey241991/dependency-injection/src/app/app.component.css
> +.--color-red {
Тут изменение цвета,  позначил как modifier

2020-12-29 19:28 UTC, andrey241991 commented on homeworks/andrey.kushch_andrey241991/dependency-injection/src/app/app.component.html
> +  <div *ngIf="areVehicleLoading">Loading...</div>
ну да, по код-конвеншену) просто лекцию смотрел и автоматом тоже так назвал) поправил

2020-12-29 22:51 UTC, andrey241991 commented on homeworks/andrey.kushch_andrey241991/dependency-injection/src/app/app.component.ts
> +    this.vehicleService.getVehicles().subscribe((vehicles: Vehicle[]) => {
я попробовал, что то так не хочет работать =(

2020-12-30 18:45 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/dependency-injection/src/app/app.component.ts
> +    this.vehicleService.getVehicles().subscribe((vehicles: Vehicle[]) => {
Я знайшов проблему. Там через те що лодінг потрібно проти по іншому робити, через Observable а не як сайд ефект. Бо використовується стрім `this.vehicles$` тільки всередині ngFor який всередині ngIf і ангуляр не робить підписку бо ngFor не рендериться через те що в ngIf приходить фолс.

Тут потрібно робити не через `tap` а через окремий стрім `loading$` який основується на `vehicles$` і в ngIf його теж передавати з async. Типу такого
```ts
this.loading$ = this.vehicle$.pipe(map(() => false), startWith(true))
```
Працює це так що створюється стрім з початковим значенням `true` і коли стається будь-який івент в стрімові vehicle$ то значення змінюється на фолс. Можеш попробувати зробити отак або хоча б додай відписку від `subscribe` в коді

2020-12-30 18:50 UTC, TArch64 requested changes

2020-12-30 18:50 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/dependency-injection/src/app/app.component.html
> +          {{ vehicle | vehiclePipe: true }}
колонки `Added from` та `Vehicle` 2 абсолютно різні поля у яких повністю своя логіка форматингу данних. Для такого потрібно робити 2 різних пайпа. Але ти ж там ніяк не форматиш проткол тому його можеш просто тут показати без всяких пайпів

2020-12-30 18:50 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/dependency-injection/src/app/models/vechicle.ts
> +interface cost {
Назви інтерфейсів починаються з великої літери

2021-01-07 12:32 UTC, TArch64 approved these changes

2021-01-07 12:34 UTC, merged