dependency injection
MastersAcademy/frontend-course-2020 pull request #308
Opened 2020-12-26 21:58 UTC by MykYarovenko36

https://mykyarovenko36.github.io/frontend-course-2020/homeworks/mykola.yarovenko_MykYarovenko36/11-dependency-injection/dist/

2020-12-28 15:35 UTC, AlexKuskov requested changes
1. зроби будь ласка розділення між елементами, а то все слитно, важко розділяти де який елемент
![image](https://user-images.githubusercontent.com/24815257/103225641-11756c80-4933-11eb-854e-cab449b30972.png)

2. це поле http, воно має бути не клікабельне
![image](https://user-images.githubusercontent.com/24815257/103225421-88f6cc00-4932-11eb-8598-6a73dde9baaf.png)

2020-12-28 15:35 UTC, AlexKuskov commented on homeworks/mykola.yarovenko_MykYarovenko36/11-dependency-injection/src/app/models/vehicles.ts
> +export interface Mock_Vehicles {
`Mock_Vehicles` - інтерфейси не записуються в снейк кейсі. Використовуй CamelCase, типу `MockVehicles`

2020-12-28 15:35 UTC, AlexKuskov commented on homeworks/mykola.yarovenko_MykYarovenko36/11-dependency-injection/src/app/models/vehicles.ts
> +export interface Mock_Vehicles {
Ну і назва для цієї моделі не дуже підходяща. Коли називається модель, то використовується однина, так як описується модель одного елементу. Можна назвати її типу `Vehicle`

2020-12-28 17:05 UTC, MykYarovenko36 commented on homeworks/mykola.yarovenko_MykYarovenko36/11-dependency-injection/src/app/models/vehicles.ts
> +export interface Mock_Vehicles {
Не успевал сделать вовремя. Всё поправим.

2020-12-30 07:41 UTC, AlexKuskov approved these changes

2020-12-30 08:01 UTC, merged