12 httpclient
MastersAcademy/frontend-course-2020 pull request #317
Opened 2021-01-02 23:53 UTC by andrey241991

https://andrey241991.github.io/frontend-course-2020/homeworks/andrey.kushch_andrey241991/http-client/dist/http-client/

2021-01-07 13:04 UTC, TArch64 requested changes

2021-01-07 13:04 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/http-client/src/app/services/loader.service.ts
> +    public isLoading: BehaviorSubject<boolean> = new BehaviorSubject<boolean>(false);
`BehaviorSubject` робити публічним не дуже добре, бо це є внутрішньою особливістю цього сервісу. Це має бути через методи та геттери
```ts
private readonly loadingSubject: BehaviorSubject<boolean> = new BehaviorSubject<boolean>(false);

public get isLoading(): boolean {
  return this.loadingSubject.value;
}

public get isLoading$(): Observable<boolean> {
  return this.loadingSubject.asObservable();
}

public enableLoading(): void {
  this.loadingSubject.next(true);
}

public disableLoading(): void {
  this.loadingSubject.next(false);
}
```

2021-01-07 13:04 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/http-client/src/app/services/user.service.ts
> +    getUsers(page: number): Observable<any> {
any -- вказуй нормальні типи. Оця штука це крайній випадок

2021-01-07 13:04 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/http-client/src/app/services/user.service.ts
> +        return this.http.get(`${this.BASE_API}users?page=${page}`);
передавай параметр page через об'єкт параметрів

2021-01-07 23:18 UTC, andrey241991 commented on homeworks/andrey.kushch_andrey241991/http-client/src/app/services/loader.service.ts
> +    public isLoading: BehaviorSubject<boolean> = new BehaviorSubject<boolean>(false);
Понял, спасибо

2021-01-10 12:46 UTC, TArch64 approved these changes

2021-01-10 12:46 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/http-client/src/app/services/user.service.ts
> +        params = params.append('page', String(page));
замість такої конструкції
```ts
let params = new HttpParams();
params = params.append('page', String(page));
```
краще використовуй отаке
```ts
const params = { page: String(page) }
```
І приводити по типу до стрінги не обов'язково. Ангуляр сам це зробить

2021-01-10 12:48 UTC, merged