12 httpclient
MastersAcademy/frontend-course-2020 pull request #324
Opened 2021-01-04 16:30 UTC by LigthWarrior

![Screenshot from 2021-01-04 18-19-04](https://user-images.githubusercontent.com/58568950/103556685-d2a75f80-4eba-11eb-9624-3f23b5d0acd4.png)

2021-01-07 13:23 UTC, TArch64 requested changes

2021-01-07 13:23 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/12-httpclient/angular-users/src/app/app-routing.module.ts
> +const routes: Routes = [];
якщо не використовуєш роутер то видали його

2021-01-07 13:23 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/12-httpclient/angular-users/src/app/app.component.html
> +      <div *ngFor="let user of userData | paginate: {itemsPerPage: 2, currentPage: currentPage}" class="user-card">
винеси `{itemsPerPage: 2, currentPage: currentPage}` в геттер

2021-01-07 13:23 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/12-httpclient/angular-users/src/app/app.component.html
> +      <div *ngFor="let user of userData | paginate: {itemsPerPage: 2, currentPage: currentPage}" class="user-card">
старайся якнайменше логіки робити в темплаті

2021-01-07 13:23 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/12-httpclient/angular-users/src/app/app.component.html
> +  <hr class="horizontal-line">
`horizontal-line` можна просто `divider`

2021-01-07 13:23 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/12-httpclient/angular-users/src/app/app.component.ts
> +  userData: User[] = [];
`userData` має буть `users` бо там множина і `Data` не несе в собі ніякої інформативної цінності

2021-01-07 13:23 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/12-httpclient/angular-users/src/app/app.component.ts
> +      .subscribe((users: User[]) => {
винеси виклик сервісу в метод а тут роби отак `this.subscription.add(this.getUsers())`. У твоєму варіанті `ngOnInit` буде дуже веливий якщо тут ще якийсь запит з'явиться

2021-01-07 13:23 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/12-httpclient/angular-users/src/app/interceptors/auth.interceptor.ts
> +      tap((event: HttpEvent<any>) => {
видаляй код який не потрібен

2021-01-07 13:23 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/12-httpclient/angular-users/src/app/interceptors/auth.interceptor.ts
> +    });
```ts
    request = request.clone({
      headers: request.headers.set('Accept-Language', 'RANDOM TEXT')
    })
    request = request.clone({
      headers: request.headers.append('Auth', 'RANDOM TEXT')
    });
```
має бути
```ts
intercept(initialRequest: HttpRequest<any>....
const request = initialRequest.clone({
  headers: initialRequest.set(...).set(...)
});
```

2021-01-07 13:23 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/12-httpclient/angular-users/src/app/interceptors/auth.interceptor.ts
> +      headers: request.headers.set('Accept-Language', 'RANDOM TEXT')
Тут точно має бути `RANDOM TEXT`?

2021-01-07 13:23 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/12-httpclient/angular-users/src/app/interfaces/page.ts
> +      url: string;
винеси тип поля support в окремий інтерфейс

2021-01-07 13:23 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/12-httpclient/angular-users/src/app/interfaces/page.ts
> +export interface Page {
я б це назвав `UsersResponse`

2021-01-07 13:23 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/12-httpclient/angular-users/src/app/interfaces/page.ts
> +export interface Page {
Page взагалі не дає зрозуміти що це

2021-01-07 13:23 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/12-httpclient/angular-users/src/app/services/user.service.ts
> +      params: new HttpParams().set('per_page', '6')
```suggestion
      params: { per_page:  '6' }
```

2021-01-07 18:48 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/12-httpclient/angular-users/src/app/app-routing.module.ts
> +const routes: Routes = [];
fixed

2021-01-07 18:49 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/12-httpclient/angular-users/src/app/app.component.html
> +  <hr class="horizontal-line">
fixed

2021-01-07 18:52 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/12-httpclient/angular-users/src/app/app.component.ts
> +  userData: User[] = [];
fixed

2021-01-07 18:56 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/12-httpclient/angular-users/src/app/interceptors/auth.interceptor.ts
> +      tap((event: HttpEvent<any>) => {
fixed

2021-01-07 19:00 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/12-httpclient/angular-users/src/app/services/user.service.ts
> +      params: new HttpParams().set('per_page', '6')
fixed

2021-01-07 19:05 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/12-httpclient/angular-users/src/app/interfaces/page.ts
> +export interface Page {
fixed

2021-01-07 19:15 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/12-httpclient/angular-users/src/app/interfaces/page.ts
> +      url: string;
fixed

2021-01-07 19:34 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/12-httpclient/angular-users/src/app/interceptors/auth.interceptor.ts
> +      headers: request.headers.set('Accept-Language', 'RANDOM TEXT')
fixed

2021-01-07 19:41 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/12-httpclient/angular-users/src/app/interceptors/auth.interceptor.ts
> +    });
fixed

2021-01-08 11:32 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/12-httpclient/angular-users/src/app/app.component.ts
> +      .subscribe((users: User[]) => {
fixed

2021-01-08 17:15 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/12-httpclient/angular-users/src/app/app.component.html
> +      <div *ngFor="let user of userData | paginate: {itemsPerPage: 2, currentPage: currentPage}" class="user-card">
fixed

2021-01-10 12:50 UTC, TArch64 approved these changes

2021-01-10 12:52 UTC, merged