13 ng forms
MastersAcademy/frontend-course-2020 pull request #345
Opened 2021-01-16 11:40 UTC by Anna1o1Vrana

https://anna1o1vrana.github.io/frontend-course-2020/homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/dist/ng-forms/

[link](https://anna1o1vrana.github.io/frontend-course-2020/homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/dist/ng-forms/)

![Screenshot from 2021-01-16 13-40-29](https://user-images.githubusercontent.com/72143197/104810894-73bde080-5800-11eb-9668-e3600810504c.png)

2021-01-18 21:41 UTC, TArch64 requested changes

2021-01-18 21:41 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/app.component.ts
> +    email: new FormControl('',
використай тут `FormBuilder` і відформатуй красівенько код

2021-01-18 21:41 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/app.component.ts
> +    const control = this.authorizationForm.controls[controlName];
щоб не робити `.controls[controlName]` можна використовувати `.get(controlName)`

2021-01-18 21:41 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/app.component.ts
> +    localStorage.setItem('password', password)
отак ти кажеш іншим що ломайте оце поле тут пароль. Сейвай все в одне поле і ключ краще називати якось типу `auth`

2021-01-18 21:41 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/app.component.ts
> +    if (this.authorizationForm.value.checkbox === true) {
тут точно потрібен `if...else`?

2021-01-19 08:57 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/app.component.ts
> +    localStorage.setItem('email', email)
винеси зберігання, діставання і форматування даних в сервіс

2021-01-19 17:50 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/app.component.ts
> +    const control = this.authorizationForm.controls[controlName];
fixed)

2021-01-19 21:59 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/app.component.ts
> +    if (this.authorizationForm.value.checkbox === true) {
fixed)

2021-01-19 23:20 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/app.component.ts
> +    localStorage.setItem('email', email)
fixed)

2021-01-19 23:21 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/app.component.ts
> +    localStorage.setItem('password', password)
fixed)

2021-01-20 00:27 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/app.component.ts
> +    email: new FormControl('',
used)

2021-01-20 08:17 UTC, TArch64 requested changes

2021-01-20 08:17 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/app.component.ts
> +    const authorizationData = 'Login: ' + `${this.authorizationForm.value.email}` + '     Password: ' + `${this.authorizationForm.value.password}`;
вся суть оцих косих кавичок щоб не використовувати конкатенацію. Зроби тут **тільки** з використанням темплейт строк

2021-01-20 08:17 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/app.component.ts
> +    if (this.authorizationForm.value.checkbox === true) {
```suggestion
    if (this.authorizationForm.value.checkbox) {
```

2021-01-20 08:17 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/app.component.ts
> +    checkbox: new FormControl()
назви це поле білш осмислино. Якщо в тебе буде ще один чекбокс то ти додаси контрол `checkbox2`?

2021-01-20 08:17 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/app.component.ts
> +        Validators.pattern(/[A-z]/)]
на логінці ніхто ніколи не робить валідації на пароль. Лише його присутність і все

2021-01-20 08:17 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/app.component.ts
> +      const dataEncode = JSON.parse(atob(localStorage.getItem('data')))
**діставання** і **збереження** даних має бути в сервісі. В компоненті лише логіка яка напряму стосується роботи з UI

2021-01-20 08:17 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/app.component.ts
> +      const dataEncode = JSON.parse(atob(localStorage.getItem('data')))
в компоненті взагалі немає бути ніяких згадок про локал сторедж

2021-01-20 08:17 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/app.component.ts
> +    private fb: FormBuilder) {
не скророчуй назви

2021-01-20 08:17 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/app.component.ts
> +    email: new FormControl('',
Суть форм білдера в тому щоб прибрати трохи копіпасту з купи конструкторів
```suggestion
    email: ['', [Validators.required, Validators.email]],
```

2021-01-20 08:17 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/models/data.model.ts
> +export class DataModel {
`DataModel` **ніколи** так нічого не називай. Це як назвати змінну `var`. У тебе є чітка назва того що ти зберігаєш

2021-01-20 08:17 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/service/saveAuth.service.ts
> +
відформатуй красівенько цей файл

2021-01-20 08:30 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/models/data.model.ts
> +export class DataModel {
deleted data.model.ts)

2021-01-20 08:30 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/service/saveAuth.service.ts
> +
done)

2021-01-20 10:56 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/service/saveAuth.service.ts
> +
done)

2021-01-20 10:56 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/models/data.model.ts
> +export class DataModel {
deleted folder "models" as unused

2021-01-20 10:56 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/app.component.ts
> +        Validators.pattern(/[A-z]/)]
deleted)

2021-01-20 10:56 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/app.component.ts
> +    if (this.authorizationForm.value.checkbox === true) {
fix)

2021-01-20 10:58 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/app.component.ts
> +    email: new FormControl('',
modified)

2021-01-20 11:07 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/app.component.ts
> +    private fb: FormBuilder) {
renamed)

2021-01-20 11:10 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/app.component.ts
> +      const dataEncode = JSON.parse(atob(localStorage.getItem('data')))
fixed)

2021-01-20 11:13 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/app.component.ts
> +    const authorizationData = 'Login: ' + `${this.authorizationForm.value.email}` + '     Password: ' + `${this.authorizationForm.value.password}`;
fixed)

2021-01-20 11:22 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/app.component.ts
> +    checkbox: new FormControl()
renamed)

2021-01-20 14:24 UTC, TArch64 requested changes

2021-01-20 14:24 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/service/saveAuth.service.ts
> +  checkLocalStorage() {
дуже багато деталей в назві. Просто `getData` і якщо нічого немає в локал стореджі то повертай якісь деолтні занчення. І де типи в тоїх методах? На кожен метод і аргумент я хочу бачити типи

2021-01-20 16:56 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/service/saveAuth.service.ts
> +  checkLocalStorage() {
fixed)

2021-01-21 01:26 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/service/saveAuth.service.ts
> +  saveData(data: AuthorizationDataModel): void {
no, changed type to interface AuthorizationData

2021-01-21 02:16 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/app.component.ts
> +      'email': dataEncode.email,
created)

2021-01-21 02:24 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/service/saveAuth.service.ts
> +      return null
add default data on ngOnInit()

2021-01-21 02:56 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/service/saveAuth.service.ts
> +      return null
changed default data in  service getData() and deleted duplicate FormBuilder on init without data in Local Storage

2021-01-21 10:42 UTC, TArch64 requested changes

2021-01-21 10:42 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/app.component.ts
> +      this.authorizationForm = this.FormBuilder.group({
Ти тут 2 раза створюєш форму. Роби це в конструкторі щоб такого не було

2021-01-21 10:42 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/service/saveAuth.service.ts
> +      return {
В такому випадку тут не потрібно else писати. Воно тільки робить читання коду складнішим. Не використовуй `if + else` якщо це можливо

2021-01-21 12:52 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/app.component.ts
> +      this.authorizationForm = this.FormBuilder.group({
fixed)

2021-01-21 12:52 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/13-ng-forms/ng-forms/src/app/service/saveAuth.service.ts
> +      return {
fixed)

2021-01-21 14:51 UTC, TArch64 approved these changes

2021-01-21 14:51 UTC, merged