13 ng forms
MastersAcademy/frontend-course-2020 pull request #347
Opened 2021-01-16 19:00 UTC by LigthWarrior

2021-01-18 22:12 UTC, TArch64 requested changes

2021-01-18 22:12 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/app.component.html
> +      <input class="field-input" type="text" placeholder="enter email" formControlName="email">
коли ти використовуєш input та label не забувай їх зв'язувати через id. Для чого таке робиться можеш почитати в інтернетах

2021-01-18 22:12 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/app.component.html
> +        *ngIf="form.get('email').invalid && form.get('email').touched"
винеси оцю умову в метод `form.get('email').invalid && form.get('email').touched`. і у тебе ж тут однаково для пасворда тільки поле інше потрібно діставати то тут щось можна перевикористати

2021-01-18 22:12 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/app.component.html
> +          The field cannot be empty.
оці текстовки можна винести в метод і тут його викликати. Для пасворда та імейла логіка в тебе однакова просто різні поля

2021-01-18 22:12 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/app.component.ts
> +    this.form = new FormGroup({
використай тут `FormBuilder`

2021-01-18 22:12 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/app.component.ts
> +  private encodedDataPassword: string = '';
тобі не потрібно зберігати це все тут. Зроби сервіс який буде зберігати та діставати дані і якось їх форматувати (енкодінг) а тут буде оригінал і то він має діставатися з стану форми

2021-01-18 22:12 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/app.component.ts
> +    const getLocalStoragePassword: string = localStorage.getItem('password') || '';
Тобі тут не потрібен колбек на `window:load`. Ти можеш сетити початкові дані разом зі створенням форми

2021-01-19 13:05 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/app.component.html
> +      <input class="field-input" type="text" placeholder="enter email" formControlName="email">
fixed

2021-01-19 13:33 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/app.component.html
> +        *ngIf="form.get('email').invalid && form.get('email').touched"
fixed

2021-01-19 14:22 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/app.component.ts
> +    this.form = new FormGroup({
fixed

2021-01-19 19:52 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/app.component.ts
> +    const getLocalStoragePassword: string = localStorage.getItem('password') || '';
fixed

2021-01-19 20:24 UTC, TArch64 requested changes

2021-01-19 20:24 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/app.component.html
> +        *ngIf="isInvalidAndTouched('email')"
можна просто `isControlInvalid`

2021-01-19 20:24 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/app.component.html
> +          The field cannot be empty.
Я про самі текстовки. 
бо можна зробити отак 
```html
<small>{{ getFieldError('email') }}</small>
```

2021-01-19 20:24 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/app.component.html
> +      <input type="checkbox" formControlName="checkbox">
в усіх інпутів мають бути лейбли

2021-01-19 20:24 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/app.component.ts
> +    const getLocalStoragePassword: string = localStorage.getItem('password') || '';
А де сервіс?

2021-01-20 14:45 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/app.component.ts
> +  private encodedDataPassword: string = '';
fixed

2021-01-20 14:45 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/app.component.ts
> +    const getLocalStoragePassword: string = localStorage.getItem('password') || '';
fixed

2021-01-20 14:47 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/app.component.html
> +        *ngIf="isInvalidAndTouched('email')"
fixed

2021-01-20 14:49 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/app.component.html
> +      <input type="checkbox" formControlName="checkbox">
fixed

2021-01-20 15:00 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/app.component.html
> +          The field cannot be empty.
fixed

2021-01-20 17:08 UTC, TArch64 requested changes

2021-01-20 17:08 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/app.component.ts
> +    this.dataPassword = this.encodeDataFormService.getDecodedDataPassword();
для чого потрібно зберігати значення в `this` (стосується і сервіса)? Якщо якісь дані використовуються тільки всередині одного метода то не потрібно такого робити. Просто зроби всередині цього метода константу та і все

2021-01-20 17:08 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/app.component.ts
> +      checkbox: new FormControl(false, [
для чекбоксів тут не потрібен `required` валідатор. Контретно цей чекбокс може бути або тру або фолс

2021-01-20 17:08 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/app.component.ts
> +      email: new FormControl('', [
суть форм білдера в тому щоб зменшини кількість дублювання однакового коду
```ts
email: ['', [Validators.email, Validators.required]]
```

2021-01-20 17:08 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/app.component.ts
> +    this.dataEmail = this.encodeDataFormService.getDecodedDataEmail();
Для чого ти створюєш пусту форму а потім змінюєш її значення? Не можна одразу передати потрібе початкове значення в контрол?

2021-01-20 17:08 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/services/encode-data-form.service.ts
> +    localStorage.setItem('password', this.encodedDataPassword);
Я ж писав не зберігати ці поля окремо. Це має бути один запис в локал сторедж

2021-01-20 17:08 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/interfaces/form.interface.ts
> +export interface Form {
чекбокс у тебе в цьому типові не використовується того його і не потрібно тут писати. Краще назвати ще якось так `Credentials`. ця назва несе більше в собі сенсу ніж Форм. Ну і тут в тебе не форма, а значення полів форми. А між цим велика різниця

2021-01-20 17:08 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/services/encode-data-form.service.ts
> +  setDataLocalStorage(data: Form): void {
можна просто методи `get` та `set` без ніяких деталей куди воно зберігає. Це зайве бо це конкретна реалізація, а вона може змінюватися

2021-01-21 10:31 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/app.component.ts
> +    this.dataPassword = this.encodeDataFormService.getDecodedDataPassword();
fixed

2021-01-21 10:31 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/app.component.ts
> +    this.dataEmail = this.encodeDataFormService.getDecodedDataEmail();
fixed

2021-01-21 10:31 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/services/encode-data-form.service.ts
> +    localStorage.setItem('password', this.encodedDataPassword);
fixed

2021-01-21 10:37 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/interfaces/form.interface.ts
> +export interface Form {
fixed

2021-01-21 10:38 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/services/encode-data-form.service.ts
> +  setDataLocalStorage(data: Form): void {
fixed

2021-01-21 10:47 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/app.component.ts
> +      checkbox: new FormControl(false, [
fixed

2021-01-21 11:01 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/app.component.html
> +          {{ getFieldError('email') }}
fixed

2021-01-21 15:03 UTC, TArch64 requested changes

2021-01-21 15:03 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/app.component.ts
> +      email: this.encodeDataFormService.get().email,
коли ти 2 рази викликаєш `this.encodeDataFormService.get()` у тебе виконується купа логіки. замість такого роби отак
```ts
const { email, password } = this.encodeDataFormService.get();
```

2021-01-21 15:03 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/services/encode-data-form.service.ts
> +    this.dataFormFilds = JSON.parse((localStorage.getItem('dataFields') || ''));
щоб не показувати людям структуру цих даних краще спочатку роби `JSON.stringify` а потім уже поверх того що воно повертає `window.atob`. Так у тебе все що будуть бачити постороні це незрозумілі символи, а у твоєму варіанті буде об'єкт з полям пошта та пароль

2021-01-21 16:25 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/services/encode-data-form.service.ts
> +  dataFormFilds: Credentials = {
fixed

2021-01-21 16:47 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/app.component.ts
> +      email: this.encodeDataFormService.get().email,
fixed

2021-01-21 17:57 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/app.component.html
> +        <small>{{ getFieldError('email') }}</small>
Залишив функцію getContolError в головному компоненті. Куди її можна винисти?

2021-01-21 18:09 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/13-ng-forms/angular-reactive-forms/src/app/services/encode-data-form.service.ts
> +    this.dataFormFilds = JSON.parse((localStorage.getItem('dataFields') || ''));
Не розумію питання. При сабміті, перед тим як зберігти в localStorage, я роблю JSON.stringify, а перед тим як розшифрувати JSON.parse. Як вони можуть бачити данні? Поясни детальніше, що потрібно зробити.

2021-01-25 17:30 UTC, merged