14 modules routing
MastersAcademy/frontend-course-2020 pull request #371
Opened 2021-01-24 16:46 UTC by LigthWarrior

![Screenshot from 2021-01-24 18-04-53](https://user-images.githubusercontent.com/58568950/105637069-1d8e1480-5e74-11eb-8a10-75ad9f2336fc.png)
https://ligthwarrior.github.io/frontend-course-2020/homeworks/andrii.stoliarov_lightwarrior/14-modules-routing/angular-three-pages/dist/angular-three-pages/accessories

2021-01-25 17:43 UTC, TArch64 requested changes

2021-01-25 17:43 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/14-modules-routing/angular-three-pages/src/app/modules/accessories/components/accessories-page/accessories-page.component.css
> +/* Unexpected empty source   no-empty-source */
якщо ругається на пустий файл то видали пустий файл

2021-01-25 17:43 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/14-modules-routing/angular-three-pages/src/app/services/route-visiting-pages.service.ts
> +        console.log(USERTENDS[index].message);
розбий цей метод на декілька менших. Вкладені іфи важко читаються

2021-01-26 10:39 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/14-modules-routing/angular-three-pages/src/app/modules/accessories/components/accessories-page/accessories-page.component.css
> +/* Unexpected empty source   no-empty-source */
fixed

2021-01-26 12:15 UTC, LigthWarrior commented on homeworks/andrii.stoliarov_lightwarrior/14-modules-routing/angular-three-pages/src/app/services/route-visiting-pages.service.ts
> +        console.log(USERTENDS[index].message);
fixed

2021-01-26 22:18 UTC, TArch64 approved these changes

2021-01-26 22:18 UTC, TArch64 commented on homeworks/andrii.stoliarov_lightwarrior/14-modules-routing/angular-three-pages/src/app/services/route-visiting-pages.service.ts
> +  showMassage(index: number): void {
```suggestion
  showMessage(index: number): void {
```

2021-01-26 22:18 UTC, merged