14 modules routing
MastersAcademy/frontend-course-2020 pull request #372
Opened 2021-01-24 17:39 UTC by Anna1o1Vrana

2021-01-25 17:50 UTC, TArch64 requested changes

2021-01-25 17:50 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/14-modules-routing/modules-routing/src/app/services/check-routing.service.ts
> +  setNewPaths(): void {
зазвичай таке називають не `setNew` а `reset`

2021-01-25 17:50 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/14-modules-routing/modules-routing/src/app/services/check-routing.service.ts
> +      this.paths.push(url)
`this.paths.push(url)` у тебе цей рядочок в обох гілках іфа однаковий

2021-01-25 17:50 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/14-modules-routing/modules-routing/src/app/services/check-routing.service.ts
> +    if (this.paths[0] === '/accessories' || this.paths[1] === '/accessories' || this.paths[0] === '/') {
що робить ця перевірка?

2021-01-25 17:50 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/14-modules-routing/modules-routing/src/app/services/check-routing.service.ts
> +    if (JSON.stringify(this.movingPaths[0]['journey']) === JSON.stringify(this.paths)) {
використай тут цикл

2021-01-25 17:50 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/14-modules-routing/modules-routing/src/app/services/check-routing.service.ts
> +    if (JSON.stringify(this.movingPaths[0]['journey']) === JSON.stringify(this.paths)) {
ітерації наше все

2021-01-25 20:11 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/14-modules-routing/modules-routing/src/app/services/check-routing.service.ts
> +  setNewPaths(): void {
fixed)

2021-01-25 20:27 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/14-modules-routing/modules-routing/src/app/services/check-routing.service.ts
> +    if (this.paths[0] === '/accessories' || this.paths[1] === '/accessories' || this.paths[0] === '/') {
deleted checkPaths() as unused

2021-01-26 12:26 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/14-modules-routing/modules-routing/src/app/services/check-routing.service.ts
> +    if (this.paths[0] === '/accessories' || this.paths[1] === '/accessories' || this.paths[0] === '/') {
used in comparePaths()

2021-01-26 12:26 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/14-modules-routing/modules-routing/src/app/services/check-routing.service.ts
> +    if (JSON.stringify(this.movingPaths[0]['journey']) === JSON.stringify(this.paths)) {
used forEach

2021-01-26 12:26 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/14-modules-routing/modules-routing/src/app/services/check-routing.service.ts
> +      this.paths.push(url)
ok, deleted)

2021-01-26 22:20 UTC, TArch64 approved these changes

2021-01-26 22:20 UTC, merged