14 modules routing
MastersAcademy/frontend-course-2020 pull request #373
Opened 2021-01-24 18:06 UTC by andrey241991

https://andrey241991.github.io/frontend-course-2020/homeworks/andrey.kushch_andrey241991/modules-routing/dist/modules-routing

2021-01-25 17:54 UTC, TArch64 requested changes

2021-01-25 17:54 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/modules-routing/src/app/services/path.service.ts
> +        this.actualPathes = [];
метод з назвою `showResult` не має очищувати ніяких масив. Це не очевидно. Винеси це за межі цього метода

2021-01-27 15:16 UTC, TArch64 commented
@andrey241991 На гітхабі ніяких нових змін. Ти точно запушив?

2021-01-27 18:33 UTC, andrey241991 commented
> @andrey241991 На гітхабі ніяких нових змін. Ти точно запушив?

Пушил, но недопушил, VS code решил вдруг что у меня неправильные криды и не дает мне запушить

2021-01-28 09:30 UTC, TArch64 approved these changes

2021-01-28 09:30 UTC, merged