14-modules-routing
MastersAcademy/frontend-course-2020 pull request #377
Opened 2021-01-24 22:10 UTC by MykYarovenko36

https://mykyarovenko36.github.io/frontend-course-2020/homeworks/mykola.yarovenko_MykYarovenko36/14-modules-routing/dist/modules-routing/

2021-01-25 21:31 UTC, AlexKuskov requested changes
я бачу, що якщо декілька раз поклікать на `home -> account -> home -> account...` то текст виводиться, але якщо брати випадок коли я тільки-но перехожу по лінкі, і пробую одну з послідовностей із скріна, ні одна з них не виводить в консоль текст.
![image](https://user-images.githubusercontent.com/24815257/105767894-4ee60d80-5f64-11eb-8ca0-2bb815367681.png)

тобто щоб зрепродюсить багу потрібно перейти по лінкі, і зразу ж спробувати ввести комбінації

2021-01-25 22:00 UTC, MykYarovenko36 commented
Це відбуваєтья через те, що перший запис до массиву виконується після переходу на посилання. Тобто при початковому завантаженні відсутній редирект на сторінку home, апка стартує з порожньї лінки. В принципі зрозумів та спробую виправити.

2021-01-26 19:51 UTC, AlexKuskov requested changes
баги про які я говорив вище, все ще залишились. Я подивився на реалізацію, і закинув декілька коментів. Після їх фікса, всі баги автоматично пофіксяться з ними

2021-01-26 19:51 UTC, AlexKuskov commented on homeworks/mykola.yarovenko_MykYarovenko36/14-modules-routing/src/app/services/journey-service.ts
> +      if(this.currentPathes.length === 3) {
виконання функції показу месседжа тільки коли довжина currentPathes === 3 призводить до наступного багу:
Розглянемо такий сценарій: юзер клікнув на  `'/accessories'`, і після цього хоче викликати текст в консолі від послідовності `'/account', '/home', '/account'`:
1. юзер клікає по такому шляху - `'/accessories', '/account', '/home'`
2. виконується  `this.showResult();` - нічого не виводиться, в `this.currentPathes` залишається тільки` '/home'`
3. потім юзер клікає `'/account' `і нічого не відбувається, тому що на даний момент в  `this.currentPathes` тільки `'/home', '/account'`

відповідно до умови завдання `При первом неправильном переходе история переходов должна обнулиться и начаться заново с этого роута.`, потрібно при кожному переході по ссилках викликати перевірку, чи послідовність `journeyPathes` співпадає. Якщо не співпадає, то обнуляти `this.currentPathes`, при цьому залишаючи останній клікнутий шлях

2021-01-26 19:51 UTC, AlexKuskov commented on homeworks/mykola.yarovenko_MykYarovenko36/14-modules-routing/src/app/services/journey-service.ts
> +    this.currentPathes.splice(0, 2);
коли юзер вводить комбінацію `'/home', '/account', '/accessories' `а потім `'/account', '/home', '/account'`, то він очікує що буде виводитись 2 месседжа, але виведеться тільки перший месседж, тому що другий раз комбінація буде 
` ''/accessories', '/account', '/home', '/account'`.

2021-01-26 19:51 UTC, AlexKuskov commented on homeworks/mykola.yarovenko_MykYarovenko36/14-modules-routing/src/app/services/journey-service.ts
> +    this.currentPathes = ['/home'];
не потрібно добавляти роут, по якому юзер не переходив. Нехай він спочатку буде пустим

2021-01-26 19:51 UTC, AlexKuskov commented on homeworks/mykola.yarovenko_MykYarovenko36/14-modules-routing/src/app/services/journey-service.ts
> +      if(this.currentPathes.length === 3) {
`...при цьому залишаючи останній клікнутий шлях`
залишати останній клікнутий шлях потрібно тільки в тому випадку, якщо послідовність неправильна. Якщо виконався повноцінний перехід по` '/account', '/home', '/account'`, то потрібно очищати масив з переходами повністю

2021-01-27 18:51 UTC, MykYarovenko36 commented on homeworks/mykola.yarovenko_MykYarovenko36/14-modules-routing/src/app/services/journey-service.ts
> +    this.currentPathes = ['/home'];
Сподіваюсь,  що мені вдалось задовольнити вимоги до завдання =)

2021-01-27 19:53 UTC, AlexKuskov commented on homeworks/mykola.yarovenko_MykYarovenko36/14-modules-routing/src/app/services/journey-service.ts
> +    console.log(message);
оскільки ця функція має тільки одну строчку, і використовується тільки в одному місці, то можна було `console.log(message);` записати зразу ж, без закидання в функцію

2021-01-27 19:54 UTC, AlexKuskov approved these changes

2021-01-27 20:00 UTC, AlexKuskov commented
Замітка на майбутнє:
Один із важливих навиків хорошого девелопера - це вміння добре тестувати свій код, і продумувати різні сценарії використання свого аплікейшна

2021-01-27 20:00 UTC, merged