hw2 fixed
MastersAcademy/frontend-course-2020 pull request #60
Opened 2020-10-28 18:28 UTC by VolodymyrUstilkin

github page:
https://volodymyrustilkin.github.io/frontend-course-2020/

screen:
![2-dom](https://user-images.githubusercontent.com/73192689/97480412-08304980-195c-11eb-9239-c081ef6248c8.png)

2020-10-29 14:37 UTC, powerbot15 requested changes

2020-10-29 14:37 UTC, powerbot15 commented on homeworks/volodymyr.ustilkin_VolodymyrUstilkin/2-DOM/submitButtonClickEvent.js
> +    .addEventListener('click', addNewMessage);
Код в каждом файле должен быть обернут в самовызывающуюся функцию, чтобы не допустить попадания имен функций и переменных в глобальное пространство имен
```
(function () {
    // code here
})();
```

2020-10-29 14:37 UTC, powerbot15 commented on homeworks/volodymyr.ustilkin_VolodymyrUstilkin/2-DOM/submitButtonClickEvent.js
> +    textContainer.setAttribute('class', 'message-container');
Лучше использовать метод для добавления класса, а не аттрибута
`element.classList.add('classname');`

2020-10-29 14:37 UTC, powerbot15 commented on homeworks/volodymyr.ustilkin_VolodymyrUstilkin/2-DOM/submitButtonClickEvent.js
> +    textContainer.innerHTML = text;
возможна XSS атака, используй `innerText`

2020-10-29 14:37 UTC, powerbot15 commented on homeworks/volodymyr.ustilkin_VolodymyrUstilkin/2-DOM/submitButtonClickEvent.js
> +    if (textCorrectCheck(cleanedText)) {
Вызов функции здесь лишний, пустая строка сама по себе будет `false` в выражении 
```
if (cleanedText) {
```

2020-10-29 14:37 UTC, powerbot15 commented on homeworks/volodymyr.ustilkin_VolodymyrUstilkin/2-DOM/index.html
> +        <button id="submit-button" class="submit-button">Submit</button>
Всегда добавляй тип к кнопке, по умолчанию любая кнопка имеет тип submit, и это часто приводит к сайд-эффектам. Добавь `type="button"`

2020-10-29 18:30 UTC, VolodymyrUstilkin commented on homeworks/volodymyr.ustilkin_VolodymyrUstilkin/2-DOM/index.html
> +        <button id="submit-button" class="submit-button">Submit</button>
fixed

2020-10-29 18:30 UTC, VolodymyrUstilkin commented on homeworks/volodymyr.ustilkin_VolodymyrUstilkin/2-DOM/submitButtonClickEvent.js
> +    if (textCorrectCheck(cleanedText)) {
fixed

2020-10-29 18:32 UTC, VolodymyrUstilkin commented on homeworks/volodymyr.ustilkin_VolodymyrUstilkin/2-DOM/submitButtonClickEvent.js
> +    textContainer.setAttribute('class', 'message-container');
fixed

2020-10-30 08:59 UTC, powerbot15 approved these changes

2020-10-30 09:00 UTC, merged