2 homework
MastersAcademy/frontend-course-2020 pull request #62
Opened 2020-10-28 19:08 UTC by RostyslavHavuka

<img width="946" alt="Screenshot 2020-10-28 at 17 42 25" src="https://user-images.githubusercontent.com/70710636/97484684-bee2f880-1961-11eb-81d8-ed302c3c9965.png">

2020-10-29 15:58 UTC, powerbot15 requested changes

2020-10-29 15:58 UTC, powerbot15 commented on homeworks/rostyslav.havuka_RostyslavHavuka/simpleChat/index.html
> +            </div>
Это должна быть кнопка `<button type="button">`

2020-10-29 15:58 UTC, powerbot15 commented on homeworks/rostyslav.havuka_RostyslavHavuka/simpleChat/index.html
> +            </div>
Тут должен быть список кнопок

2020-10-29 15:58 UTC, powerbot15 commented on homeworks/rostyslav.havuka_RostyslavHavuka/simpleChat/main.js
> +        messageBubble.innerHTML = messege;
Здесь надо использовать `innerText`

2020-10-29 15:58 UTC, powerbot15 commented on homeworks/rostyslav.havuka_RostyslavHavuka/simpleChat/main.js
> +        if (event.type === 'mouseup') mainAppFlow();
Здесь не нужна проверка, у тебя в любом случае сюда придет `mouseup` (когда исправишь - `click`)

2020-10-29 15:58 UTC, powerbot15 commented on homeworks/rostyslav.havuka_RostyslavHavuka/simpleChat/main.js
> +    button.addEventListener('mouseup', clickHandler);
Здесь `click` ивент

2020-10-29 19:54 UTC, RostyslavHavuka commented on homeworks/rostyslav.havuka_RostyslavHavuka/simpleChat/main.js
> +        if (event.type === 'mouseup') mainAppFlow();
Дякую, така цікава поведінка кліка для мене була не очікувана.

2020-10-30 08:47 UTC, powerbot15 approved these changes

2020-10-30 08:47 UTC, merged