dz_chat
MastersAcademy/frontend-course-2020 pull request #84
Opened 2020-10-30 20:06 UTC by IgorES1

Chat
![dz-2](https://user-images.githubusercontent.com/71279315/97752088-0e5d2c00-1afc-11eb-89b8-2ebbe10f972d.png)

2020-10-31 10:23 UTC, TArch64 requested changes
у тебе там лінтери помилки показали Пофіксь їх спочатку.
Зроби без джейквері. Ця штука потрохи вмирає і писати новий код де ця штука не потрібна (це 99.9% випадків) є погано. Ми тут вчимося робити хорошо і без джеквері

2020-11-02 13:32 UTC, IgorES1 commented
Пофиксил. Сылка на работу
https://igores1.github.io/frontend-course-2020/homeworks/igor.borovko_IgorES1/2-dom/?fbclid=IwAR3RDycNFXI8qOlShm7J8nWoBA9kMBUbbY7DI3Ijra803ZxwcmQ6fwOIns0

2020-11-02 17:40 UTC, TArch64 requested changes

2020-11-02 17:40 UTC, TArch64 commented on homeworks/igor.borovko_IgorES1/2-dom/index.css
> +input {
за виключенням `body` та `html` стилі вішай тільки через класи

2020-11-02 17:40 UTC, TArch64 commented on homeworks/igor.borovko_IgorES1/2-dom/index.html
> +        <p>
для чого тут `<p>`?

2020-11-02 17:40 UTC, TArch64 commented on homeworks/igor.borovko_IgorES1/2-dom/index.html
> +                style="display: block; margin-left: auto; margin-right: auto"
винеси стилі в класи

2020-11-02 17:40 UTC, TArch64 commented on homeworks/igor.borovko_IgorES1/2-dom/index.html
> +        <div class="pichat">
не використовуй трансліт в назвах

2020-11-02 17:40 UTC, TArch64 commented on homeworks/igor.borovko_IgorES1/2-dom/index.html
> +            <div id="pechat"></div>
для чого тут `<div>` всередині `<div>`? Чому не можна тільки одним?

2020-11-02 17:40 UTC, TArch64 commented on homeworks/igor.borovko_IgorES1/2-dom/index.html
> +        <div id="msg">
`<div id="msg">` зроби формою і слухай в неї `submit` івент. Не забудься потім додати `event.preventDefault()`

2020-11-02 17:40 UTC, TArch64 commented on homeworks/igor.borovko_IgorES1/2-dom/index.js
> +const userText = document.querySelector('#userText');
шукай елементи в домі по `data-` атрибутах

2020-11-02 17:40 UTC, TArch64 commented on homeworks/igor.borovko_IgorES1/2-dom/index.js
> +function Submit() {
Функції називаються в `camelCase`. Якщо назва капсом починається то це означає що це конструктор, а це ні разу не конструктор

2020-11-02 17:40 UTC, TArch64 commented on homeworks/igor.borovko_IgorES1/2-dom/index.js
> +    const text = userText.value;
роби трім перед перевірками `text = userText.value.trim()` бо потім вийде отаке
```js
const text = userText.value; // value = '        '
if (!text) return; // !text = false
const li = document.createElement('li');
li.innerText = text.trim(); // li.innerText = ''
```

2020-11-05 07:01 UTC, TArch64 commented
Пулл реквест все ще вимагає правок і не встиг по делайну

2020-11-05 07:01 UTC, closed without merging