2 dom
MastersAcademy/frontend-course-2020 pull request #90
Opened 2020-10-31 10:59 UTC by Anna1o1Vrana

https://anna1o1vrana.github.io/frontend-course-2020/homeworks/anna.vrana_Anna1o1Vrana/2-dom/  
 у функції альтернатива else створена на випадок, якщо темплейт не підтримується - тоді повідомлення виводиться в дів. Маме тому може виводитись пуста строка
![Screenshot from 2020-10-30 17-07-44](https://user-images.githubusercontent.com/72143197/97777432-caf4d300-1b78-11eb-89b5-fa482cf8e8d8.png)

2020-11-01 10:45 UTC, TArch64 requested changes

2020-11-01 10:45 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/2-dom/index.html
> +            <p id="valueResualt" class="message hide"></p>
valueRes**ual**t -> valueRes**ul**t

У тебе там опечатка

2020-11-01 10:45 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/2-dom/scripts.js
> +    if (newTxt.trim() !== '' && 'content' in document.createElement('template')) {
`'content' in document.createElement('template')` не потрібно робити. `<template>` підтримується скрізь за виключенням `ie11` (хай люди з цим браузером страждають). Тому краще прибери цю перевірку

2020-11-01 10:45 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/2-dom/scripts.js
> +const valueResualt = document.querySelector('#valueResualt');
шукай в домі за `data-` атрибутами

2020-11-01 10:45 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/2-dom/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Courier+Prime&display=swap" rel="stylesheet">
у тебе цей шрифт не використовується. видали його

2020-11-01 10:45 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/2-dom/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Courier+Prime&display=swap" rel="stylesheet">
`<link href="https://fonts.googleapis.com/css2?family=Courier+Prime&display=swap" rel="stylesheet">`

2020-11-01 10:45 UTC, TArch64 commented on homeworks/anna.vrana_Anna1o1Vrana/2-dom/index.html
> +        <div class="input-area-wrapper">
зроби це тегом `form` і в нього слухай сабміт івент. так можна буде відправляти меседжі ентер кнопкою
```html
<form class="input-area-wrapper" data-send-form>
    ...other content
</form>
```
І замість `btnSendNode.addEventListener('click', sendMessage);` отаке
```js
document.querySelector('[data-send-form]').addEventListener('submit', event => {
    event.preventDefault();
    sendMessage();
});
```

2020-11-01 15:12 UTC, Anna1o1Vrana commented on homeworks/anna.vrana_Anna1o1Vrana/2-dom/scripts.js
> +    if (newTxt.trim() !== '' && 'content' in document.createElement('template')) {
я ж тут роблю загальну перевірку щоб не створювався <template> для пустої строчки :) чи цю перевірку записати в окрему функцію?

2020-11-03 11:10 UTC, TArch64 approved these changes

2020-11-03 11:10 UTC, merged