2 dom
MastersAcademy/frontend-course-2020 pull request #91
Opened 2020-10-31 11:15 UTC by LigthWarrior

2020-10-31 11:20 UTC, LigthWarrior commented
https://github.com/LigthWarrior/frontend-course-2020/tree/2-dom/homeworks/andrii.stoliarov_lightwarrior/2-dom

2020-10-31 11:23 UTC, LigthWarrior commented
![homework-2-screenshot](https://user-images.githubusercontent.com/58568950/97777944-32f8e880-1b7c-11eb-9f89-d9e9fc6f8915.png)

2020-11-01 16:58 UTC, powerbot15 requested changes

2020-11-01 16:58 UTC, powerbot15 commented on homeworks/andrii.stoliarov_lightwarrior/2-dom/script.js
> +    p.textContent = trimStr;
Не меняй контент темплейта, лучше этот текст установить в уже склонированный элемент

2020-11-01 16:58 UTC, powerbot15 commented on homeworks/andrii.stoliarov_lightwarrior/2-dom/style.css
> +.tooltip {
Это плохое название для класса, который только прячет элемент. Назови его хотя бы `hidden`

2020-11-01 16:58 UTC, powerbot15 commented on homeworks/andrii.stoliarov_lightwarrior/2-dom/style.css
> +input {
Имена тегов в качестве селекторов первого уровня - плохая практика, используй класс

2020-11-01 16:58 UTC, powerbot15 commented on homeworks/andrii.stoliarov_lightwarrior/2-dom/script.js
> +const formPublish = document.forms.publish;
Эту переменную можно убрать. Выбери инпут и кнопку через `querySelector`. Прямое обращение к формам и их полям - слабораспространенная практика.

2020-11-01 16:58 UTC, powerbot15 commented on homeworks/andrii.stoliarov_lightwarrior/2-dom/index.html
> +      <div>
Этот див лишний, оставь в темплейте только`p`

2020-11-01 17:01 UTC, powerbot15 commented
В дополнение к ревью 
  - ссылка на гитхаб-пейджес отсутствует, почитай здесь как сделать https://pages.github.com/ 
  - оберни весь JS код в самовызывающуюся функцию (IIFE) чтобы имена твоих функций не попали в глобальный скоуп window
```
(function () {
    // your code here
})();
```

2020-11-02 13:18 UTC, powerbot15 requested changes

2020-11-02 13:18 UTC, powerbot15 commented on homeworks/andrii.stoliarov_lightwarrior/2-dom/script.js
> +    const hiddenStatus = document.querySelector('[data-status]');
Вот тут не надо называть переменную `hiddenStatus` - назови ее логично -  `typingStatusEl`, тогда дальше будет понятно, что происходит, элемент прячется или показывается, когда происходит смена класса `hidden-status`

2020-11-02 14:50 UTC, LigthWarrior reviewed
work on changes

2020-11-02 15:55 UTC, LigthWarrior commented
Сделал все изменения, re-request review, обратите, пожалуйста, внимание на
GitHub Pages.

пн, 2 нояб. 2020 г. в 15:18, Oleh Kastornov <notifications@github.com>:

> *@powerbot15* requested changes on this pull request.
> ------------------------------
>
> In homeworks/andrii.stoliarov_lightwarrior/2-dom/script.js
> <https://github.com/MastersAcademy/frontend-course-2020/pull/91#discussion_r515964678>
> :
>
> > +    const messageNode = document.querySelector('[data-message-template]');
>
> +    const clone = messageNode.content.cloneNode(true);
>
> +    const p = clone.querySelector('[data-message]');
>
> +
>
> +    p.textContent = trimStr;
>
> +
>
> +    wallNode.append(clone);
>
> +
>
> +    autoScrollMessages();
>
> +
>
> +    // clear the input field
>
> +    inputMessage.value = '';
>
> +}
>
> +
>
> +function showStatus() {
>
> +    const hiddenStatus = document.querySelector('[data-status]');
>
>
> Вот тут не надо называть переменную hiddenStatus - назови ее логично -
> typingStatusEl, тогда дальше будет понятно, что происходит, элемент
> прячется или показывается, когда происходит смена класса hidden-status
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/MastersAcademy/frontend-course-2020/pull/91#pullrequestreview-521618770>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AN63B5XV3UKY6U36MTW666DSN2WSXANCNFSM4TF2VEYQ>
> .
>

2020-11-03 09:35 UTC, powerbot15 commented
![image](https://user-images.githubusercontent.com/5908792/97969219-6a5bd500-1dc8-11eb-9276-e08af46bd559.png)
Привет, на будущее - перезапрашивать ревью надо с помощью кнопочки))

2020-11-03 09:35 UTC, powerbot15 approved these changes

2020-11-03 09:36 UTC, merged