2 dom
MastersAcademy/frontend-course-2020 pull request #93
Opened 2020-10-31 14:43 UTC by andrey241991

https://andrey241991.github.io/frontend-course-2020/homeworks/andrey.kushch_andrey241991/2-dom/
![2020-10-31_16h20_46](https://user-images.githubusercontent.com/26023192/97782084-2b473d00-1b98-11eb-97e9-70b51dba0bce.png)

2020-10-31 14:56 UTC, TArch64 requested changes
пофіксь помилки які тобі лінтер викидає

2020-10-31 14:56 UTC, TArch64 commented on _config.yml
> +theme: jekyll-theme-cayman
цього файлику тут не повинно бути

2020-10-31 21:58 UTC, andrey241991 commented on _config.yml
> +theme: jekyll-theme-cayman
убрал

2020-11-01 09:57 UTC, TArch64 requested changes

2020-11-01 09:57 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/2-dom/index.html
> +        <style></style>
У тебе тут пустий тег stye

2020-11-01 09:57 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/2-dom/index.html
> +                    <form class="input-form" submit="onSubmit()">
Для слухання івентів використовуй addEventListener. Всі інші варіанти в реальних задачах не використовуються

2020-11-01 09:57 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/2-dom/index.html
> +                        <input type="submit" class="submit" value="Send"/>
Роби кнопки через тег button

2020-11-01 09:57 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/2-dom/index.js
> +const inputElem = document.querySelector('.input');
Для пошуку елементів в домі використовуй `data-` атрибути

2020-11-01 09:57 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/2-dom/index.js
> +    addMessage(message.trim());
Зав‘язувати виклик однієї функції на іншій без видимих на те причин не є добре. Просто виклич 2 свої функції по порядку в лістенері на сабміт

2020-11-01 09:57 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/2-dom/index.js
> +formElem.addEventListener('submit', (e) => {
Якщо ти робиш addEventListener то в html атрибут onsubmit не потрібен

2020-11-01 09:57 UTC, TArch64 commented on homeworks/andrey.kushch_andrey241991/2-dom/style.css
> +.message-wrapper {
Дублювати стилі не є добре. Щроби базовий класс `message-wrapper` який буде завжди на меседжах та буде мати загальні стилі меседжа а також `message-wrapper-left` та `message-wrapper-right`

2020-11-04 16:40 UTC, andrey241991 commented on homeworks/andrey.kushch_andrey241991/2-dom/index.html
> +        <style></style>
случайно туда попал, поправил

2020-11-04 16:40 UTC, andrey241991 commented on homeworks/andrey.kushch_andrey241991/2-dom/index.html
> +                    <form class="input-form" submit="onSubmit()">
случайно туда попал, поправил

2020-11-04 16:40 UTC, andrey241991 commented on homeworks/andrey.kushch_andrey241991/2-dom/index.html
> +                        <input type="submit" class="submit" value="Send"/>
принял, поправил

2020-11-04 16:40 UTC, andrey241991 commented on homeworks/andrey.kushch_andrey241991/2-dom/index.js
> +const inputElem = document.querySelector('.input');
принял, поправил

2020-11-04 16:41 UTC, andrey241991 commented on homeworks/andrey.kushch_andrey241991/2-dom/index.js
> +    addMessage(message.trim());
понял, поправил

2020-11-04 16:41 UTC, andrey241991 commented on homeworks/andrey.kushch_andrey241991/2-dom/index.js
> +formElem.addEventListener('submit', (e) => {
поправил

2020-11-04 16:41 UTC, andrey241991 commented on homeworks/andrey.kushch_andrey241991/2-dom/style.css
> +.message-wrapper {
поправил

2020-11-04 19:16 UTC, TArch64 approved these changes

2020-11-04 19:16 UTC, merged