2 dom - spavel
MastersAcademy/frontend-course-2020 pull request #96
Opened 2020-10-31 17:07 UTC by spavel-gh

[GitHub Pages link](https://spavel-gh.github.io/frontend-course-2020/homeworks/sokurenko.pavel_spavel_gh/2-dom/)

![image](https://user-images.githubusercontent.com/71533482/97785193-37d59080-1bac-11eb-8269-bbdb99678162.png)

2020-10-31 17:30 UTC, spavel-gh commented
А что с проверками делать? Переписывать весь код? Вроде же всё работает и ошибок в консоли нет. Даже вот css прошел валидацию на https://jigsaw.w3.org/css-validator/validator

2020-11-01 01:08 UTC, spavel-gh commented
🥴 вроде сам разобрался, но нужно конкретно заняться этой темой с тестами. Уважаемые менторы-проверяющее, покритикуйте пожалуйста мой JS. ESLint заставил меня располагать вызов функции после её определения, что перевернуло композицию кода вверх дном. Это норм?

2020-11-01 21:59 UTC, TArch64 requested changes

2020-11-01 21:59 UTC, TArch64 commented on homeworks/sokurenko.pavel_spavel_gh/2-dom/index.html
> +        <header class="card-header">
якщо в тебе тут всередині нічого немає то видаляй. Ця штука нічого не робить

2020-11-01 21:59 UTC, TArch64 commented on homeworks/sokurenko.pavel_spavel_gh/2-dom/script.js
> +        const msgTmlpNode = document.querySelector('[msg-tmlp]');
для пошуку елементів в домі використовуй `data-` атрибути. звичайні атрибути та класи не є хорошо

2020-11-01 21:59 UTC, TArch64 commented on homeworks/sokurenko.pavel_spavel_gh/2-dom/script.js
> +// проверка и вырезание пробелов
коменти залишай на англ

2020-11-01 21:59 UTC, TArch64 commented on homeworks/sokurenko.pavel_spavel_gh/2-dom/style.css
> +h1 {
задавай стилі через класи. Теги найбільш проблемний варіант

2020-11-01 21:59 UTC, TArch64 commented on homeworks/sokurenko.pavel_spavel_gh/2-dom/style.css
> +.card > header > h1 ~ * {
якщо немає необхідності то не використовуй вкладеності та отакі тяжкі для розуміння селектори. Зроби клас куди прикріпи ці стилі та додай їх куди тобі потрібно

2020-11-01 21:59 UTC, TArch64 commented on homeworks/sokurenko.pavel_spavel_gh/2-dom/style.css
> +  /* margin-left: auto; */
видаляй закоменчений код

2020-11-01 21:59 UTC, TArch64 commented on homeworks/sokurenko.pavel_spavel_gh/2-dom/style.css
> +.hidden > div {
чому ти просто не додаєш hidden на елемент куди потрібно? Не роби вкладеності в селекторах просто так

2020-11-01 21:59 UTC, TArch64 commented on homeworks/sokurenko.pavel_spavel_gh/2-dom/style.css
> +.loader-2 {
для чого тут в назві 2?

2020-11-01 22:00 UTC, TArch64 commented on homeworks/sokurenko.pavel_spavel_gh/2-dom/index.html
> +    <script type="text/javascript" src="script.js" defer></script>
Перемісти цей скріпт в кінець баді. В хеді тег defer нічого не робить. Як перемістиш то видали `window.onload` бо він там буде не потрібен

2020-11-01 23:21 UTC, spavel-gh commented on homeworks/sokurenko.pavel_spavel_gh/2-dom/index.html
> +    <script type="text/javascript" src="script.js" defer></script>
> В хеді тег defer нічого не робить.

> Як перемістиш то видали `window.onload` бо він там буде не потрібен

Я удалил `window.onload = function () {` и `}`, оставив код вне функции, который, естественно, обязан выполнится как только браузер найдёт **_script.js_** в `<head> </head>` . 

И да, без `defer`, конечно же, ничего не работает. Но если его вернуть, то весь проект снова работает корректно! 

То есть `defer` в `<head> </head>` в моём случае работает.
Если гуглить по ключевым словам, можно найти только [подтверждение этому](https://flaviocopes.com/javascript-async-defer/#with-defer-in-the-head). И в [w3schools](https://www.w3schools.com/tags/att_script_defer.asp) нет ни слова о неработоспособности `defer` в `<head> </head>`.

Я думаю оставить подключение скрипта как есть, но от `window.onload` и правда можно избавиться. Что скажите?

2020-11-02 17:28 UTC, TArch64 commented on homeworks/sokurenko.pavel_spavel_gh/2-dom/index.html
> +    <script type="text/javascript" src="script.js" defer></script>
Нуууу хай тоді буде в хеді

2020-11-02 17:31 UTC, TArch64 requested changes

2020-11-02 17:31 UTC, TArch64 commented on homeworks/sokurenko.pavel_spavel_gh/2-dom/index.html
> +                <div msg-send class="btn-target">
`msg-send` не використовується

2020-11-02 17:31 UTC, TArch64 commented on homeworks/sokurenko.pavel_spavel_gh/2-dom/index.html
> +                    <div data-msg-send2 class="btn-send" title="Ctrl+Enter"></div>
кліки слухай у кнопок. Слухання кліку на дівові дуже погано з точки зору семантики

2020-11-02 17:32 UTC, TArch64 commented
> 🥴 вроде сам разобрался, но нужно конкретно заняться этой темой с тестами. Уважаемые менторы-проверяющее, покритикуйте пожалуйста мой JS. ESLint заставил меня располагать вызов функции после её определения, что перевернуло композицию кода вверх дном. Это норм?

це ок. Зазвичай так і роблять щоб потім уникнути дивних ситуацій на проді коли немає функції яку ти хочеш викликати

2020-11-02 21:24 UTC, TArch64 approved these changes

2020-11-03 09:52 UTC, merged